// -------------------------------------------------------------
// 
// File Name: hdlsrc\dsp_proj_v3_2024_n\Chart.v
// Created: 2026-04-12 08:40:34
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Chart
// Source Path: dsp_proj_v3_2024_n/Chart
// Hierarchy Level: 1
// Model version: 3.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Chart
          (clk,
           reset,
           enb,
           EN,
           Process);

  // Default encoded enumeration values for type state_type_is_Chart
  parameter state_type_is_Chart_IN_Data_Loading = 1'd0, state_type_is_Chart_IN_Processing = 1'd1;

  input   clk;
  input   reset;
  input   enb;
  input   EN;
  output  Process;


  reg  Process_1;
  reg  is_Chart;  // uint8
  reg  is_Chart_next;  // enum type state_type_is_Chart (2 enums)


  always @(posedge clk or posedge reset)
    begin : Chart_1_process
      if (reset == 1'b1) begin
        is_Chart <= state_type_is_Chart_IN_Data_Loading;
      end
      else begin
        if (enb) begin
          is_Chart <= is_Chart_next;
        end
      end
    end

  always @(EN, is_Chart) begin
    is_Chart_next = is_Chart;
    //case IN_Processing:
    case ( is_Chart)
      state_type_is_Chart_IN_Data_Loading :
        begin
          if (EN) begin
            is_Chart_next = state_type_is_Chart_IN_Processing;
          end
        end
    endcase
  end

  always @(is_Chart) begin
    case ( is_Chart)
      state_type_is_Chart_IN_Data_Loading :
        begin
          Process_1 = 1'b0;
        end
      default :
        begin
          //case IN_Processing:
          Process_1 = 1'b1;
        end
    endcase
  end

  assign Process = Process_1;

endmodule  // Chart

