// -------------------------------------------------------------
// 
// File Name: hdlsrc\dsp_proj_v3_2024_n\Discrete_FIR_Filter.v
// Created: 2026-04-12 08:40:34
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Discrete_FIR_Filter
// Source Path: dsp_proj_v3_2024_n/Discrete FIR Filter
// Hierarchy Level: 1
// Model version: 3.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Discrete_FIR_Filter
          (clk,
           reset,
           enb,
           Discrete_FIR_Filter_in_re,
           Discrete_FIR_Filter_in_im,
           Discrete_FIR_Filter_out_re,
           Discrete_FIR_Filter_out_im);


  input   clk;
  input   reset;
  input   enb;
  input   signed [7:0] Discrete_FIR_Filter_in_re;  // sfix8_En6
  input   signed [7:0] Discrete_FIR_Filter_in_im;  // sfix8_En6
  output  signed [63:0] Discrete_FIR_Filter_out_re;  // sfix64_En30
  output  signed [63:0] Discrete_FIR_Filter_out_im;  // sfix64_En30


  reg signed [7:0] tapped_delay_reg_re [0:115];  // sfix8_En6 [116]
  reg signed [7:0] tapped_delay_reg_im [0:115];  // sfix8_En6 [116]
  reg signed [7:0] tapped_delay_reg_next_re [0:115];  // sfix8_En6 [116]
  reg signed [7:0] tapped_delay_reg_next_im [0:115];  // sfix8_En6 [116]
  reg signed [7:0] delay_pipeline_re [0:115];  // sfix8_En6 [116]
  reg signed [7:0] delay_pipeline_im [0:115];  // sfix8_En6 [116]
  wire signed [7:0] delay116_re;  // sfix8_En6
  wire signed [7:0] delay116_im;  // sfix8_En6
  wire signed [7:0] combined0_re;  // sfix8_En6
  wire signed [7:0] combined0_im;  // sfix8_En6
  wire signed [32:0] gain0_mul_temp;  // sfix33_En30
  wire signed [32:0] gain0_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain0_re;  // sfix34_En30
  wire signed [33:0] gain0_im;  // sfix34_En30
  wire signed [7:0] delay1_re;  // sfix8_En6
  wire signed [7:0] delay1_im;  // sfix8_En6
  wire signed [7:0] delay115_re;  // sfix8_En6
  wire signed [7:0] delay115_im;  // sfix8_En6
  wire signed [7:0] combined1_re;  // sfix8_En6
  wire signed [7:0] combined1_im;  // sfix8_En6
  wire signed [32:0] gain1_mul_temp;  // sfix33_En30
  wire signed [32:0] gain1_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain1_re;  // sfix34_En30
  wire signed [33:0] gain1_im;  // sfix34_En30
  wire signed [63:0] add_add_cast;  // sfix64_En30
  wire signed [63:0] add_add_cast_1;  // sfix64_En30
  wire signed [63:0] add_add_cast_2;  // sfix64_En30
  wire signed [63:0] add_add_cast_3;  // sfix64_En30
  wire signed [63:0] add_re;  // sfix64_En30
  wire signed [63:0] add_im;  // sfix64_En30
  wire signed [7:0] delay2_re;  // sfix8_En6
  wire signed [7:0] delay2_im;  // sfix8_En6
  wire signed [7:0] delay114_re;  // sfix8_En6
  wire signed [7:0] delay114_im;  // sfix8_En6
  wire signed [7:0] combined2_re;  // sfix8_En6
  wire signed [7:0] combined2_im;  // sfix8_En6
  wire signed [32:0] gain2_mul_temp;  // sfix33_En30
  wire signed [32:0] gain2_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain2_re;  // sfix34_En30
  wire signed [33:0] gain2_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_4;  // sfix64_En30
  wire signed [63:0] add_add_cast_5;  // sfix64_En30
  wire signed [63:0] add_re_1;  // sfix64_En30
  wire signed [63:0] add_im_1;  // sfix64_En30
  wire signed [7:0] delay3_re;  // sfix8_En6
  wire signed [7:0] delay3_im;  // sfix8_En6
  wire signed [7:0] delay113_re;  // sfix8_En6
  wire signed [7:0] delay113_im;  // sfix8_En6
  wire signed [7:0] combined3_re;  // sfix8_En6
  wire signed [7:0] combined3_im;  // sfix8_En6
  wire signed [32:0] gain3_mul_temp;  // sfix33_En30
  wire signed [32:0] gain3_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain3_re;  // sfix34_En30
  wire signed [33:0] gain3_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_6;  // sfix64_En30
  wire signed [63:0] add_add_cast_7;  // sfix64_En30
  wire signed [63:0] add_re_2;  // sfix64_En30
  wire signed [63:0] add_im_2;  // sfix64_En30
  wire signed [7:0] delay4_re;  // sfix8_En6
  wire signed [7:0] delay4_im;  // sfix8_En6
  wire signed [7:0] delay112_re;  // sfix8_En6
  wire signed [7:0] delay112_im;  // sfix8_En6
  wire signed [7:0] combined4_re;  // sfix8_En6
  wire signed [7:0] combined4_im;  // sfix8_En6
  wire signed [32:0] gain4_mul_temp;  // sfix33_En30
  wire signed [32:0] gain4_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain4_re;  // sfix34_En30
  wire signed [33:0] gain4_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_8;  // sfix64_En30
  wire signed [63:0] add_add_cast_9;  // sfix64_En30
  wire signed [63:0] add_re_3;  // sfix64_En30
  wire signed [63:0] add_im_3;  // sfix64_En30
  wire signed [7:0] delay5_re;  // sfix8_En6
  wire signed [7:0] delay5_im;  // sfix8_En6
  wire signed [7:0] delay111_re;  // sfix8_En6
  wire signed [7:0] delay111_im;  // sfix8_En6
  wire signed [7:0] combined5_re;  // sfix8_En6
  wire signed [7:0] combined5_im;  // sfix8_En6
  wire signed [32:0] gain5_mul_temp;  // sfix33_En30
  wire signed [32:0] gain5_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain5_re;  // sfix34_En30
  wire signed [33:0] gain5_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_10;  // sfix64_En30
  wire signed [63:0] add_add_cast_11;  // sfix64_En30
  wire signed [63:0] add_re_4;  // sfix64_En30
  wire signed [63:0] add_im_4;  // sfix64_En30
  wire signed [7:0] delay6_re;  // sfix8_En6
  wire signed [7:0] delay6_im;  // sfix8_En6
  wire signed [7:0] delay110_re;  // sfix8_En6
  wire signed [7:0] delay110_im;  // sfix8_En6
  wire signed [7:0] combined6_re;  // sfix8_En6
  wire signed [7:0] combined6_im;  // sfix8_En6
  wire signed [32:0] gain6_mul_temp;  // sfix33_En30
  wire signed [32:0] gain6_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain6_re;  // sfix34_En30
  wire signed [33:0] gain6_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_12;  // sfix64_En30
  wire signed [63:0] add_add_cast_13;  // sfix64_En30
  wire signed [63:0] add_re_5;  // sfix64_En30
  wire signed [63:0] add_im_5;  // sfix64_En30
  wire signed [7:0] delay7_re;  // sfix8_En6
  wire signed [7:0] delay7_im;  // sfix8_En6
  wire signed [7:0] delay109_re;  // sfix8_En6
  wire signed [7:0] delay109_im;  // sfix8_En6
  wire signed [7:0] combined7_re;  // sfix8_En6
  wire signed [7:0] combined7_im;  // sfix8_En6
  wire signed [32:0] gain7_mul_temp;  // sfix33_En30
  wire signed [32:0] gain7_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain7_re;  // sfix34_En30
  wire signed [33:0] gain7_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_14;  // sfix64_En30
  wire signed [63:0] add_add_cast_15;  // sfix64_En30
  wire signed [63:0] add_re_6;  // sfix64_En30
  wire signed [63:0] add_im_6;  // sfix64_En30
  wire signed [7:0] delay8_re;  // sfix8_En6
  wire signed [7:0] delay8_im;  // sfix8_En6
  wire signed [7:0] delay108_re;  // sfix8_En6
  wire signed [7:0] delay108_im;  // sfix8_En6
  wire signed [7:0] combined8_re;  // sfix8_En6
  wire signed [7:0] combined8_im;  // sfix8_En6
  wire signed [32:0] gain8_mul_temp;  // sfix33_En30
  wire signed [32:0] gain8_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain8_re;  // sfix34_En30
  wire signed [33:0] gain8_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_16;  // sfix64_En30
  wire signed [63:0] add_add_cast_17;  // sfix64_En30
  wire signed [63:0] add_re_7;  // sfix64_En30
  wire signed [63:0] add_im_7;  // sfix64_En30
  wire signed [7:0] delay9_re;  // sfix8_En6
  wire signed [7:0] delay9_im;  // sfix8_En6
  wire signed [7:0] delay107_re;  // sfix8_En6
  wire signed [7:0] delay107_im;  // sfix8_En6
  wire signed [7:0] combined9_re;  // sfix8_En6
  wire signed [7:0] combined9_im;  // sfix8_En6
  wire signed [32:0] gain9_mul_temp;  // sfix33_En30
  wire signed [32:0] gain9_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain9_re;  // sfix34_En30
  wire signed [33:0] gain9_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_18;  // sfix64_En30
  wire signed [63:0] add_add_cast_19;  // sfix64_En30
  wire signed [63:0] add_re_8;  // sfix64_En30
  wire signed [63:0] add_im_8;  // sfix64_En30
  wire signed [7:0] delay10_re;  // sfix8_En6
  wire signed [7:0] delay10_im;  // sfix8_En6
  wire signed [7:0] delay106_re;  // sfix8_En6
  wire signed [7:0] delay106_im;  // sfix8_En6
  wire signed [7:0] combined10_re;  // sfix8_En6
  wire signed [7:0] combined10_im;  // sfix8_En6
  wire signed [32:0] gain10_mul_temp;  // sfix33_En30
  wire signed [32:0] gain10_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain10_re;  // sfix34_En30
  wire signed [33:0] gain10_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_20;  // sfix64_En30
  wire signed [63:0] add_add_cast_21;  // sfix64_En30
  wire signed [63:0] add_re_9;  // sfix64_En30
  wire signed [63:0] add_im_9;  // sfix64_En30
  wire signed [7:0] delay11_re;  // sfix8_En6
  wire signed [7:0] delay11_im;  // sfix8_En6
  wire signed [7:0] delay105_re;  // sfix8_En6
  wire signed [7:0] delay105_im;  // sfix8_En6
  wire signed [7:0] combined11_re;  // sfix8_En6
  wire signed [7:0] combined11_im;  // sfix8_En6
  wire signed [32:0] gain11_mul_temp;  // sfix33_En30
  wire signed [32:0] gain11_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain11_re;  // sfix34_En30
  wire signed [33:0] gain11_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_22;  // sfix64_En30
  wire signed [63:0] add_add_cast_23;  // sfix64_En30
  wire signed [63:0] add_re_10;  // sfix64_En30
  wire signed [63:0] add_im_10;  // sfix64_En30
  wire signed [7:0] delay12_re;  // sfix8_En6
  wire signed [7:0] delay12_im;  // sfix8_En6
  wire signed [7:0] delay104_re;  // sfix8_En6
  wire signed [7:0] delay104_im;  // sfix8_En6
  wire signed [7:0] combined12_re;  // sfix8_En6
  wire signed [7:0] combined12_im;  // sfix8_En6
  wire signed [32:0] gain12_mul_temp;  // sfix33_En30
  wire signed [32:0] gain12_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain12_re;  // sfix34_En30
  wire signed [33:0] gain12_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_24;  // sfix64_En30
  wire signed [63:0] add_add_cast_25;  // sfix64_En30
  wire signed [63:0] add_re_11;  // sfix64_En30
  wire signed [63:0] add_im_11;  // sfix64_En30
  wire signed [7:0] delay13_re;  // sfix8_En6
  wire signed [7:0] delay13_im;  // sfix8_En6
  wire signed [7:0] delay103_re;  // sfix8_En6
  wire signed [7:0] delay103_im;  // sfix8_En6
  wire signed [7:0] combined13_re;  // sfix8_En6
  wire signed [7:0] combined13_im;  // sfix8_En6
  wire signed [32:0] gain13_mul_temp;  // sfix33_En30
  wire signed [32:0] gain13_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain13_re;  // sfix34_En30
  wire signed [33:0] gain13_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_26;  // sfix64_En30
  wire signed [63:0] add_add_cast_27;  // sfix64_En30
  wire signed [63:0] add_re_12;  // sfix64_En30
  wire signed [63:0] add_im_12;  // sfix64_En30
  wire signed [7:0] delay14_re;  // sfix8_En6
  wire signed [7:0] delay14_im;  // sfix8_En6
  wire signed [7:0] delay102_re;  // sfix8_En6
  wire signed [7:0] delay102_im;  // sfix8_En6
  wire signed [7:0] combined14_re;  // sfix8_En6
  wire signed [7:0] combined14_im;  // sfix8_En6
  wire signed [32:0] gain14_mul_temp;  // sfix33_En30
  wire signed [32:0] gain14_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain14_re;  // sfix34_En30
  wire signed [33:0] gain14_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_28;  // sfix64_En30
  wire signed [63:0] add_add_cast_29;  // sfix64_En30
  wire signed [63:0] add_re_13;  // sfix64_En30
  wire signed [63:0] add_im_13;  // sfix64_En30
  wire signed [7:0] delay15_re;  // sfix8_En6
  wire signed [7:0] delay15_im;  // sfix8_En6
  wire signed [7:0] delay101_re;  // sfix8_En6
  wire signed [7:0] delay101_im;  // sfix8_En6
  wire signed [7:0] combined15_re;  // sfix8_En6
  wire signed [7:0] combined15_im;  // sfix8_En6
  wire signed [32:0] gain15_mul_temp;  // sfix33_En30
  wire signed [32:0] gain15_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain15_re;  // sfix34_En30
  wire signed [33:0] gain15_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_30;  // sfix64_En30
  wire signed [63:0] add_add_cast_31;  // sfix64_En30
  wire signed [63:0] add_re_14;  // sfix64_En30
  wire signed [63:0] add_im_14;  // sfix64_En30
  wire signed [7:0] delay16_re;  // sfix8_En6
  wire signed [7:0] delay16_im;  // sfix8_En6
  wire signed [7:0] delay100_re;  // sfix8_En6
  wire signed [7:0] delay100_im;  // sfix8_En6
  wire signed [7:0] combined16_re;  // sfix8_En6
  wire signed [7:0] combined16_im;  // sfix8_En6
  wire signed [32:0] gain16_mul_temp;  // sfix33_En30
  wire signed [32:0] gain16_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain16_re;  // sfix34_En30
  wire signed [33:0] gain16_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_32;  // sfix64_En30
  wire signed [63:0] add_add_cast_33;  // sfix64_En30
  wire signed [63:0] add_re_15;  // sfix64_En30
  wire signed [63:0] add_im_15;  // sfix64_En30
  wire signed [7:0] delay17_re;  // sfix8_En6
  wire signed [7:0] delay17_im;  // sfix8_En6
  wire signed [7:0] delay99_re;  // sfix8_En6
  wire signed [7:0] delay99_im;  // sfix8_En6
  wire signed [7:0] combined17_re;  // sfix8_En6
  wire signed [7:0] combined17_im;  // sfix8_En6
  wire signed [32:0] gain17_mul_temp;  // sfix33_En30
  wire signed [32:0] gain17_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain17_re;  // sfix34_En30
  wire signed [33:0] gain17_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_34;  // sfix64_En30
  wire signed [63:0] add_add_cast_35;  // sfix64_En30
  wire signed [63:0] add_re_16;  // sfix64_En30
  wire signed [63:0] add_im_16;  // sfix64_En30
  wire signed [7:0] delay18_re;  // sfix8_En6
  wire signed [7:0] delay18_im;  // sfix8_En6
  wire signed [7:0] delay98_re;  // sfix8_En6
  wire signed [7:0] delay98_im;  // sfix8_En6
  wire signed [7:0] combined18_re;  // sfix8_En6
  wire signed [7:0] combined18_im;  // sfix8_En6
  wire signed [32:0] gain18_mul_temp;  // sfix33_En30
  wire signed [32:0] gain18_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain18_re;  // sfix34_En30
  wire signed [33:0] gain18_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_36;  // sfix64_En30
  wire signed [63:0] add_add_cast_37;  // sfix64_En30
  wire signed [63:0] add_re_17;  // sfix64_En30
  wire signed [63:0] add_im_17;  // sfix64_En30
  wire signed [7:0] delay19_re;  // sfix8_En6
  wire signed [7:0] delay19_im;  // sfix8_En6
  wire signed [7:0] delay97_re;  // sfix8_En6
  wire signed [7:0] delay97_im;  // sfix8_En6
  wire signed [7:0] combined19_re;  // sfix8_En6
  wire signed [7:0] combined19_im;  // sfix8_En6
  wire signed [32:0] gain19_mul_temp;  // sfix33_En30
  wire signed [32:0] gain19_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain19_re;  // sfix34_En30
  wire signed [33:0] gain19_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_38;  // sfix64_En30
  wire signed [63:0] add_add_cast_39;  // sfix64_En30
  wire signed [63:0] add_re_18;  // sfix64_En30
  wire signed [63:0] add_im_18;  // sfix64_En30
  wire signed [7:0] delay20_re;  // sfix8_En6
  wire signed [7:0] delay20_im;  // sfix8_En6
  wire signed [7:0] delay96_re;  // sfix8_En6
  wire signed [7:0] delay96_im;  // sfix8_En6
  wire signed [7:0] combined20_re;  // sfix8_En6
  wire signed [7:0] combined20_im;  // sfix8_En6
  wire signed [32:0] gain20_mul_temp;  // sfix33_En30
  wire signed [32:0] gain20_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain20_re;  // sfix34_En30
  wire signed [33:0] gain20_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_40;  // sfix64_En30
  wire signed [63:0] add_add_cast_41;  // sfix64_En30
  wire signed [63:0] add_re_19;  // sfix64_En30
  wire signed [63:0] add_im_19;  // sfix64_En30
  wire signed [7:0] delay21_re;  // sfix8_En6
  wire signed [7:0] delay21_im;  // sfix8_En6
  wire signed [7:0] delay95_re;  // sfix8_En6
  wire signed [7:0] delay95_im;  // sfix8_En6
  wire signed [7:0] combined21_re;  // sfix8_En6
  wire signed [7:0] combined21_im;  // sfix8_En6
  wire signed [32:0] gain21_mul_temp;  // sfix33_En30
  wire signed [32:0] gain21_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain21_re;  // sfix34_En30
  wire signed [33:0] gain21_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_42;  // sfix64_En30
  wire signed [63:0] add_add_cast_43;  // sfix64_En30
  wire signed [63:0] add_re_20;  // sfix64_En30
  wire signed [63:0] add_im_20;  // sfix64_En30
  wire signed [7:0] delay22_re;  // sfix8_En6
  wire signed [7:0] delay22_im;  // sfix8_En6
  wire signed [7:0] delay94_re;  // sfix8_En6
  wire signed [7:0] delay94_im;  // sfix8_En6
  wire signed [7:0] combined22_re;  // sfix8_En6
  wire signed [7:0] combined22_im;  // sfix8_En6
  wire signed [32:0] gain22_mul_temp;  // sfix33_En30
  wire signed [32:0] gain22_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain22_re;  // sfix34_En30
  wire signed [33:0] gain22_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_44;  // sfix64_En30
  wire signed [63:0] add_add_cast_45;  // sfix64_En30
  wire signed [63:0] add_re_21;  // sfix64_En30
  wire signed [63:0] add_im_21;  // sfix64_En30
  wire signed [7:0] delay23_re;  // sfix8_En6
  wire signed [7:0] delay23_im;  // sfix8_En6
  wire signed [7:0] delay93_re;  // sfix8_En6
  wire signed [7:0] delay93_im;  // sfix8_En6
  wire signed [7:0] combined23_re;  // sfix8_En6
  wire signed [7:0] combined23_im;  // sfix8_En6
  wire signed [32:0] gain23_mul_temp;  // sfix33_En30
  wire signed [32:0] gain23_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain23_re;  // sfix34_En30
  wire signed [33:0] gain23_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_46;  // sfix64_En30
  wire signed [63:0] add_add_cast_47;  // sfix64_En30
  wire signed [63:0] add_re_22;  // sfix64_En30
  wire signed [63:0] add_im_22;  // sfix64_En30
  wire signed [7:0] delay24_re;  // sfix8_En6
  wire signed [7:0] delay24_im;  // sfix8_En6
  wire signed [7:0] delay92_re;  // sfix8_En6
  wire signed [7:0] delay92_im;  // sfix8_En6
  wire signed [7:0] combined24_re;  // sfix8_En6
  wire signed [7:0] combined24_im;  // sfix8_En6
  wire signed [32:0] gain24_mul_temp;  // sfix33_En30
  wire signed [32:0] gain24_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain24_re;  // sfix34_En30
  wire signed [33:0] gain24_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_48;  // sfix64_En30
  wire signed [63:0] add_add_cast_49;  // sfix64_En30
  wire signed [63:0] add_re_23;  // sfix64_En30
  wire signed [63:0] add_im_23;  // sfix64_En30
  wire signed [7:0] delay25_re;  // sfix8_En6
  wire signed [7:0] delay25_im;  // sfix8_En6
  wire signed [7:0] delay91_re;  // sfix8_En6
  wire signed [7:0] delay91_im;  // sfix8_En6
  wire signed [7:0] combined25_re;  // sfix8_En6
  wire signed [7:0] combined25_im;  // sfix8_En6
  wire signed [32:0] gain25_mul_temp;  // sfix33_En30
  wire signed [32:0] gain25_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain25_re;  // sfix34_En30
  wire signed [33:0] gain25_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_50;  // sfix64_En30
  wire signed [63:0] add_add_cast_51;  // sfix64_En30
  wire signed [63:0] add_re_24;  // sfix64_En30
  wire signed [63:0] add_im_24;  // sfix64_En30
  wire signed [7:0] delay26_re;  // sfix8_En6
  wire signed [7:0] delay26_im;  // sfix8_En6
  wire signed [7:0] delay90_re;  // sfix8_En6
  wire signed [7:0] delay90_im;  // sfix8_En6
  wire signed [7:0] combined26_re;  // sfix8_En6
  wire signed [7:0] combined26_im;  // sfix8_En6
  wire signed [32:0] gain26_mul_temp;  // sfix33_En30
  wire signed [32:0] gain26_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain26_re;  // sfix34_En30
  wire signed [33:0] gain26_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_52;  // sfix64_En30
  wire signed [63:0] add_add_cast_53;  // sfix64_En30
  wire signed [63:0] add_re_25;  // sfix64_En30
  wire signed [63:0] add_im_25;  // sfix64_En30
  wire signed [7:0] delay27_re;  // sfix8_En6
  wire signed [7:0] delay27_im;  // sfix8_En6
  wire signed [7:0] delay89_re;  // sfix8_En6
  wire signed [7:0] delay89_im;  // sfix8_En6
  wire signed [7:0] combined27_re;  // sfix8_En6
  wire signed [7:0] combined27_im;  // sfix8_En6
  wire signed [32:0] gain27_mul_temp;  // sfix33_En30
  wire signed [32:0] gain27_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain27_re;  // sfix34_En30
  wire signed [33:0] gain27_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_54;  // sfix64_En30
  wire signed [63:0] add_add_cast_55;  // sfix64_En30
  wire signed [63:0] add_re_26;  // sfix64_En30
  wire signed [63:0] add_im_26;  // sfix64_En30
  wire signed [7:0] delay28_re;  // sfix8_En6
  wire signed [7:0] delay28_im;  // sfix8_En6
  wire signed [7:0] delay88_re;  // sfix8_En6
  wire signed [7:0] delay88_im;  // sfix8_En6
  wire signed [7:0] combined28_re;  // sfix8_En6
  wire signed [7:0] combined28_im;  // sfix8_En6
  wire signed [32:0] gain28_mul_temp;  // sfix33_En30
  wire signed [32:0] gain28_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain28_re;  // sfix34_En30
  wire signed [33:0] gain28_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_56;  // sfix64_En30
  wire signed [63:0] add_add_cast_57;  // sfix64_En30
  wire signed [63:0] add_re_27;  // sfix64_En30
  wire signed [63:0] add_im_27;  // sfix64_En30
  wire signed [7:0] delay29_re;  // sfix8_En6
  wire signed [7:0] delay29_im;  // sfix8_En6
  wire signed [7:0] delay87_re;  // sfix8_En6
  wire signed [7:0] delay87_im;  // sfix8_En6
  wire signed [7:0] combined29_re;  // sfix8_En6
  wire signed [7:0] combined29_im;  // sfix8_En6
  wire signed [32:0] gain29_mul_temp;  // sfix33_En30
  wire signed [32:0] gain29_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain29_re;  // sfix34_En30
  wire signed [33:0] gain29_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_58;  // sfix64_En30
  wire signed [63:0] add_add_cast_59;  // sfix64_En30
  wire signed [63:0] add_re_28;  // sfix64_En30
  wire signed [63:0] add_im_28;  // sfix64_En30
  wire signed [7:0] delay30_re;  // sfix8_En6
  wire signed [7:0] delay30_im;  // sfix8_En6
  wire signed [7:0] delay86_re;  // sfix8_En6
  wire signed [7:0] delay86_im;  // sfix8_En6
  wire signed [7:0] combined30_re;  // sfix8_En6
  wire signed [7:0] combined30_im;  // sfix8_En6
  wire signed [32:0] gain30_mul_temp;  // sfix33_En30
  wire signed [32:0] gain30_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain30_re;  // sfix34_En30
  wire signed [33:0] gain30_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_60;  // sfix64_En30
  wire signed [63:0] add_add_cast_61;  // sfix64_En30
  wire signed [63:0] add_re_29;  // sfix64_En30
  wire signed [63:0] add_im_29;  // sfix64_En30
  wire signed [7:0] delay31_re;  // sfix8_En6
  wire signed [7:0] delay31_im;  // sfix8_En6
  wire signed [7:0] delay85_re;  // sfix8_En6
  wire signed [7:0] delay85_im;  // sfix8_En6
  wire signed [7:0] combined31_re;  // sfix8_En6
  wire signed [7:0] combined31_im;  // sfix8_En6
  wire signed [32:0] gain31_mul_temp;  // sfix33_En30
  wire signed [32:0] gain31_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain31_re;  // sfix34_En30
  wire signed [33:0] gain31_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_62;  // sfix64_En30
  wire signed [63:0] add_add_cast_63;  // sfix64_En30
  wire signed [63:0] add_re_30;  // sfix64_En30
  wire signed [63:0] add_im_30;  // sfix64_En30
  wire signed [7:0] delay32_re;  // sfix8_En6
  wire signed [7:0] delay32_im;  // sfix8_En6
  wire signed [7:0] delay84_re;  // sfix8_En6
  wire signed [7:0] delay84_im;  // sfix8_En6
  wire signed [7:0] combined32_re;  // sfix8_En6
  wire signed [7:0] combined32_im;  // sfix8_En6
  wire signed [32:0] gain32_mul_temp;  // sfix33_En30
  wire signed [32:0] gain32_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain32_re;  // sfix34_En30
  wire signed [33:0] gain32_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_64;  // sfix64_En30
  wire signed [63:0] add_add_cast_65;  // sfix64_En30
  wire signed [63:0] add_re_31;  // sfix64_En30
  wire signed [63:0] add_im_31;  // sfix64_En30
  wire signed [7:0] delay33_re;  // sfix8_En6
  wire signed [7:0] delay33_im;  // sfix8_En6
  wire signed [7:0] delay83_re;  // sfix8_En6
  wire signed [7:0] delay83_im;  // sfix8_En6
  wire signed [7:0] combined33_re;  // sfix8_En6
  wire signed [7:0] combined33_im;  // sfix8_En6
  wire signed [32:0] gain33_mul_temp;  // sfix33_En30
  wire signed [32:0] gain33_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain33_re;  // sfix34_En30
  wire signed [33:0] gain33_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_66;  // sfix64_En30
  wire signed [63:0] add_add_cast_67;  // sfix64_En30
  wire signed [63:0] add_re_32;  // sfix64_En30
  wire signed [63:0] add_im_32;  // sfix64_En30
  wire signed [7:0] delay34_re;  // sfix8_En6
  wire signed [7:0] delay34_im;  // sfix8_En6
  wire signed [7:0] delay82_re;  // sfix8_En6
  wire signed [7:0] delay82_im;  // sfix8_En6
  wire signed [7:0] combined34_re;  // sfix8_En6
  wire signed [7:0] combined34_im;  // sfix8_En6
  wire signed [32:0] gain34_mul_temp;  // sfix33_En30
  wire signed [32:0] gain34_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain34_re;  // sfix34_En30
  wire signed [33:0] gain34_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_68;  // sfix64_En30
  wire signed [63:0] add_add_cast_69;  // sfix64_En30
  wire signed [63:0] add_re_33;  // sfix64_En30
  wire signed [63:0] add_im_33;  // sfix64_En30
  wire signed [7:0] delay35_re;  // sfix8_En6
  wire signed [7:0] delay35_im;  // sfix8_En6
  wire signed [7:0] delay81_re;  // sfix8_En6
  wire signed [7:0] delay81_im;  // sfix8_En6
  wire signed [7:0] combined35_re;  // sfix8_En6
  wire signed [7:0] combined35_im;  // sfix8_En6
  wire signed [32:0] gain35_mul_temp;  // sfix33_En30
  wire signed [32:0] gain35_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain35_re;  // sfix34_En30
  wire signed [33:0] gain35_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_70;  // sfix64_En30
  wire signed [63:0] add_add_cast_71;  // sfix64_En30
  wire signed [63:0] add_re_34;  // sfix64_En30
  wire signed [63:0] add_im_34;  // sfix64_En30
  wire signed [7:0] delay36_re;  // sfix8_En6
  wire signed [7:0] delay36_im;  // sfix8_En6
  wire signed [7:0] delay80_re;  // sfix8_En6
  wire signed [7:0] delay80_im;  // sfix8_En6
  wire signed [7:0] combined36_re;  // sfix8_En6
  wire signed [7:0] combined36_im;  // sfix8_En6
  wire signed [32:0] gain36_mul_temp;  // sfix33_En30
  wire signed [32:0] gain36_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain36_re;  // sfix34_En30
  wire signed [33:0] gain36_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_72;  // sfix64_En30
  wire signed [63:0] add_add_cast_73;  // sfix64_En30
  wire signed [63:0] add_re_35;  // sfix64_En30
  wire signed [63:0] add_im_35;  // sfix64_En30
  wire signed [7:0] delay37_re;  // sfix8_En6
  wire signed [7:0] delay37_im;  // sfix8_En6
  wire signed [7:0] delay79_re;  // sfix8_En6
  wire signed [7:0] delay79_im;  // sfix8_En6
  wire signed [7:0] combined37_re;  // sfix8_En6
  wire signed [7:0] combined37_im;  // sfix8_En6
  wire signed [32:0] gain37_mul_temp;  // sfix33_En30
  wire signed [32:0] gain37_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain37_re;  // sfix34_En30
  wire signed [33:0] gain37_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_74;  // sfix64_En30
  wire signed [63:0] add_add_cast_75;  // sfix64_En30
  wire signed [63:0] add_re_36;  // sfix64_En30
  wire signed [63:0] add_im_36;  // sfix64_En30
  wire signed [7:0] delay38_re;  // sfix8_En6
  wire signed [7:0] delay38_im;  // sfix8_En6
  wire signed [7:0] delay78_re;  // sfix8_En6
  wire signed [7:0] delay78_im;  // sfix8_En6
  wire signed [7:0] combined38_re;  // sfix8_En6
  wire signed [7:0] combined38_im;  // sfix8_En6
  wire signed [32:0] gain38_mul_temp;  // sfix33_En30
  wire signed [32:0] gain38_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain38_re;  // sfix34_En30
  wire signed [33:0] gain38_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_76;  // sfix64_En30
  wire signed [63:0] add_add_cast_77;  // sfix64_En30
  wire signed [63:0] add_re_37;  // sfix64_En30
  wire signed [63:0] add_im_37;  // sfix64_En30
  wire signed [7:0] delay39_re;  // sfix8_En6
  wire signed [7:0] delay39_im;  // sfix8_En6
  wire signed [7:0] delay77_re;  // sfix8_En6
  wire signed [7:0] delay77_im;  // sfix8_En6
  wire signed [7:0] combined39_re;  // sfix8_En6
  wire signed [7:0] combined39_im;  // sfix8_En6
  wire signed [32:0] gain39_mul_temp;  // sfix33_En30
  wire signed [32:0] gain39_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain39_re;  // sfix34_En30
  wire signed [33:0] gain39_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_78;  // sfix64_En30
  wire signed [63:0] add_add_cast_79;  // sfix64_En30
  wire signed [63:0] add_re_38;  // sfix64_En30
  wire signed [63:0] add_im_38;  // sfix64_En30
  wire signed [7:0] delay40_re;  // sfix8_En6
  wire signed [7:0] delay40_im;  // sfix8_En6
  wire signed [7:0] delay76_re;  // sfix8_En6
  wire signed [7:0] delay76_im;  // sfix8_En6
  wire signed [7:0] combined40_re;  // sfix8_En6
  wire signed [7:0] combined40_im;  // sfix8_En6
  wire signed [32:0] gain40_mul_temp;  // sfix33_En30
  wire signed [32:0] gain40_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain40_re;  // sfix34_En30
  wire signed [33:0] gain40_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_80;  // sfix64_En30
  wire signed [63:0] add_add_cast_81;  // sfix64_En30
  wire signed [63:0] add_re_39;  // sfix64_En30
  wire signed [63:0] add_im_39;  // sfix64_En30
  wire signed [7:0] delay41_re;  // sfix8_En6
  wire signed [7:0] delay41_im;  // sfix8_En6
  wire signed [7:0] delay75_re;  // sfix8_En6
  wire signed [7:0] delay75_im;  // sfix8_En6
  wire signed [7:0] combined41_re;  // sfix8_En6
  wire signed [7:0] combined41_im;  // sfix8_En6
  wire signed [32:0] gain41_mul_temp;  // sfix33_En30
  wire signed [32:0] gain41_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain41_re;  // sfix34_En30
  wire signed [33:0] gain41_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_82;  // sfix64_En30
  wire signed [63:0] add_add_cast_83;  // sfix64_En30
  wire signed [63:0] add_re_40;  // sfix64_En30
  wire signed [63:0] add_im_40;  // sfix64_En30
  wire signed [7:0] delay42_re;  // sfix8_En6
  wire signed [7:0] delay42_im;  // sfix8_En6
  wire signed [7:0] delay74_re;  // sfix8_En6
  wire signed [7:0] delay74_im;  // sfix8_En6
  wire signed [7:0] combined42_re;  // sfix8_En6
  wire signed [7:0] combined42_im;  // sfix8_En6
  wire signed [32:0] gain42_mul_temp;  // sfix33_En30
  wire signed [32:0] gain42_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain42_re;  // sfix34_En30
  wire signed [33:0] gain42_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_84;  // sfix64_En30
  wire signed [63:0] add_add_cast_85;  // sfix64_En30
  wire signed [63:0] add_re_41;  // sfix64_En30
  wire signed [63:0] add_im_41;  // sfix64_En30
  wire signed [7:0] delay43_re;  // sfix8_En6
  wire signed [7:0] delay43_im;  // sfix8_En6
  wire signed [7:0] delay73_re;  // sfix8_En6
  wire signed [7:0] delay73_im;  // sfix8_En6
  wire signed [7:0] combined43_re;  // sfix8_En6
  wire signed [7:0] combined43_im;  // sfix8_En6
  wire signed [32:0] gain43_mul_temp;  // sfix33_En30
  wire signed [32:0] gain43_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain43_re;  // sfix34_En30
  wire signed [33:0] gain43_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_86;  // sfix64_En30
  wire signed [63:0] add_add_cast_87;  // sfix64_En30
  wire signed [63:0] add_re_42;  // sfix64_En30
  wire signed [63:0] add_im_42;  // sfix64_En30
  wire signed [7:0] delay44_re;  // sfix8_En6
  wire signed [7:0] delay44_im;  // sfix8_En6
  wire signed [7:0] delay72_re;  // sfix8_En6
  wire signed [7:0] delay72_im;  // sfix8_En6
  wire signed [7:0] combined44_re;  // sfix8_En6
  wire signed [7:0] combined44_im;  // sfix8_En6
  wire signed [32:0] gain44_mul_temp;  // sfix33_En30
  wire signed [32:0] gain44_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain44_re;  // sfix34_En30
  wire signed [33:0] gain44_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_88;  // sfix64_En30
  wire signed [63:0] add_add_cast_89;  // sfix64_En30
  wire signed [63:0] add_re_43;  // sfix64_En30
  wire signed [63:0] add_im_43;  // sfix64_En30
  wire signed [7:0] delay45_re;  // sfix8_En6
  wire signed [7:0] delay45_im;  // sfix8_En6
  wire signed [7:0] delay71_re;  // sfix8_En6
  wire signed [7:0] delay71_im;  // sfix8_En6
  wire signed [7:0] combined45_re;  // sfix8_En6
  wire signed [7:0] combined45_im;  // sfix8_En6
  wire signed [32:0] gain45_mul_temp;  // sfix33_En30
  wire signed [32:0] gain45_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain45_re;  // sfix34_En30
  wire signed [33:0] gain45_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_90;  // sfix64_En30
  wire signed [63:0] add_add_cast_91;  // sfix64_En30
  wire signed [63:0] add_re_44;  // sfix64_En30
  wire signed [63:0] add_im_44;  // sfix64_En30
  wire signed [7:0] delay46_re;  // sfix8_En6
  wire signed [7:0] delay46_im;  // sfix8_En6
  wire signed [7:0] delay70_re;  // sfix8_En6
  wire signed [7:0] delay70_im;  // sfix8_En6
  wire signed [7:0] combined46_re;  // sfix8_En6
  wire signed [7:0] combined46_im;  // sfix8_En6
  wire signed [32:0] gain46_mul_temp;  // sfix33_En30
  wire signed [32:0] gain46_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain46_re;  // sfix34_En30
  wire signed [33:0] gain46_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_92;  // sfix64_En30
  wire signed [63:0] add_add_cast_93;  // sfix64_En30
  wire signed [63:0] add_re_45;  // sfix64_En30
  wire signed [63:0] add_im_45;  // sfix64_En30
  wire signed [7:0] delay47_re;  // sfix8_En6
  wire signed [7:0] delay47_im;  // sfix8_En6
  wire signed [7:0] delay69_re;  // sfix8_En6
  wire signed [7:0] delay69_im;  // sfix8_En6
  wire signed [7:0] combined47_re;  // sfix8_En6
  wire signed [7:0] combined47_im;  // sfix8_En6
  wire signed [32:0] gain47_mul_temp;  // sfix33_En30
  wire signed [32:0] gain47_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain47_re;  // sfix34_En30
  wire signed [33:0] gain47_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_94;  // sfix64_En30
  wire signed [63:0] add_add_cast_95;  // sfix64_En30
  wire signed [63:0] add_re_46;  // sfix64_En30
  wire signed [63:0] add_im_46;  // sfix64_En30
  wire signed [7:0] delay48_re;  // sfix8_En6
  wire signed [7:0] delay48_im;  // sfix8_En6
  wire signed [7:0] delay68_re;  // sfix8_En6
  wire signed [7:0] delay68_im;  // sfix8_En6
  wire signed [7:0] combined48_re;  // sfix8_En6
  wire signed [7:0] combined48_im;  // sfix8_En6
  wire signed [32:0] gain48_mul_temp;  // sfix33_En30
  wire signed [32:0] gain48_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain48_re;  // sfix34_En30
  wire signed [33:0] gain48_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_96;  // sfix64_En30
  wire signed [63:0] add_add_cast_97;  // sfix64_En30
  wire signed [63:0] add_re_47;  // sfix64_En30
  wire signed [63:0] add_im_47;  // sfix64_En30
  wire signed [7:0] delay49_re;  // sfix8_En6
  wire signed [7:0] delay49_im;  // sfix8_En6
  wire signed [7:0] delay67_re;  // sfix8_En6
  wire signed [7:0] delay67_im;  // sfix8_En6
  wire signed [7:0] combined49_re;  // sfix8_En6
  wire signed [7:0] combined49_im;  // sfix8_En6
  wire signed [32:0] gain49_mul_temp;  // sfix33_En30
  wire signed [32:0] gain49_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain49_re;  // sfix34_En30
  wire signed [33:0] gain49_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_98;  // sfix64_En30
  wire signed [63:0] add_add_cast_99;  // sfix64_En30
  wire signed [63:0] add_re_48;  // sfix64_En30
  wire signed [63:0] add_im_48;  // sfix64_En30
  wire signed [7:0] delay50_re;  // sfix8_En6
  wire signed [7:0] delay50_im;  // sfix8_En6
  wire signed [7:0] delay66_re;  // sfix8_En6
  wire signed [7:0] delay66_im;  // sfix8_En6
  wire signed [7:0] combined50_re;  // sfix8_En6
  wire signed [7:0] combined50_im;  // sfix8_En6
  wire signed [32:0] gain50_mul_temp;  // sfix33_En30
  wire signed [32:0] gain50_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain50_re;  // sfix34_En30
  wire signed [33:0] gain50_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_100;  // sfix64_En30
  wire signed [63:0] add_add_cast_101;  // sfix64_En30
  wire signed [63:0] add_re_49;  // sfix64_En30
  wire signed [63:0] add_im_49;  // sfix64_En30
  wire signed [7:0] delay51_re;  // sfix8_En6
  wire signed [7:0] delay51_im;  // sfix8_En6
  wire signed [7:0] delay65_re;  // sfix8_En6
  wire signed [7:0] delay65_im;  // sfix8_En6
  wire signed [7:0] combined51_re;  // sfix8_En6
  wire signed [7:0] combined51_im;  // sfix8_En6
  wire signed [32:0] gain51_mul_temp;  // sfix33_En30
  wire signed [32:0] gain51_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain51_re;  // sfix34_En30
  wire signed [33:0] gain51_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_102;  // sfix64_En30
  wire signed [63:0] add_add_cast_103;  // sfix64_En30
  wire signed [63:0] add_re_50;  // sfix64_En30
  wire signed [63:0] add_im_50;  // sfix64_En30
  wire signed [7:0] delay52_re;  // sfix8_En6
  wire signed [7:0] delay52_im;  // sfix8_En6
  wire signed [7:0] delay64_re;  // sfix8_En6
  wire signed [7:0] delay64_im;  // sfix8_En6
  wire signed [7:0] combined52_re;  // sfix8_En6
  wire signed [7:0] combined52_im;  // sfix8_En6
  wire signed [32:0] gain52_mul_temp;  // sfix33_En30
  wire signed [32:0] gain52_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain52_re;  // sfix34_En30
  wire signed [33:0] gain52_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_104;  // sfix64_En30
  wire signed [63:0] add_add_cast_105;  // sfix64_En30
  wire signed [63:0] add_re_51;  // sfix64_En30
  wire signed [63:0] add_im_51;  // sfix64_En30
  wire signed [7:0] delay53_re;  // sfix8_En6
  wire signed [7:0] delay53_im;  // sfix8_En6
  wire signed [7:0] delay63_re;  // sfix8_En6
  wire signed [7:0] delay63_im;  // sfix8_En6
  wire signed [7:0] combined53_re;  // sfix8_En6
  wire signed [7:0] combined53_im;  // sfix8_En6
  wire signed [32:0] gain53_mul_temp;  // sfix33_En30
  wire signed [32:0] gain53_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain53_re;  // sfix34_En30
  wire signed [33:0] gain53_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_106;  // sfix64_En30
  wire signed [63:0] add_add_cast_107;  // sfix64_En30
  wire signed [63:0] add_re_52;  // sfix64_En30
  wire signed [63:0] add_im_52;  // sfix64_En30
  wire signed [7:0] delay54_re;  // sfix8_En6
  wire signed [7:0] delay54_im;  // sfix8_En6
  wire signed [7:0] delay62_re;  // sfix8_En6
  wire signed [7:0] delay62_im;  // sfix8_En6
  wire signed [7:0] combined54_re;  // sfix8_En6
  wire signed [7:0] combined54_im;  // sfix8_En6
  wire signed [32:0] gain54_mul_temp;  // sfix33_En30
  wire signed [32:0] gain54_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain54_re;  // sfix34_En30
  wire signed [33:0] gain54_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_108;  // sfix64_En30
  wire signed [63:0] add_add_cast_109;  // sfix64_En30
  wire signed [63:0] add_re_53;  // sfix64_En30
  wire signed [63:0] add_im_53;  // sfix64_En30
  wire signed [7:0] delay55_re;  // sfix8_En6
  wire signed [7:0] delay55_im;  // sfix8_En6
  wire signed [7:0] delay61_re;  // sfix8_En6
  wire signed [7:0] delay61_im;  // sfix8_En6
  wire signed [7:0] combined55_re;  // sfix8_En6
  wire signed [7:0] combined55_im;  // sfix8_En6
  wire signed [32:0] gain55_mul_temp;  // sfix33_En30
  wire signed [32:0] gain55_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain55_re;  // sfix34_En30
  wire signed [33:0] gain55_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_110;  // sfix64_En30
  wire signed [63:0] add_add_cast_111;  // sfix64_En30
  wire signed [63:0] add_re_54;  // sfix64_En30
  wire signed [63:0] add_im_54;  // sfix64_En30
  wire signed [7:0] delay56_re;  // sfix8_En6
  wire signed [7:0] delay56_im;  // sfix8_En6
  wire signed [7:0] delay60_re;  // sfix8_En6
  wire signed [7:0] delay60_im;  // sfix8_En6
  wire signed [7:0] combined56_re;  // sfix8_En6
  wire signed [7:0] combined56_im;  // sfix8_En6
  wire signed [32:0] gain56_mul_temp;  // sfix33_En30
  wire signed [32:0] gain56_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain56_re;  // sfix34_En30
  wire signed [33:0] gain56_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_112;  // sfix64_En30
  wire signed [63:0] add_add_cast_113;  // sfix64_En30
  wire signed [63:0] add_re_55;  // sfix64_En30
  wire signed [63:0] add_im_55;  // sfix64_En30
  wire signed [7:0] delay57_re;  // sfix8_En6
  wire signed [7:0] delay57_im;  // sfix8_En6
  wire signed [7:0] delay59_re;  // sfix8_En6
  wire signed [7:0] delay59_im;  // sfix8_En6
  wire signed [7:0] combined57_re;  // sfix8_En6
  wire signed [7:0] combined57_im;  // sfix8_En6
  wire signed [32:0] gain57_mul_temp;  // sfix33_En30
  wire signed [32:0] gain57_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain57_re;  // sfix34_En30
  wire signed [33:0] gain57_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_114;  // sfix64_En30
  wire signed [63:0] add_add_cast_115;  // sfix64_En30
  wire signed [63:0] add_re_56;  // sfix64_En30
  wire signed [63:0] add_im_56;  // sfix64_En30
  wire signed [7:0] delay58_re;  // sfix8_En6
  wire signed [7:0] delay58_im;  // sfix8_En6
  wire signed [32:0] gain58_mul_temp;  // sfix33_En30
  wire signed [32:0] gain58_mul_temp_1;  // sfix33_En30
  wire signed [33:0] gain58_re;  // sfix34_En30
  wire signed [33:0] gain58_im;  // sfix34_En30
  wire signed [63:0] add_add_cast_116;  // sfix64_En30
  wire signed [63:0] add_add_cast_117;  // sfix64_En30
  reg signed [31:0] tapped_delay_t_0_0;  // int32
  reg signed [31:0] tapped_delay_t_1;  // int32
  reg signed [31:0] tapped_delay_t_0_1;  // int32
  reg signed [31:0] tapped_delay_t_1_0;  // int32


  always @(posedge clk or posedge reset)
    begin : tapped_delay_process
      if (reset == 1'b1) begin
        for(tapped_delay_t_1_0 = 32'sd0; tapped_delay_t_1_0 <= 32'sd115; tapped_delay_t_1_0 = tapped_delay_t_1_0 + 32'sd1) begin
          tapped_delay_reg_re[tapped_delay_t_1_0] <= 8'sb00000000;
          tapped_delay_reg_im[tapped_delay_t_1_0] <= 8'sb00000000;
        end
      end
      else begin
        if (enb) begin
          for(tapped_delay_t_0_1 = 32'sd0; tapped_delay_t_0_1 <= 32'sd115; tapped_delay_t_0_1 = tapped_delay_t_0_1 + 32'sd1) begin
            tapped_delay_reg_re[tapped_delay_t_0_1] <= tapped_delay_reg_next_re[tapped_delay_t_0_1];
            tapped_delay_reg_im[tapped_delay_t_0_1] <= tapped_delay_reg_next_im[tapped_delay_t_0_1];
          end
        end
      end
    end

  always @* begin

    for(tapped_delay_t_0_0 = 32'sd0; tapped_delay_t_0_0 <= 32'sd115; tapped_delay_t_0_0 = tapped_delay_t_0_0 + 32'sd1) begin
      delay_pipeline_re[tapped_delay_t_0_0] = tapped_delay_reg_re[tapped_delay_t_0_0];
      delay_pipeline_im[tapped_delay_t_0_0] = tapped_delay_reg_im[tapped_delay_t_0_0];
    end

    tapped_delay_reg_next_re[0] = Discrete_FIR_Filter_in_re;
    tapped_delay_reg_next_im[0] = Discrete_FIR_Filter_in_im;

    for(tapped_delay_t_1 = 32'sd0; tapped_delay_t_1 <= 32'sd114; tapped_delay_t_1 = tapped_delay_t_1 + 32'sd1) begin
      tapped_delay_reg_next_re[tapped_delay_t_1 + 32'sd1] = tapped_delay_reg_re[tapped_delay_t_1];
      tapped_delay_reg_next_im[tapped_delay_t_1 + 32'sd1] = tapped_delay_reg_im[tapped_delay_t_1];
    end

  end

  assign delay116_re = delay_pipeline_re[115];

  assign delay116_im = delay_pipeline_im[115];

  assign combined0_re = Discrete_FIR_Filter_in_re + delay116_re;
  assign combined0_im = Discrete_FIR_Filter_in_im + delay116_im;

  assign gain0_mul_temp = 25'sb1111111111111110100111001 * combined0_re;
  assign gain0_re = {gain0_mul_temp[32], gain0_mul_temp};
  assign gain0_mul_temp_1 = 25'sb1111111111111110100111001 * combined0_im;
  assign gain0_im = {gain0_mul_temp_1[32], gain0_mul_temp_1};

  assign delay1_re = delay_pipeline_re[0];

  assign delay1_im = delay_pipeline_im[0];

  assign delay115_re = delay_pipeline_re[114];

  assign delay115_im = delay_pipeline_im[114];

  assign combined1_re = delay1_re + delay115_re;
  assign combined1_im = delay1_im + delay115_im;

  assign gain1_mul_temp = 25'sb0000000000000001111101011 * combined1_re;
  assign gain1_re = {gain1_mul_temp[32], gain1_mul_temp};
  assign gain1_mul_temp_1 = 25'sb0000000000000001111101011 * combined1_im;
  assign gain1_im = {gain1_mul_temp_1[32], gain1_mul_temp_1};

  assign add_add_cast = {{30{gain0_re[33]}}, gain0_re};
  assign add_add_cast_1 = {{30{gain1_re[33]}}, gain1_re};
  assign add_re = add_add_cast + add_add_cast_1;
  assign add_add_cast_2 = {{30{gain0_im[33]}}, gain0_im};
  assign add_add_cast_3 = {{30{gain1_im[33]}}, gain1_im};
  assign add_im = add_add_cast_2 + add_add_cast_3;

  assign delay2_re = delay_pipeline_re[1];

  assign delay2_im = delay_pipeline_im[1];

  assign delay114_re = delay_pipeline_re[113];

  assign delay114_im = delay_pipeline_im[113];

  assign combined2_re = delay2_re + delay114_re;
  assign combined2_im = delay2_im + delay114_im;

  assign gain2_mul_temp = 25'sb0000000000000110101110001 * combined2_re;
  assign gain2_re = {gain2_mul_temp[32], gain2_mul_temp};
  assign gain2_mul_temp_1 = 25'sb0000000000000110101110001 * combined2_im;
  assign gain2_im = {gain2_mul_temp_1[32], gain2_mul_temp_1};

  assign add_add_cast_4 = {{30{gain2_re[33]}}, gain2_re};
  assign add_re_1 = add_re + add_add_cast_4;
  assign add_add_cast_5 = {{30{gain2_im[33]}}, gain2_im};
  assign add_im_1 = add_im + add_add_cast_5;

  assign delay3_re = delay_pipeline_re[2];

  assign delay3_im = delay_pipeline_im[2];

  assign delay113_re = delay_pipeline_re[112];

  assign delay113_im = delay_pipeline_im[112];

  assign combined3_re = delay3_re + delay113_re;
  assign combined3_im = delay3_im + delay113_im;

  assign gain3_mul_temp = 25'sb0000000000001110010010111 * combined3_re;
  assign gain3_re = {gain3_mul_temp[32], gain3_mul_temp};
  assign gain3_mul_temp_1 = 25'sb0000000000001110010010111 * combined3_im;
  assign gain3_im = {gain3_mul_temp_1[32], gain3_mul_temp_1};

  assign add_add_cast_6 = {{30{gain3_re[33]}}, gain3_re};
  assign add_re_2 = add_re_1 + add_add_cast_6;
  assign add_add_cast_7 = {{30{gain3_im[33]}}, gain3_im};
  assign add_im_2 = add_im_1 + add_add_cast_7;

  assign delay4_re = delay_pipeline_re[3];

  assign delay4_im = delay_pipeline_im[3];

  assign delay112_re = delay_pipeline_re[111];

  assign delay112_im = delay_pipeline_im[111];

  assign combined4_re = delay4_re + delay112_re;
  assign combined4_im = delay4_im + delay112_im;

  assign gain4_mul_temp = 25'sb0000000000010111000101100 * combined4_re;
  assign gain4_re = {gain4_mul_temp[32], gain4_mul_temp};
  assign gain4_mul_temp_1 = 25'sb0000000000010111000101100 * combined4_im;
  assign gain4_im = {gain4_mul_temp_1[32], gain4_mul_temp_1};

  assign add_add_cast_8 = {{30{gain4_re[33]}}, gain4_re};
  assign add_re_3 = add_re_2 + add_add_cast_8;
  assign add_add_cast_9 = {{30{gain4_im[33]}}, gain4_im};
  assign add_im_3 = add_im_2 + add_add_cast_9;

  assign delay5_re = delay_pipeline_re[4];

  assign delay5_im = delay_pipeline_im[4];

  assign delay111_re = delay_pipeline_re[110];

  assign delay111_im = delay_pipeline_im[110];

  assign combined5_re = delay5_re + delay111_re;
  assign combined5_im = delay5_im + delay111_im;

  assign gain5_mul_temp = 25'sb0000000000011110000111101 * combined5_re;
  assign gain5_re = {gain5_mul_temp[32], gain5_mul_temp};
  assign gain5_mul_temp_1 = 25'sb0000000000011110000111101 * combined5_im;
  assign gain5_im = {gain5_mul_temp_1[32], gain5_mul_temp_1};

  assign add_add_cast_10 = {{30{gain5_re[33]}}, gain5_re};
  assign add_re_4 = add_re_3 + add_add_cast_10;
  assign add_add_cast_11 = {{30{gain5_im[33]}}, gain5_im};
  assign add_im_4 = add_im_3 + add_add_cast_11;

  assign delay6_re = delay_pipeline_re[5];

  assign delay6_im = delay_pipeline_im[5];

  assign delay110_re = delay_pipeline_re[109];

  assign delay110_im = delay_pipeline_im[109];

  assign combined6_re = delay6_re + delay110_re;
  assign combined6_im = delay6_im + delay110_im;

  assign gain6_mul_temp = 25'sb0000000000011111110001100 * combined6_re;
  assign gain6_re = {gain6_mul_temp[32], gain6_mul_temp};
  assign gain6_mul_temp_1 = 25'sb0000000000011111110001100 * combined6_im;
  assign gain6_im = {gain6_mul_temp_1[32], gain6_mul_temp_1};

  assign add_add_cast_12 = {{30{gain6_re[33]}}, gain6_re};
  assign add_re_5 = add_re_4 + add_add_cast_12;
  assign add_add_cast_13 = {{30{gain6_im[33]}}, gain6_im};
  assign add_im_5 = add_im_4 + add_add_cast_13;

  assign delay7_re = delay_pipeline_re[6];

  assign delay7_im = delay_pipeline_im[6];

  assign delay109_re = delay_pipeline_re[108];

  assign delay109_im = delay_pipeline_im[108];

  assign combined7_re = delay7_re + delay109_re;
  assign combined7_im = delay7_im + delay109_im;

  assign gain7_mul_temp = 25'sb0000000000011001001110101 * combined7_re;
  assign gain7_re = {gain7_mul_temp[32], gain7_mul_temp};
  assign gain7_mul_temp_1 = 25'sb0000000000011001001110101 * combined7_im;
  assign gain7_im = {gain7_mul_temp_1[32], gain7_mul_temp_1};

  assign add_add_cast_14 = {{30{gain7_re[33]}}, gain7_re};
  assign add_re_6 = add_re_5 + add_add_cast_14;
  assign add_add_cast_15 = {{30{gain7_im[33]}}, gain7_im};
  assign add_im_6 = add_im_5 + add_add_cast_15;

  assign delay8_re = delay_pipeline_re[7];

  assign delay8_im = delay_pipeline_im[7];

  assign delay108_re = delay_pipeline_re[107];

  assign delay108_im = delay_pipeline_im[107];

  assign combined8_re = delay8_re + delay108_re;
  assign combined8_im = delay8_im + delay108_im;

  assign gain8_mul_temp = 25'sb0000000000001010000110000 * combined8_re;
  assign gain8_re = {gain8_mul_temp[32], gain8_mul_temp};
  assign gain8_mul_temp_1 = 25'sb0000000000001010000110000 * combined8_im;
  assign gain8_im = {gain8_mul_temp_1[32], gain8_mul_temp_1};

  assign add_add_cast_16 = {{30{gain8_re[33]}}, gain8_re};
  assign add_re_7 = add_re_6 + add_add_cast_16;
  assign add_add_cast_17 = {{30{gain8_im[33]}}, gain8_im};
  assign add_im_7 = add_im_6 + add_add_cast_17;

  assign delay9_re = delay_pipeline_re[8];

  assign delay9_im = delay_pipeline_im[8];

  assign delay107_re = delay_pipeline_re[106];

  assign delay107_im = delay_pipeline_im[106];

  assign combined9_re = delay9_re + delay107_re;
  assign combined9_im = delay9_im + delay107_im;

  assign gain9_mul_temp = 25'sb1111111111110101011111010 * combined9_re;
  assign gain9_re = {gain9_mul_temp[32], gain9_mul_temp};
  assign gain9_mul_temp_1 = 25'sb1111111111110101011111010 * combined9_im;
  assign gain9_im = {gain9_mul_temp_1[32], gain9_mul_temp_1};

  assign add_add_cast_18 = {{30{gain9_re[33]}}, gain9_re};
  assign add_re_8 = add_re_7 + add_add_cast_18;
  assign add_add_cast_19 = {{30{gain9_im[33]}}, gain9_im};
  assign add_im_8 = add_im_7 + add_add_cast_19;

  assign delay10_re = delay_pipeline_re[9];

  assign delay10_im = delay_pipeline_im[9];

  assign delay106_re = delay_pipeline_re[105];

  assign delay106_im = delay_pipeline_im[105];

  assign combined10_re = delay10_re + delay106_re;
  assign combined10_im = delay10_im + delay106_im;

  assign gain10_mul_temp = 25'sb1111111111100001110100011 * combined10_re;
  assign gain10_re = {gain10_mul_temp[32], gain10_mul_temp};
  assign gain10_mul_temp_1 = 25'sb1111111111100001110100011 * combined10_im;
  assign gain10_im = {gain10_mul_temp_1[32], gain10_mul_temp_1};

  assign add_add_cast_20 = {{30{gain10_re[33]}}, gain10_re};
  assign add_re_9 = add_re_8 + add_add_cast_20;
  assign add_add_cast_21 = {{30{gain10_im[33]}}, gain10_im};
  assign add_im_9 = add_im_8 + add_add_cast_21;

  assign delay11_re = delay_pipeline_re[10];

  assign delay11_im = delay_pipeline_im[10];

  assign delay105_re = delay_pipeline_re[104];

  assign delay105_im = delay_pipeline_im[104];

  assign combined11_re = delay11_re + delay105_re;
  assign combined11_im = delay11_im + delay105_im;

  assign gain11_mul_temp = 25'sb1111111111010110111100110 * combined11_re;
  assign gain11_re = {gain11_mul_temp[32], gain11_mul_temp};
  assign gain11_mul_temp_1 = 25'sb1111111111010110111100110 * combined11_im;
  assign gain11_im = {gain11_mul_temp_1[32], gain11_mul_temp_1};

  assign add_add_cast_22 = {{30{gain11_re[33]}}, gain11_re};
  assign add_re_10 = add_re_9 + add_add_cast_22;
  assign add_add_cast_23 = {{30{gain11_im[33]}}, gain11_im};
  assign add_im_10 = add_im_9 + add_add_cast_23;

  assign delay12_re = delay_pipeline_re[11];

  assign delay12_im = delay_pipeline_im[11];

  assign delay104_re = delay_pipeline_re[103];

  assign delay104_im = delay_pipeline_im[103];

  assign combined12_re = delay12_re + delay104_re;
  assign combined12_im = delay12_im + delay104_im;

  assign gain12_mul_temp = 25'sb1111111111011011001001011 * combined12_re;
  assign gain12_re = {gain12_mul_temp[32], gain12_mul_temp};
  assign gain12_mul_temp_1 = 25'sb1111111111011011001001011 * combined12_im;
  assign gain12_im = {gain12_mul_temp_1[32], gain12_mul_temp_1};

  assign add_add_cast_24 = {{30{gain12_re[33]}}, gain12_re};
  assign add_re_11 = add_re_10 + add_add_cast_24;
  assign add_add_cast_25 = {{30{gain12_im[33]}}, gain12_im};
  assign add_im_11 = add_im_10 + add_add_cast_25;

  assign delay13_re = delay_pipeline_re[12];

  assign delay13_im = delay_pipeline_im[12];

  assign delay103_re = delay_pipeline_re[102];

  assign delay103_im = delay_pipeline_im[102];

  assign combined13_re = delay13_re + delay103_re;
  assign combined13_im = delay13_im + delay103_im;

  assign gain13_mul_temp = 25'sb1111111111101111110111111 * combined13_re;
  assign gain13_re = {gain13_mul_temp[32], gain13_mul_temp};
  assign gain13_mul_temp_1 = 25'sb1111111111101111110111111 * combined13_im;
  assign gain13_im = {gain13_mul_temp_1[32], gain13_mul_temp_1};

  assign add_add_cast_26 = {{30{gain13_re[33]}}, gain13_re};
  assign add_re_12 = add_re_11 + add_add_cast_26;
  assign add_add_cast_27 = {{30{gain13_im[33]}}, gain13_im};
  assign add_im_12 = add_im_11 + add_add_cast_27;

  assign delay14_re = delay_pipeline_re[13];

  assign delay14_im = delay_pipeline_im[13];

  assign delay102_re = delay_pipeline_re[101];

  assign delay102_im = delay_pipeline_im[101];

  assign combined14_re = delay14_re + delay102_re;
  assign combined14_im = delay14_im + delay102_im;

  assign gain14_mul_temp = 25'sb0000000000001111111010001 * combined14_re;
  assign gain14_re = {gain14_mul_temp[32], gain14_mul_temp};
  assign gain14_mul_temp_1 = 25'sb0000000000001111111010001 * combined14_im;
  assign gain14_im = {gain14_mul_temp_1[32], gain14_mul_temp_1};

  assign add_add_cast_28 = {{30{gain14_re[33]}}, gain14_re};
  assign add_re_13 = add_re_12 + add_add_cast_28;
  assign add_add_cast_29 = {{30{gain14_im[33]}}, gain14_im};
  assign add_im_13 = add_im_12 + add_add_cast_29;

  assign delay15_re = delay_pipeline_re[14];

  assign delay15_im = delay_pipeline_im[14];

  assign delay101_re = delay_pipeline_re[100];

  assign delay101_im = delay_pipeline_im[100];

  assign combined15_re = delay15_re + delay101_re;
  assign combined15_im = delay15_im + delay101_im;

  assign gain15_mul_temp = 25'sb0000000000101111111111100 * combined15_re;
  assign gain15_re = {gain15_mul_temp[32], gain15_mul_temp};
  assign gain15_mul_temp_1 = 25'sb0000000000101111111111100 * combined15_im;
  assign gain15_im = {gain15_mul_temp_1[32], gain15_mul_temp_1};

  assign add_add_cast_30 = {{30{gain15_re[33]}}, gain15_re};
  assign add_re_14 = add_re_13 + add_add_cast_30;
  assign add_add_cast_31 = {{30{gain15_im[33]}}, gain15_im};
  assign add_im_14 = add_im_13 + add_add_cast_31;

  assign delay16_re = delay_pipeline_re[15];

  assign delay16_im = delay_pipeline_im[15];

  assign delay100_re = delay_pipeline_re[99];

  assign delay100_im = delay_pipeline_im[99];

  assign combined16_re = delay16_re + delay100_re;
  assign combined16_im = delay16_im + delay100_im;

  assign gain16_mul_temp = 25'sb0000000001000010010110101 * combined16_re;
  assign gain16_re = {gain16_mul_temp[32], gain16_mul_temp};
  assign gain16_mul_temp_1 = 25'sb0000000001000010010110101 * combined16_im;
  assign gain16_im = {gain16_mul_temp_1[32], gain16_mul_temp_1};

  assign add_add_cast_32 = {{30{gain16_re[33]}}, gain16_re};
  assign add_re_15 = add_re_14 + add_add_cast_32;
  assign add_add_cast_33 = {{30{gain16_im[33]}}, gain16_im};
  assign add_im_15 = add_im_14 + add_add_cast_33;

  assign delay17_re = delay_pipeline_re[16];

  assign delay17_im = delay_pipeline_im[16];

  assign delay99_re = delay_pipeline_re[98];

  assign delay99_im = delay_pipeline_im[98];

  assign combined17_re = delay17_re + delay99_re;
  assign combined17_im = delay17_im + delay99_im;

  assign gain17_mul_temp = 25'sb0000000000111100001011100 * combined17_re;
  assign gain17_re = {gain17_mul_temp[32], gain17_mul_temp};
  assign gain17_mul_temp_1 = 25'sb0000000000111100001011100 * combined17_im;
  assign gain17_im = {gain17_mul_temp_1[32], gain17_mul_temp_1};

  assign add_add_cast_34 = {{30{gain17_re[33]}}, gain17_re};
  assign add_re_16 = add_re_15 + add_add_cast_34;
  assign add_add_cast_35 = {{30{gain17_im[33]}}, gain17_im};
  assign add_im_16 = add_im_15 + add_add_cast_35;

  assign delay18_re = delay_pipeline_re[17];

  assign delay18_im = delay_pipeline_im[17];

  assign delay98_re = delay_pipeline_re[97];

  assign delay98_im = delay_pipeline_im[97];

  assign combined18_re = delay18_re + delay98_re;
  assign combined18_im = delay18_im + delay98_im;

  assign gain18_mul_temp = 25'sb0000000000011011000010010 * combined18_re;
  assign gain18_re = {gain18_mul_temp[32], gain18_mul_temp};
  assign gain18_mul_temp_1 = 25'sb0000000000011011000010010 * combined18_im;
  assign gain18_im = {gain18_mul_temp_1[32], gain18_mul_temp_1};

  assign add_add_cast_36 = {{30{gain18_re[33]}}, gain18_re};
  assign add_re_17 = add_re_16 + add_add_cast_36;
  assign add_add_cast_37 = {{30{gain18_im[33]}}, gain18_im};
  assign add_im_17 = add_im_16 + add_add_cast_37;

  assign delay19_re = delay_pipeline_re[18];

  assign delay19_im = delay_pipeline_im[18];

  assign delay97_re = delay_pipeline_re[96];

  assign delay97_im = delay_pipeline_im[96];

  assign combined19_re = delay19_re + delay97_re;
  assign combined19_im = delay19_im + delay97_im;

  assign gain19_mul_temp = 25'sb1111111111100111101110001 * combined19_re;
  assign gain19_re = {gain19_mul_temp[32], gain19_mul_temp};
  assign gain19_mul_temp_1 = 25'sb1111111111100111101110001 * combined19_im;
  assign gain19_im = {gain19_mul_temp_1[32], gain19_mul_temp_1};

  assign add_add_cast_38 = {{30{gain19_re[33]}}, gain19_re};
  assign add_re_18 = add_re_17 + add_add_cast_38;
  assign add_add_cast_39 = {{30{gain19_im[33]}}, gain19_im};
  assign add_im_18 = add_im_17 + add_add_cast_39;

  assign delay20_re = delay_pipeline_re[19];

  assign delay20_im = delay_pipeline_im[19];

  assign delay96_re = delay_pipeline_re[95];

  assign delay96_im = delay_pipeline_im[95];

  assign combined20_re = delay20_re + delay96_re;
  assign combined20_im = delay20_im + delay96_im;

  assign gain20_mul_temp = 25'sb1111111110110100101111110 * combined20_re;
  assign gain20_re = {gain20_mul_temp[32], gain20_mul_temp};
  assign gain20_mul_temp_1 = 25'sb1111111110110100101111110 * combined20_im;
  assign gain20_im = {gain20_mul_temp_1[32], gain20_mul_temp_1};

  assign add_add_cast_40 = {{30{gain20_re[33]}}, gain20_re};
  assign add_re_19 = add_re_18 + add_add_cast_40;
  assign add_add_cast_41 = {{30{gain20_im[33]}}, gain20_im};
  assign add_im_19 = add_im_18 + add_add_cast_41;

  assign delay21_re = delay_pipeline_re[20];

  assign delay21_im = delay_pipeline_im[20];

  assign delay95_re = delay_pipeline_re[94];

  assign delay95_im = delay_pipeline_im[94];

  assign combined21_re = delay21_re + delay95_re;
  assign combined21_im = delay21_im + delay95_im;

  assign gain21_mul_temp = 25'sb1111111110011000001010111 * combined21_re;
  assign gain21_re = {gain21_mul_temp[32], gain21_mul_temp};
  assign gain21_mul_temp_1 = 25'sb1111111110011000001010111 * combined21_im;
  assign gain21_im = {gain21_mul_temp_1[32], gain21_mul_temp_1};

  assign add_add_cast_42 = {{30{gain21_re[33]}}, gain21_re};
  assign add_re_20 = add_re_19 + add_add_cast_42;
  assign add_add_cast_43 = {{30{gain21_im[33]}}, gain21_im};
  assign add_im_20 = add_im_19 + add_add_cast_43;

  assign delay22_re = delay_pipeline_re[21];

  assign delay22_im = delay_pipeline_im[21];

  assign delay94_re = delay_pipeline_re[93];

  assign delay94_im = delay_pipeline_im[93];

  assign combined22_re = delay22_re + delay94_re;
  assign combined22_im = delay22_im + delay94_im;

  assign gain22_mul_temp = 25'sb1111111110100010101000100 * combined22_re;
  assign gain22_re = {gain22_mul_temp[32], gain22_mul_temp};
  assign gain22_mul_temp_1 = 25'sb1111111110100010101000100 * combined22_im;
  assign gain22_im = {gain22_mul_temp_1[32], gain22_mul_temp_1};

  assign add_add_cast_44 = {{30{gain22_re[33]}}, gain22_re};
  assign add_re_21 = add_re_20 + add_add_cast_44;
  assign add_add_cast_45 = {{30{gain22_im[33]}}, gain22_im};
  assign add_im_21 = add_im_20 + add_add_cast_45;

  assign delay23_re = delay_pipeline_re[22];

  assign delay23_im = delay_pipeline_im[22];

  assign delay93_re = delay_pipeline_re[92];

  assign delay93_im = delay_pipeline_im[92];

  assign combined23_re = delay23_re + delay93_re;
  assign combined23_im = delay23_im + delay93_im;

  assign gain23_mul_temp = 25'sb1111111111010110111111001 * combined23_re;
  assign gain23_re = {gain23_mul_temp[32], gain23_mul_temp};
  assign gain23_mul_temp_1 = 25'sb1111111111010110111111001 * combined23_im;
  assign gain23_im = {gain23_mul_temp_1[32], gain23_mul_temp_1};

  assign add_add_cast_46 = {{30{gain23_re[33]}}, gain23_re};
  assign add_re_22 = add_re_21 + add_add_cast_46;
  assign add_add_cast_47 = {{30{gain23_im[33]}}, gain23_im};
  assign add_im_22 = add_im_21 + add_add_cast_47;

  assign delay24_re = delay_pipeline_re[23];

  assign delay24_im = delay_pipeline_im[23];

  assign delay92_re = delay_pipeline_re[91];

  assign delay92_im = delay_pipeline_im[91];

  assign combined24_re = delay24_re + delay92_re;
  assign combined24_im = delay24_im + delay92_im;

  assign gain24_mul_temp = 25'sb0000000000100110011011001 * combined24_re;
  assign gain24_re = {gain24_mul_temp[32], gain24_mul_temp};
  assign gain24_mul_temp_1 = 25'sb0000000000100110011011001 * combined24_im;
  assign gain24_im = {gain24_mul_temp_1[32], gain24_mul_temp_1};

  assign add_add_cast_48 = {{30{gain24_re[33]}}, gain24_re};
  assign add_re_23 = add_re_22 + add_add_cast_48;
  assign add_add_cast_49 = {{30{gain24_im[33]}}, gain24_im};
  assign add_im_23 = add_im_22 + add_add_cast_49;

  assign delay25_re = delay_pipeline_re[24];

  assign delay25_im = delay_pipeline_im[24];

  assign delay91_re = delay_pipeline_re[90];

  assign delay91_im = delay_pipeline_im[90];

  assign combined25_re = delay25_re + delay91_re;
  assign combined25_im = delay25_im + delay91_im;

  assign gain25_mul_temp = 25'sb0000000001110011101001000 * combined25_re;
  assign gain25_re = {gain25_mul_temp[32], gain25_mul_temp};
  assign gain25_mul_temp_1 = 25'sb0000000001110011101001000 * combined25_im;
  assign gain25_im = {gain25_mul_temp_1[32], gain25_mul_temp_1};

  assign add_add_cast_50 = {{30{gain25_re[33]}}, gain25_re};
  assign add_re_24 = add_re_23 + add_add_cast_50;
  assign add_add_cast_51 = {{30{gain25_im[33]}}, gain25_im};
  assign add_im_24 = add_im_23 + add_add_cast_51;

  assign delay26_re = delay_pipeline_re[25];

  assign delay26_im = delay_pipeline_im[25];

  assign delay90_re = delay_pipeline_re[89];

  assign delay90_im = delay_pipeline_im[89];

  assign combined26_re = delay26_re + delay90_re;
  assign combined26_im = delay26_im + delay90_im;

  assign gain26_mul_temp = 25'sb0000000010011100111110001 * combined26_re;
  assign gain26_re = {gain26_mul_temp[32], gain26_mul_temp};
  assign gain26_mul_temp_1 = 25'sb0000000010011100111110001 * combined26_im;
  assign gain26_im = {gain26_mul_temp_1[32], gain26_mul_temp_1};

  assign add_add_cast_52 = {{30{gain26_re[33]}}, gain26_re};
  assign add_re_25 = add_re_24 + add_add_cast_52;
  assign add_add_cast_53 = {{30{gain26_im[33]}}, gain26_im};
  assign add_im_25 = add_im_24 + add_add_cast_53;

  assign delay27_re = delay_pipeline_re[26];

  assign delay27_im = delay_pipeline_im[26];

  assign delay89_re = delay_pipeline_re[88];

  assign delay89_im = delay_pipeline_im[88];

  assign combined27_re = delay27_re + delay89_re;
  assign combined27_im = delay27_im + delay89_im;

  assign gain27_mul_temp = 25'sb0000000010001010010001001 * combined27_re;
  assign gain27_re = {gain27_mul_temp[32], gain27_mul_temp};
  assign gain27_mul_temp_1 = 25'sb0000000010001010010001001 * combined27_im;
  assign gain27_im = {gain27_mul_temp_1[32], gain27_mul_temp_1};

  assign add_add_cast_54 = {{30{gain27_re[33]}}, gain27_re};
  assign add_re_26 = add_re_25 + add_add_cast_54;
  assign add_add_cast_55 = {{30{gain27_im[33]}}, gain27_im};
  assign add_im_26 = add_im_25 + add_add_cast_55;

  assign delay28_re = delay_pipeline_re[27];

  assign delay28_im = delay_pipeline_im[27];

  assign delay88_re = delay_pipeline_re[87];

  assign delay88_im = delay_pipeline_im[87];

  assign combined28_re = delay28_re + delay88_re;
  assign combined28_im = delay28_im + delay88_im;

  assign gain28_mul_temp = 25'sb0000000000111001000111111 * combined28_re;
  assign gain28_re = {gain28_mul_temp[32], gain28_mul_temp};
  assign gain28_mul_temp_1 = 25'sb0000000000111001000111111 * combined28_im;
  assign gain28_im = {gain28_mul_temp_1[32], gain28_mul_temp_1};

  assign add_add_cast_56 = {{30{gain28_re[33]}}, gain28_re};
  assign add_re_27 = add_re_26 + add_add_cast_56;
  assign add_add_cast_57 = {{30{gain28_im[33]}}, gain28_im};
  assign add_im_27 = add_im_26 + add_add_cast_57;

  assign delay29_re = delay_pipeline_re[28];

  assign delay29_im = delay_pipeline_im[28];

  assign delay87_re = delay_pipeline_re[86];

  assign delay87_im = delay_pipeline_im[86];

  assign combined29_re = delay29_re + delay87_re;
  assign combined29_im = delay29_im + delay87_im;

  assign gain29_mul_temp = 25'sb1111111111000001101101001 * combined29_re;
  assign gain29_re = {gain29_mul_temp[32], gain29_mul_temp};
  assign gain29_mul_temp_1 = 25'sb1111111111000001101101001 * combined29_im;
  assign gain29_im = {gain29_mul_temp_1[32], gain29_mul_temp_1};

  assign add_add_cast_58 = {{30{gain29_re[33]}}, gain29_re};
  assign add_re_28 = add_re_27 + add_add_cast_58;
  assign add_add_cast_59 = {{30{gain29_im[33]}}, gain29_im};
  assign add_im_28 = add_im_27 + add_add_cast_59;

  assign delay30_re = delay_pipeline_re[29];

  assign delay30_im = delay_pipeline_im[29];

  assign delay86_re = delay_pipeline_re[85];

  assign delay86_im = delay_pipeline_im[85];

  assign combined30_re = delay30_re + delay86_re;
  assign combined30_im = delay30_im + delay86_im;

  assign gain30_mul_temp = 25'sb1111111101010000110111111 * combined30_re;
  assign gain30_re = {gain30_mul_temp[32], gain30_mul_temp};
  assign gain30_mul_temp_1 = 25'sb1111111101010000110111111 * combined30_im;
  assign gain30_im = {gain30_mul_temp_1[32], gain30_mul_temp_1};

  assign add_add_cast_60 = {{30{gain30_re[33]}}, gain30_re};
  assign add_re_29 = add_re_28 + add_add_cast_60;
  assign add_add_cast_61 = {{30{gain30_im[33]}}, gain30_im};
  assign add_im_29 = add_im_28 + add_add_cast_61;

  assign delay31_re = delay_pipeline_re[30];

  assign delay31_im = delay_pipeline_im[30];

  assign delay85_re = delay_pipeline_re[84];

  assign delay85_im = delay_pipeline_im[84];

  assign combined31_re = delay31_re + delay85_re;
  assign combined31_im = delay31_im + delay85_im;

  assign gain31_mul_temp = 25'sb1111111100011000010010001 * combined31_re;
  assign gain31_re = {gain31_mul_temp[32], gain31_mul_temp};
  assign gain31_mul_temp_1 = 25'sb1111111100011000010010001 * combined31_im;
  assign gain31_im = {gain31_mul_temp_1[32], gain31_mul_temp_1};

  assign add_add_cast_62 = {{30{gain31_re[33]}}, gain31_re};
  assign add_re_30 = add_re_29 + add_add_cast_62;
  assign add_add_cast_63 = {{30{gain31_im[33]}}, gain31_im};
  assign add_im_30 = add_im_29 + add_add_cast_63;

  assign delay32_re = delay_pipeline_re[31];

  assign delay32_im = delay_pipeline_im[31];

  assign delay84_re = delay_pipeline_re[83];

  assign delay84_im = delay_pipeline_im[83];

  assign combined32_re = delay32_re + delay84_re;
  assign combined32_im = delay32_im + delay84_im;

  assign gain32_mul_temp = 25'sb1111111100111001101100011 * combined32_re;
  assign gain32_re = {gain32_mul_temp[32], gain32_mul_temp};
  assign gain32_mul_temp_1 = 25'sb1111111100111001101100011 * combined32_im;
  assign gain32_im = {gain32_mul_temp_1[32], gain32_mul_temp_1};

  assign add_add_cast_64 = {{30{gain32_re[33]}}, gain32_re};
  assign add_re_31 = add_re_30 + add_add_cast_64;
  assign add_add_cast_65 = {{30{gain32_im[33]}}, gain32_im};
  assign add_im_31 = add_im_30 + add_add_cast_65;

  assign delay33_re = delay_pipeline_re[32];

  assign delay33_im = delay_pipeline_im[32];

  assign delay83_re = delay_pipeline_re[82];

  assign delay83_im = delay_pipeline_im[82];

  assign combined33_re = delay33_re + delay83_re;
  assign combined33_im = delay33_im + delay83_im;

  assign gain33_mul_temp = 25'sb1111111110110101101111111 * combined33_re;
  assign gain33_re = {gain33_mul_temp[32], gain33_mul_temp};
  assign gain33_mul_temp_1 = 25'sb1111111110110101101111111 * combined33_im;
  assign gain33_im = {gain33_mul_temp_1[32], gain33_mul_temp_1};

  assign add_add_cast_66 = {{30{gain33_re[33]}}, gain33_re};
  assign add_re_32 = add_re_31 + add_add_cast_66;
  assign add_add_cast_67 = {{30{gain33_im[33]}}, gain33_im};
  assign add_im_32 = add_im_31 + add_add_cast_67;

  assign delay34_re = delay_pipeline_re[33];

  assign delay34_im = delay_pipeline_im[33];

  assign delay82_re = delay_pipeline_re[81];

  assign delay82_im = delay_pipeline_im[81];

  assign combined34_re = delay34_re + delay82_re;
  assign combined34_im = delay34_im + delay82_im;

  assign gain34_mul_temp = 25'sb0000000001100110001010101 * combined34_re;
  assign gain34_re = {gain34_mul_temp[32], gain34_mul_temp};
  assign gain34_mul_temp_1 = 25'sb0000000001100110001010101 * combined34_im;
  assign gain34_im = {gain34_mul_temp_1[32], gain34_mul_temp_1};

  assign add_add_cast_68 = {{30{gain34_re[33]}}, gain34_re};
  assign add_re_33 = add_re_32 + add_add_cast_68;
  assign add_add_cast_69 = {{30{gain34_im[33]}}, gain34_im};
  assign add_im_33 = add_im_32 + add_add_cast_69;

  assign delay35_re = delay_pipeline_re[34];

  assign delay35_im = delay_pipeline_im[34];

  assign delay81_re = delay_pipeline_re[80];

  assign delay81_im = delay_pipeline_im[80];

  assign combined35_re = delay35_re + delay81_re;
  assign combined35_im = delay35_im + delay81_im;

  assign gain35_mul_temp = 25'sb0000000100000111110011000 * combined35_re;
  assign gain35_re = {gain35_mul_temp[32], gain35_mul_temp};
  assign gain35_mul_temp_1 = 25'sb0000000100000111110011000 * combined35_im;
  assign gain35_im = {gain35_mul_temp_1[32], gain35_mul_temp_1};

  assign add_add_cast_70 = {{30{gain35_re[33]}}, gain35_re};
  assign add_re_34 = add_re_33 + add_add_cast_70;
  assign add_add_cast_71 = {{30{gain35_im[33]}}, gain35_im};
  assign add_im_34 = add_im_33 + add_add_cast_71;

  assign delay36_re = delay_pipeline_re[35];

  assign delay36_im = delay_pipeline_im[35];

  assign delay80_re = delay_pipeline_re[79];

  assign delay80_im = delay_pipeline_im[79];

  assign combined36_re = delay36_re + delay80_re;
  assign combined36_im = delay36_im + delay80_im;

  assign gain36_mul_temp = 25'sb0000000101010010101101000 * combined36_re;
  assign gain36_re = {gain36_mul_temp[32], gain36_mul_temp};
  assign gain36_mul_temp_1 = 25'sb0000000101010010101101000 * combined36_im;
  assign gain36_im = {gain36_mul_temp_1[32], gain36_mul_temp_1};

  assign add_add_cast_72 = {{30{gain36_re[33]}}, gain36_re};
  assign add_re_35 = add_re_34 + add_add_cast_72;
  assign add_add_cast_73 = {{30{gain36_im[33]}}, gain36_im};
  assign add_im_35 = add_im_34 + add_add_cast_73;

  assign delay37_re = delay_pipeline_re[36];

  assign delay37_im = delay_pipeline_im[36];

  assign delay79_re = delay_pipeline_re[78];

  assign delay79_im = delay_pipeline_im[78];

  assign combined37_re = delay37_re + delay79_re;
  assign combined37_im = delay37_im + delay79_im;

  assign gain37_mul_temp = 25'sb0000000100011000001110010 * combined37_re;
  assign gain37_re = {gain37_mul_temp[32], gain37_mul_temp};
  assign gain37_mul_temp_1 = 25'sb0000000100011000001110010 * combined37_im;
  assign gain37_im = {gain37_mul_temp_1[32], gain37_mul_temp_1};

  assign add_add_cast_74 = {{30{gain37_re[33]}}, gain37_re};
  assign add_re_36 = add_re_35 + add_add_cast_74;
  assign add_add_cast_75 = {{30{gain37_im[33]}}, gain37_im};
  assign add_im_36 = add_im_35 + add_add_cast_75;

  assign delay38_re = delay_pipeline_re[37];

  assign delay38_im = delay_pipeline_im[37];

  assign delay78_re = delay_pipeline_re[77];

  assign delay78_im = delay_pipeline_im[77];

  assign combined38_re = delay38_re + delay78_re;
  assign combined38_im = delay38_im + delay78_im;

  assign gain38_mul_temp = 25'sb0000000001011011001000001 * combined38_re;
  assign gain38_re = {gain38_mul_temp[32], gain38_mul_temp};
  assign gain38_mul_temp_1 = 25'sb0000000001011011001000001 * combined38_im;
  assign gain38_im = {gain38_mul_temp_1[32], gain38_mul_temp_1};

  assign add_add_cast_76 = {{30{gain38_re[33]}}, gain38_re};
  assign add_re_37 = add_re_36 + add_add_cast_76;
  assign add_add_cast_77 = {{30{gain38_im[33]}}, gain38_im};
  assign add_im_37 = add_im_36 + add_add_cast_77;

  assign delay39_re = delay_pipeline_re[38];

  assign delay39_im = delay_pipeline_im[38];

  assign delay77_re = delay_pipeline_re[76];

  assign delay77_im = delay_pipeline_im[76];

  assign combined39_re = delay39_re + delay77_re;
  assign combined39_im = delay39_im + delay77_im;

  assign gain39_mul_temp = 25'sb1111111101010110100110111 * combined39_re;
  assign gain39_re = {gain39_mul_temp[32], gain39_mul_temp};
  assign gain39_mul_temp_1 = 25'sb1111111101010110100110111 * combined39_im;
  assign gain39_im = {gain39_mul_temp_1[32], gain39_mul_temp_1};

  assign add_add_cast_78 = {{30{gain39_re[33]}}, gain39_re};
  assign add_re_38 = add_re_37 + add_add_cast_78;
  assign add_add_cast_79 = {{30{gain39_im[33]}}, gain39_im};
  assign add_im_38 = add_im_37 + add_add_cast_79;

  assign delay40_re = delay_pipeline_re[39];

  assign delay40_im = delay_pipeline_im[39];

  assign delay76_re = delay_pipeline_re[75];

  assign delay76_im = delay_pipeline_im[75];

  assign combined40_re = delay40_re + delay76_re;
  assign combined40_im = delay40_im + delay76_im;

  assign gain40_mul_temp = 25'sb1111111001101110011110101 * combined40_re;
  assign gain40_re = {gain40_mul_temp[32], gain40_mul_temp};
  assign gain40_mul_temp_1 = 25'sb1111111001101110011110101 * combined40_im;
  assign gain40_im = {gain40_mul_temp_1[32], gain40_mul_temp_1};

  assign add_add_cast_80 = {{30{gain40_re[33]}}, gain40_re};
  assign add_re_39 = add_re_38 + add_add_cast_80;
  assign add_add_cast_81 = {{30{gain40_im[33]}}, gain40_im};
  assign add_im_39 = add_im_38 + add_add_cast_81;

  assign delay41_re = delay_pipeline_re[40];

  assign delay41_im = delay_pipeline_im[40];

  assign delay75_re = delay_pipeline_re[74];

  assign delay75_im = delay_pipeline_im[74];

  assign combined41_re = delay41_re + delay75_re;
  assign combined41_im = delay41_im + delay75_im;

  assign gain41_mul_temp = 25'sb1111111000001011100110000 * combined41_re;
  assign gain41_re = {gain41_mul_temp[32], gain41_mul_temp};
  assign gain41_mul_temp_1 = 25'sb1111111000001011100110000 * combined41_im;
  assign gain41_im = {gain41_mul_temp_1[32], gain41_mul_temp_1};

  assign add_add_cast_82 = {{30{gain41_re[33]}}, gain41_re};
  assign add_re_40 = add_re_39 + add_add_cast_82;
  assign add_add_cast_83 = {{30{gain41_im[33]}}, gain41_im};
  assign add_im_40 = add_im_39 + add_add_cast_83;

  assign delay42_re = delay_pipeline_re[41];

  assign delay42_im = delay_pipeline_im[41];

  assign delay74_re = delay_pipeline_re[73];

  assign delay74_im = delay_pipeline_im[73];

  assign combined42_re = delay42_re + delay74_re;
  assign combined42_im = delay42_im + delay74_im;

  assign gain42_mul_temp = 25'sb1111111001110000010010010 * combined42_re;
  assign gain42_re = {gain42_mul_temp[32], gain42_mul_temp};
  assign gain42_mul_temp_1 = 25'sb1111111001110000010010010 * combined42_im;
  assign gain42_im = {gain42_mul_temp_1[32], gain42_mul_temp_1};

  assign add_add_cast_84 = {{30{gain42_re[33]}}, gain42_re};
  assign add_re_41 = add_re_40 + add_add_cast_84;
  assign add_add_cast_85 = {{30{gain42_im[33]}}, gain42_im};
  assign add_im_41 = add_im_40 + add_add_cast_85;

  assign delay43_re = delay_pipeline_re[42];

  assign delay43_im = delay_pipeline_im[42];

  assign delay73_re = delay_pipeline_re[72];

  assign delay73_im = delay_pipeline_im[72];

  assign combined43_re = delay43_re + delay73_re;
  assign combined43_im = delay43_im + delay73_im;

  assign gain43_mul_temp = 25'sb1111111110010101101100101 * combined43_re;
  assign gain43_re = {gain43_mul_temp[32], gain43_mul_temp};
  assign gain43_mul_temp_1 = 25'sb1111111110010101101100101 * combined43_im;
  assign gain43_im = {gain43_mul_temp_1[32], gain43_mul_temp_1};

  assign add_add_cast_86 = {{30{gain43_re[33]}}, gain43_re};
  assign add_re_42 = add_re_41 + add_add_cast_86;
  assign add_add_cast_87 = {{30{gain43_im[33]}}, gain43_im};
  assign add_im_42 = add_im_41 + add_add_cast_87;

  assign delay44_re = delay_pipeline_re[43];

  assign delay44_im = delay_pipeline_im[43];

  assign delay72_re = delay_pipeline_re[71];

  assign delay72_im = delay_pipeline_im[71];

  assign combined44_re = delay44_re + delay72_re;
  assign combined44_im = delay44_im + delay72_im;

  assign gain44_mul_temp = 25'sb0000000100100001101110000 * combined44_re;
  assign gain44_re = {gain44_mul_temp[32], gain44_mul_temp};
  assign gain44_mul_temp_1 = 25'sb0000000100100001101110000 * combined44_im;
  assign gain44_im = {gain44_mul_temp_1[32], gain44_mul_temp_1};

  assign add_add_cast_88 = {{30{gain44_re[33]}}, gain44_re};
  assign add_re_43 = add_re_42 + add_add_cast_88;
  assign add_add_cast_89 = {{30{gain44_im[33]}}, gain44_im};
  assign add_im_43 = add_im_42 + add_add_cast_89;

  assign delay45_re = delay_pipeline_re[44];

  assign delay45_im = delay_pipeline_im[44];

  assign delay71_re = delay_pipeline_re[70];

  assign delay71_im = delay_pipeline_im[70];

  assign combined45_re = delay45_re + delay71_re;
  assign combined45_im = delay45_im + delay71_im;

  assign gain45_mul_temp = 25'sb0000001001111101100100101 * combined45_re;
  assign gain45_re = {gain45_mul_temp[32], gain45_mul_temp};
  assign gain45_mul_temp_1 = 25'sb0000001001111101100100101 * combined45_im;
  assign gain45_im = {gain45_mul_temp_1[32], gain45_mul_temp_1};

  assign add_add_cast_90 = {{30{gain45_re[33]}}, gain45_re};
  assign add_re_44 = add_re_43 + add_add_cast_90;
  assign add_add_cast_91 = {{30{gain45_im[33]}}, gain45_im};
  assign add_im_44 = add_im_43 + add_add_cast_91;

  assign delay46_re = delay_pipeline_re[45];

  assign delay46_im = delay_pipeline_im[45];

  assign delay70_re = delay_pipeline_re[69];

  assign delay70_im = delay_pipeline_im[69];

  assign combined46_re = delay46_re + delay70_re;
  assign combined46_im = delay46_im + delay70_im;

  assign gain46_mul_temp = 25'sb0000001100001001000111100 * combined46_re;
  assign gain46_re = {gain46_mul_temp[32], gain46_mul_temp};
  assign gain46_mul_temp_1 = 25'sb0000001100001001000111100 * combined46_im;
  assign gain46_im = {gain46_mul_temp_1[32], gain46_mul_temp_1};

  assign add_add_cast_92 = {{30{gain46_re[33]}}, gain46_re};
  assign add_re_45 = add_re_44 + add_add_cast_92;
  assign add_add_cast_93 = {{30{gain46_im[33]}}, gain46_im};
  assign add_im_45 = add_im_44 + add_add_cast_93;

  assign delay47_re = delay_pipeline_re[46];

  assign delay47_im = delay_pipeline_im[46];

  assign delay69_re = delay_pipeline_re[68];

  assign delay69_im = delay_pipeline_im[68];

  assign combined47_re = delay47_re + delay69_re;
  assign combined47_im = delay47_im + delay69_im;

  assign gain47_mul_temp = 25'sb0000001001011010111110000 * combined47_re;
  assign gain47_re = {gain47_mul_temp[32], gain47_mul_temp};
  assign gain47_mul_temp_1 = 25'sb0000001001011010111110000 * combined47_im;
  assign gain47_im = {gain47_mul_temp_1[32], gain47_mul_temp_1};

  assign add_add_cast_94 = {{30{gain47_re[33]}}, gain47_re};
  assign add_re_46 = add_re_45 + add_add_cast_94;
  assign add_add_cast_95 = {{30{gain47_im[33]}}, gain47_im};
  assign add_im_46 = add_im_45 + add_add_cast_95;

  assign delay48_re = delay_pipeline_re[47];

  assign delay48_im = delay_pipeline_im[47];

  assign delay68_re = delay_pipeline_re[67];

  assign delay68_im = delay_pipeline_im[67];

  assign combined48_re = delay48_re + delay68_re;
  assign combined48_im = delay48_im + delay68_im;

  assign gain48_mul_temp = 25'sb0000000001110110010011111 * combined48_re;
  assign gain48_re = {gain48_mul_temp[32], gain48_mul_temp};
  assign gain48_mul_temp_1 = 25'sb0000000001110110010011111 * combined48_im;
  assign gain48_im = {gain48_mul_temp_1[32], gain48_mul_temp_1};

  assign add_add_cast_96 = {{30{gain48_re[33]}}, gain48_re};
  assign add_re_47 = add_re_46 + add_add_cast_96;
  assign add_add_cast_97 = {{30{gain48_im[33]}}, gain48_im};
  assign add_im_47 = add_im_46 + add_add_cast_97;

  assign delay49_re = delay_pipeline_re[48];

  assign delay49_im = delay_pipeline_im[48];

  assign delay67_re = delay_pipeline_re[66];

  assign delay67_im = delay_pipeline_im[66];

  assign combined49_re = delay49_re + delay67_re;
  assign combined49_im = delay49_im + delay67_im;

  assign gain49_mul_temp = 25'sb1111110111100000001110000 * combined49_re;
  assign gain49_re = {gain49_mul_temp[32], gain49_mul_temp};
  assign gain49_mul_temp_1 = 25'sb1111110111100000001110000 * combined49_im;
  assign gain49_im = {gain49_mul_temp_1[32], gain49_mul_temp_1};

  assign add_add_cast_98 = {{30{gain49_re[33]}}, gain49_re};
  assign add_re_48 = add_re_47 + add_add_cast_98;
  assign add_add_cast_99 = {{30{gain49_im[33]}}, gain49_im};
  assign add_im_48 = add_im_47 + add_add_cast_99;

  assign delay50_re = delay_pipeline_re[49];

  assign delay50_im = delay_pipeline_im[49];

  assign delay66_re = delay_pipeline_re[65];

  assign delay66_im = delay_pipeline_im[65];

  assign combined50_re = delay50_re + delay66_re;
  assign combined50_im = delay50_im + delay66_im;

  assign gain50_mul_temp = 25'sb1111101110000111110010111 * combined50_re;
  assign gain50_re = {gain50_mul_temp[32], gain50_mul_temp};
  assign gain50_mul_temp_1 = 25'sb1111101110000111110010111 * combined50_im;
  assign gain50_im = {gain50_mul_temp_1[32], gain50_mul_temp_1};

  assign add_add_cast_100 = {{30{gain50_re[33]}}, gain50_re};
  assign add_re_49 = add_re_48 + add_add_cast_100;
  assign add_add_cast_101 = {{30{gain50_im[33]}}, gain50_im};
  assign add_im_49 = add_im_48 + add_add_cast_101;

  assign delay51_re = delay_pipeline_re[50];

  assign delay51_im = delay_pipeline_im[50];

  assign delay65_re = delay_pipeline_re[64];

  assign delay65_im = delay_pipeline_im[64];

  assign combined51_re = delay51_re + delay65_re;
  assign combined51_im = delay51_im + delay65_im;

  assign gain51_mul_temp = 25'sb1111101010000011110010011 * combined51_re;
  assign gain51_re = {gain51_mul_temp[32], gain51_mul_temp};
  assign gain51_mul_temp_1 = 25'sb1111101010000011110010011 * combined51_im;
  assign gain51_im = {gain51_mul_temp_1[32], gain51_mul_temp_1};

  assign add_add_cast_102 = {{30{gain51_re[33]}}, gain51_re};
  assign add_re_50 = add_re_49 + add_add_cast_102;
  assign add_add_cast_103 = {{30{gain51_im[33]}}, gain51_im};
  assign add_im_50 = add_im_49 + add_add_cast_103;

  assign delay52_re = delay_pipeline_re[51];

  assign delay52_im = delay_pipeline_im[51];

  assign delay64_re = delay_pipeline_re[63];

  assign delay64_im = delay_pipeline_im[63];

  assign combined52_re = delay52_re + delay64_re;
  assign combined52_im = delay52_im + delay64_im;

  assign gain52_mul_temp = 25'sb1111101110111000010101010 * combined52_re;
  assign gain52_re = {gain52_mul_temp[32], gain52_mul_temp};
  assign gain52_mul_temp_1 = 25'sb1111101110111000010101010 * combined52_im;
  assign gain52_im = {gain52_mul_temp_1[32], gain52_mul_temp_1};

  assign add_add_cast_104 = {{30{gain52_re[33]}}, gain52_re};
  assign add_re_51 = add_re_50 + add_add_cast_104;
  assign add_add_cast_105 = {{30{gain52_im[33]}}, gain52_im};
  assign add_im_51 = add_im_50 + add_add_cast_105;

  assign delay53_re = delay_pipeline_re[52];

  assign delay53_im = delay_pipeline_im[52];

  assign delay63_re = delay_pipeline_re[62];

  assign delay63_im = delay_pipeline_im[62];

  assign combined53_re = delay53_re + delay63_re;
  assign combined53_im = delay53_im + delay63_im;

  assign gain53_mul_temp = 25'sb1111111110000001111011100 * combined53_re;
  assign gain53_re = {gain53_mul_temp[32], gain53_mul_temp};
  assign gain53_mul_temp_1 = 25'sb1111111110000001111011100 * combined53_im;
  assign gain53_im = {gain53_mul_temp_1[32], gain53_mul_temp_1};

  assign add_add_cast_106 = {{30{gain53_re[33]}}, gain53_re};
  assign add_re_52 = add_re_51 + add_add_cast_106;
  assign add_add_cast_107 = {{30{gain53_im[33]}}, gain53_im};
  assign add_im_52 = add_im_51 + add_add_cast_107;

  assign delay54_re = delay_pipeline_re[53];

  assign delay54_im = delay_pipeline_im[53];

  assign delay62_re = delay_pipeline_re[61];

  assign delay62_im = delay_pipeline_im[61];

  assign combined54_re = delay54_re + delay62_re;
  assign combined54_im = delay54_im + delay62_im;

  assign gain54_mul_temp = 25'sb0000010110000011101011110 * combined54_re;
  assign gain54_re = {gain54_mul_temp[32], gain54_mul_temp};
  assign gain54_mul_temp_1 = 25'sb0000010110000011101011110 * combined54_im;
  assign gain54_im = {gain54_mul_temp_1[32], gain54_mul_temp_1};

  assign add_add_cast_108 = {{30{gain54_re[33]}}, gain54_re};
  assign add_re_53 = add_re_52 + add_add_cast_108;
  assign add_add_cast_109 = {{30{gain54_im[33]}}, gain54_im};
  assign add_im_53 = add_im_52 + add_add_cast_109;

  assign delay55_re = delay_pipeline_re[54];

  assign delay55_im = delay_pipeline_im[54];

  assign delay61_re = delay_pipeline_re[60];

  assign delay61_im = delay_pipeline_im[60];

  assign combined55_re = delay55_re + delay61_re;
  assign combined55_im = delay55_im + delay61_im;

  assign gain55_mul_temp = 25'sb0000110010101100111011110 * combined55_re;
  assign gain55_re = {gain55_mul_temp[32], gain55_mul_temp};
  assign gain55_mul_temp_1 = 25'sb0000110010101100111011110 * combined55_im;
  assign gain55_im = {gain55_mul_temp_1[32], gain55_mul_temp_1};

  assign add_add_cast_110 = {{30{gain55_re[33]}}, gain55_re};
  assign add_re_54 = add_re_53 + add_add_cast_110;
  assign add_add_cast_111 = {{30{gain55_im[33]}}, gain55_im};
  assign add_im_54 = add_im_53 + add_add_cast_111;

  assign delay56_re = delay_pipeline_re[55];

  assign delay56_im = delay_pipeline_im[55];

  assign delay60_re = delay_pipeline_re[59];

  assign delay60_im = delay_pipeline_im[59];

  assign combined56_re = delay56_re + delay60_re;
  assign combined56_im = delay56_im + delay60_im;

  assign gain56_mul_temp = 25'sb0001001101111000110000100 * combined56_re;
  assign gain56_re = {gain56_mul_temp[32], gain56_mul_temp};
  assign gain56_mul_temp_1 = 25'sb0001001101111000110000100 * combined56_im;
  assign gain56_im = {gain56_mul_temp_1[32], gain56_mul_temp_1};

  assign add_add_cast_112 = {{30{gain56_re[33]}}, gain56_re};
  assign add_re_55 = add_re_54 + add_add_cast_112;
  assign add_add_cast_113 = {{30{gain56_im[33]}}, gain56_im};
  assign add_im_55 = add_im_54 + add_add_cast_113;

  assign delay57_re = delay_pipeline_re[56];

  assign delay57_im = delay_pipeline_im[56];

  assign delay59_re = delay_pipeline_re[58];

  assign delay59_im = delay_pipeline_im[58];

  assign combined57_re = delay57_re + delay59_re;
  assign combined57_im = delay57_im + delay59_im;

  assign gain57_mul_temp = 25'sb0001100001010110010011010 * combined57_re;
  assign gain57_re = {gain57_mul_temp[32], gain57_mul_temp};
  assign gain57_mul_temp_1 = 25'sb0001100001010110010011010 * combined57_im;
  assign gain57_im = {gain57_mul_temp_1[32], gain57_mul_temp_1};

  assign add_add_cast_114 = {{30{gain57_re[33]}}, gain57_re};
  assign add_re_56 = add_re_55 + add_add_cast_114;
  assign add_add_cast_115 = {{30{gain57_im[33]}}, gain57_im};
  assign add_im_56 = add_im_55 + add_add_cast_115;

  assign delay58_re = delay_pipeline_re[57];

  assign delay58_im = delay_pipeline_im[57];

  assign gain58_mul_temp = 25'sb0001101000011010010101111 * delay58_re;
  assign gain58_re = {gain58_mul_temp[32], gain58_mul_temp};
  assign gain58_mul_temp_1 = 25'sb0001101000011010010101111 * delay58_im;
  assign gain58_im = {gain58_mul_temp_1[32], gain58_mul_temp_1};

  assign add_add_cast_116 = {{30{gain58_re[33]}}, gain58_re};
  assign Discrete_FIR_Filter_out_re = add_re_56 + add_add_cast_116;
  assign add_add_cast_117 = {{30{gain58_im[33]}}, gain58_im};
  assign Discrete_FIR_Filter_out_im = add_im_56 + add_add_cast_117;

endmodule  // Discrete_FIR_Filter

