// -------------------------------------------------------------
// 
// File Name: hdlsrc\dsp_proj_v3_2024_n\Discrete_FIR_Filter1.v
// Created: 2026-04-12 08:40:34
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Discrete_FIR_Filter1
// Source Path: dsp_proj_v3_2024_n/Discrete FIR Filter1
// Hierarchy Level: 1
// Model version: 3.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Discrete_FIR_Filter1
          (clk,
           reset,
           enb,
           Discrete_FIR_Filter1_in_re,
           Discrete_FIR_Filter1_in_im,
           Discrete_FIR_Filter1_out_re,
           Discrete_FIR_Filter1_out_im);


  input   clk;
  input   reset;
  input   enb;
  input   signed [9:0] Discrete_FIR_Filter1_in_re;  // sfix10_En8
  input   signed [9:0] Discrete_FIR_Filter1_in_im;  // sfix10_En8
  output  signed [63:0] Discrete_FIR_Filter1_out_re;  // sfix64_En32
  output  signed [63:0] Discrete_FIR_Filter1_out_im;  // sfix64_En32


  reg signed [9:0] tapped_delay_reg_re [0:69];  // sfix10_En8 [70]
  reg signed [9:0] tapped_delay_reg_im [0:69];  // sfix10_En8 [70]
  reg signed [9:0] tapped_delay_reg_next_re [0:69];  // sfix10_En8 [70]
  reg signed [9:0] tapped_delay_reg_next_im [0:69];  // sfix10_En8 [70]
  reg signed [9:0] delay_pipeline_re [0:69];  // sfix10_En8 [70]
  reg signed [9:0] delay_pipeline_im [0:69];  // sfix10_En8 [70]
  wire signed [9:0] delay70_re;  // sfix10_En8
  wire signed [9:0] delay70_im;  // sfix10_En8
  wire signed [9:0] combined0_re;  // sfix10_En8
  wire signed [9:0] combined0_im;  // sfix10_En8
  wire signed [34:0] gain0_mul_temp;  // sfix35_En32
  wire signed [34:0] gain0_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain0_re;  // sfix36_En32
  wire signed [35:0] gain0_im;  // sfix36_En32
  wire signed [9:0] delay1_re;  // sfix10_En8
  wire signed [9:0] delay1_im;  // sfix10_En8
  wire signed [9:0] delay69_re;  // sfix10_En8
  wire signed [9:0] delay69_im;  // sfix10_En8
  wire signed [9:0] combined1_re;  // sfix10_En8
  wire signed [9:0] combined1_im;  // sfix10_En8
  wire signed [34:0] gain1_mul_temp;  // sfix35_En32
  wire signed [34:0] gain1_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain1_re;  // sfix36_En32
  wire signed [35:0] gain1_im;  // sfix36_En32
  wire signed [63:0] add_add_cast;  // sfix64_En32
  wire signed [63:0] add_add_cast_1;  // sfix64_En32
  wire signed [63:0] add_add_cast_2;  // sfix64_En32
  wire signed [63:0] add_add_cast_3;  // sfix64_En32
  wire signed [63:0] add_re;  // sfix64_En32
  wire signed [63:0] add_im;  // sfix64_En32
  wire signed [9:0] delay2_re;  // sfix10_En8
  wire signed [9:0] delay2_im;  // sfix10_En8
  wire signed [9:0] delay68_re;  // sfix10_En8
  wire signed [9:0] delay68_im;  // sfix10_En8
  wire signed [9:0] combined2_re;  // sfix10_En8
  wire signed [9:0] combined2_im;  // sfix10_En8
  wire signed [34:0] gain2_mul_temp;  // sfix35_En32
  wire signed [34:0] gain2_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain2_re;  // sfix36_En32
  wire signed [35:0] gain2_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_4;  // sfix64_En32
  wire signed [63:0] add_add_cast_5;  // sfix64_En32
  wire signed [63:0] add_re_1;  // sfix64_En32
  wire signed [63:0] add_im_1;  // sfix64_En32
  wire signed [9:0] delay3_re;  // sfix10_En8
  wire signed [9:0] delay3_im;  // sfix10_En8
  wire signed [9:0] delay67_re;  // sfix10_En8
  wire signed [9:0] delay67_im;  // sfix10_En8
  wire signed [9:0] combined3_re;  // sfix10_En8
  wire signed [9:0] combined3_im;  // sfix10_En8
  wire signed [34:0] gain3_mul_temp;  // sfix35_En32
  wire signed [34:0] gain3_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain3_re;  // sfix36_En32
  wire signed [35:0] gain3_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_6;  // sfix64_En32
  wire signed [63:0] add_add_cast_7;  // sfix64_En32
  wire signed [63:0] add_re_2;  // sfix64_En32
  wire signed [63:0] add_im_2;  // sfix64_En32
  wire signed [9:0] delay4_re;  // sfix10_En8
  wire signed [9:0] delay4_im;  // sfix10_En8
  wire signed [9:0] delay66_re;  // sfix10_En8
  wire signed [9:0] delay66_im;  // sfix10_En8
  wire signed [9:0] combined4_re;  // sfix10_En8
  wire signed [9:0] combined4_im;  // sfix10_En8
  wire signed [34:0] gain4_mul_temp;  // sfix35_En32
  wire signed [34:0] gain4_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain4_re;  // sfix36_En32
  wire signed [35:0] gain4_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_8;  // sfix64_En32
  wire signed [63:0] add_add_cast_9;  // sfix64_En32
  wire signed [63:0] add_re_3;  // sfix64_En32
  wire signed [63:0] add_im_3;  // sfix64_En32
  wire signed [9:0] delay5_re;  // sfix10_En8
  wire signed [9:0] delay5_im;  // sfix10_En8
  wire signed [9:0] delay65_re;  // sfix10_En8
  wire signed [9:0] delay65_im;  // sfix10_En8
  wire signed [9:0] combined5_re;  // sfix10_En8
  wire signed [9:0] combined5_im;  // sfix10_En8
  wire signed [34:0] gain5_mul_temp;  // sfix35_En32
  wire signed [34:0] gain5_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain5_re;  // sfix36_En32
  wire signed [35:0] gain5_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_10;  // sfix64_En32
  wire signed [63:0] add_add_cast_11;  // sfix64_En32
  wire signed [63:0] add_re_4;  // sfix64_En32
  wire signed [63:0] add_im_4;  // sfix64_En32
  wire signed [9:0] delay6_re;  // sfix10_En8
  wire signed [9:0] delay6_im;  // sfix10_En8
  wire signed [9:0] delay64_re;  // sfix10_En8
  wire signed [9:0] delay64_im;  // sfix10_En8
  wire signed [9:0] combined6_re;  // sfix10_En8
  wire signed [9:0] combined6_im;  // sfix10_En8
  wire signed [34:0] gain6_mul_temp;  // sfix35_En32
  wire signed [34:0] gain6_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain6_re;  // sfix36_En32
  wire signed [35:0] gain6_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_12;  // sfix64_En32
  wire signed [63:0] add_add_cast_13;  // sfix64_En32
  wire signed [63:0] add_re_5;  // sfix64_En32
  wire signed [63:0] add_im_5;  // sfix64_En32
  wire signed [9:0] delay7_re;  // sfix10_En8
  wire signed [9:0] delay7_im;  // sfix10_En8
  wire signed [9:0] delay63_re;  // sfix10_En8
  wire signed [9:0] delay63_im;  // sfix10_En8
  wire signed [9:0] combined7_re;  // sfix10_En8
  wire signed [9:0] combined7_im;  // sfix10_En8
  wire signed [34:0] gain7_mul_temp;  // sfix35_En32
  wire signed [34:0] gain7_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain7_re;  // sfix36_En32
  wire signed [35:0] gain7_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_14;  // sfix64_En32
  wire signed [63:0] add_add_cast_15;  // sfix64_En32
  wire signed [63:0] add_re_6;  // sfix64_En32
  wire signed [63:0] add_im_6;  // sfix64_En32
  wire signed [9:0] delay8_re;  // sfix10_En8
  wire signed [9:0] delay8_im;  // sfix10_En8
  wire signed [9:0] delay62_re;  // sfix10_En8
  wire signed [9:0] delay62_im;  // sfix10_En8
  wire signed [9:0] combined8_re;  // sfix10_En8
  wire signed [9:0] combined8_im;  // sfix10_En8
  wire signed [34:0] gain8_mul_temp;  // sfix35_En32
  wire signed [34:0] gain8_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain8_re;  // sfix36_En32
  wire signed [35:0] gain8_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_16;  // sfix64_En32
  wire signed [63:0] add_add_cast_17;  // sfix64_En32
  wire signed [63:0] add_re_7;  // sfix64_En32
  wire signed [63:0] add_im_7;  // sfix64_En32
  wire signed [9:0] delay9_re;  // sfix10_En8
  wire signed [9:0] delay9_im;  // sfix10_En8
  wire signed [9:0] delay61_re;  // sfix10_En8
  wire signed [9:0] delay61_im;  // sfix10_En8
  wire signed [9:0] combined9_re;  // sfix10_En8
  wire signed [9:0] combined9_im;  // sfix10_En8
  wire signed [34:0] gain9_mul_temp;  // sfix35_En32
  wire signed [34:0] gain9_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain9_re;  // sfix36_En32
  wire signed [35:0] gain9_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_18;  // sfix64_En32
  wire signed [63:0] add_add_cast_19;  // sfix64_En32
  wire signed [63:0] add_re_8;  // sfix64_En32
  wire signed [63:0] add_im_8;  // sfix64_En32
  wire signed [9:0] delay10_re;  // sfix10_En8
  wire signed [9:0] delay10_im;  // sfix10_En8
  wire signed [9:0] delay60_re;  // sfix10_En8
  wire signed [9:0] delay60_im;  // sfix10_En8
  wire signed [9:0] combined10_re;  // sfix10_En8
  wire signed [9:0] combined10_im;  // sfix10_En8
  wire signed [34:0] gain10_mul_temp;  // sfix35_En32
  wire signed [34:0] gain10_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain10_re;  // sfix36_En32
  wire signed [35:0] gain10_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_20;  // sfix64_En32
  wire signed [63:0] add_add_cast_21;  // sfix64_En32
  wire signed [63:0] add_re_9;  // sfix64_En32
  wire signed [63:0] add_im_9;  // sfix64_En32
  wire signed [9:0] delay11_re;  // sfix10_En8
  wire signed [9:0] delay11_im;  // sfix10_En8
  wire signed [9:0] delay59_re;  // sfix10_En8
  wire signed [9:0] delay59_im;  // sfix10_En8
  wire signed [9:0] combined11_re;  // sfix10_En8
  wire signed [9:0] combined11_im;  // sfix10_En8
  wire signed [34:0] gain11_mul_temp;  // sfix35_En32
  wire signed [34:0] gain11_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain11_re;  // sfix36_En32
  wire signed [35:0] gain11_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_22;  // sfix64_En32
  wire signed [63:0] add_add_cast_23;  // sfix64_En32
  wire signed [63:0] add_re_10;  // sfix64_En32
  wire signed [63:0] add_im_10;  // sfix64_En32
  wire signed [9:0] delay12_re;  // sfix10_En8
  wire signed [9:0] delay12_im;  // sfix10_En8
  wire signed [9:0] delay58_re;  // sfix10_En8
  wire signed [9:0] delay58_im;  // sfix10_En8
  wire signed [9:0] combined12_re;  // sfix10_En8
  wire signed [9:0] combined12_im;  // sfix10_En8
  wire signed [34:0] gain12_mul_temp;  // sfix35_En32
  wire signed [34:0] gain12_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain12_re;  // sfix36_En32
  wire signed [35:0] gain12_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_24;  // sfix64_En32
  wire signed [63:0] add_add_cast_25;  // sfix64_En32
  wire signed [63:0] add_re_11;  // sfix64_En32
  wire signed [63:0] add_im_11;  // sfix64_En32
  wire signed [9:0] delay13_re;  // sfix10_En8
  wire signed [9:0] delay13_im;  // sfix10_En8
  wire signed [9:0] delay57_re;  // sfix10_En8
  wire signed [9:0] delay57_im;  // sfix10_En8
  wire signed [9:0] combined13_re;  // sfix10_En8
  wire signed [9:0] combined13_im;  // sfix10_En8
  wire signed [34:0] gain13_mul_temp;  // sfix35_En32
  wire signed [34:0] gain13_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain13_re;  // sfix36_En32
  wire signed [35:0] gain13_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_26;  // sfix64_En32
  wire signed [63:0] add_add_cast_27;  // sfix64_En32
  wire signed [63:0] add_re_12;  // sfix64_En32
  wire signed [63:0] add_im_12;  // sfix64_En32
  wire signed [9:0] delay14_re;  // sfix10_En8
  wire signed [9:0] delay14_im;  // sfix10_En8
  wire signed [9:0] delay56_re;  // sfix10_En8
  wire signed [9:0] delay56_im;  // sfix10_En8
  wire signed [9:0] combined14_re;  // sfix10_En8
  wire signed [9:0] combined14_im;  // sfix10_En8
  wire signed [34:0] gain14_mul_temp;  // sfix35_En32
  wire signed [34:0] gain14_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain14_re;  // sfix36_En32
  wire signed [35:0] gain14_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_28;  // sfix64_En32
  wire signed [63:0] add_add_cast_29;  // sfix64_En32
  wire signed [63:0] add_re_13;  // sfix64_En32
  wire signed [63:0] add_im_13;  // sfix64_En32
  wire signed [9:0] delay15_re;  // sfix10_En8
  wire signed [9:0] delay15_im;  // sfix10_En8
  wire signed [9:0] delay55_re;  // sfix10_En8
  wire signed [9:0] delay55_im;  // sfix10_En8
  wire signed [9:0] combined15_re;  // sfix10_En8
  wire signed [9:0] combined15_im;  // sfix10_En8
  wire signed [34:0] gain15_mul_temp;  // sfix35_En32
  wire signed [34:0] gain15_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain15_re;  // sfix36_En32
  wire signed [35:0] gain15_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_30;  // sfix64_En32
  wire signed [63:0] add_add_cast_31;  // sfix64_En32
  wire signed [63:0] add_re_14;  // sfix64_En32
  wire signed [63:0] add_im_14;  // sfix64_En32
  wire signed [9:0] delay16_re;  // sfix10_En8
  wire signed [9:0] delay16_im;  // sfix10_En8
  wire signed [9:0] delay54_re;  // sfix10_En8
  wire signed [9:0] delay54_im;  // sfix10_En8
  wire signed [9:0] combined16_re;  // sfix10_En8
  wire signed [9:0] combined16_im;  // sfix10_En8
  wire signed [34:0] gain16_mul_temp;  // sfix35_En32
  wire signed [34:0] gain16_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain16_re;  // sfix36_En32
  wire signed [35:0] gain16_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_32;  // sfix64_En32
  wire signed [63:0] add_add_cast_33;  // sfix64_En32
  wire signed [63:0] add_re_15;  // sfix64_En32
  wire signed [63:0] add_im_15;  // sfix64_En32
  wire signed [9:0] delay17_re;  // sfix10_En8
  wire signed [9:0] delay17_im;  // sfix10_En8
  wire signed [9:0] delay53_re;  // sfix10_En8
  wire signed [9:0] delay53_im;  // sfix10_En8
  wire signed [9:0] combined17_re;  // sfix10_En8
  wire signed [9:0] combined17_im;  // sfix10_En8
  wire signed [34:0] gain17_mul_temp;  // sfix35_En32
  wire signed [34:0] gain17_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain17_re;  // sfix36_En32
  wire signed [35:0] gain17_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_34;  // sfix64_En32
  wire signed [63:0] add_add_cast_35;  // sfix64_En32
  wire signed [63:0] add_re_16;  // sfix64_En32
  wire signed [63:0] add_im_16;  // sfix64_En32
  wire signed [9:0] delay18_re;  // sfix10_En8
  wire signed [9:0] delay18_im;  // sfix10_En8
  wire signed [9:0] delay52_re;  // sfix10_En8
  wire signed [9:0] delay52_im;  // sfix10_En8
  wire signed [9:0] combined18_re;  // sfix10_En8
  wire signed [9:0] combined18_im;  // sfix10_En8
  wire signed [34:0] gain18_mul_temp;  // sfix35_En32
  wire signed [34:0] gain18_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain18_re;  // sfix36_En32
  wire signed [35:0] gain18_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_36;  // sfix64_En32
  wire signed [63:0] add_add_cast_37;  // sfix64_En32
  wire signed [63:0] add_re_17;  // sfix64_En32
  wire signed [63:0] add_im_17;  // sfix64_En32
  wire signed [9:0] delay19_re;  // sfix10_En8
  wire signed [9:0] delay19_im;  // sfix10_En8
  wire signed [9:0] delay51_re;  // sfix10_En8
  wire signed [9:0] delay51_im;  // sfix10_En8
  wire signed [9:0] combined19_re;  // sfix10_En8
  wire signed [9:0] combined19_im;  // sfix10_En8
  wire signed [34:0] gain19_mul_temp;  // sfix35_En32
  wire signed [34:0] gain19_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain19_re;  // sfix36_En32
  wire signed [35:0] gain19_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_38;  // sfix64_En32
  wire signed [63:0] add_add_cast_39;  // sfix64_En32
  wire signed [63:0] add_re_18;  // sfix64_En32
  wire signed [63:0] add_im_18;  // sfix64_En32
  wire signed [9:0] delay20_re;  // sfix10_En8
  wire signed [9:0] delay20_im;  // sfix10_En8
  wire signed [9:0] delay50_re;  // sfix10_En8
  wire signed [9:0] delay50_im;  // sfix10_En8
  wire signed [9:0] combined20_re;  // sfix10_En8
  wire signed [9:0] combined20_im;  // sfix10_En8
  wire signed [34:0] gain20_mul_temp;  // sfix35_En32
  wire signed [34:0] gain20_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain20_re;  // sfix36_En32
  wire signed [35:0] gain20_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_40;  // sfix64_En32
  wire signed [63:0] add_add_cast_41;  // sfix64_En32
  wire signed [63:0] add_re_19;  // sfix64_En32
  wire signed [63:0] add_im_19;  // sfix64_En32
  wire signed [9:0] delay21_re;  // sfix10_En8
  wire signed [9:0] delay21_im;  // sfix10_En8
  wire signed [9:0] delay49_re;  // sfix10_En8
  wire signed [9:0] delay49_im;  // sfix10_En8
  wire signed [9:0] combined21_re;  // sfix10_En8
  wire signed [9:0] combined21_im;  // sfix10_En8
  wire signed [34:0] gain21_mul_temp;  // sfix35_En32
  wire signed [34:0] gain21_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain21_re;  // sfix36_En32
  wire signed [35:0] gain21_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_42;  // sfix64_En32
  wire signed [63:0] add_add_cast_43;  // sfix64_En32
  wire signed [63:0] add_re_20;  // sfix64_En32
  wire signed [63:0] add_im_20;  // sfix64_En32
  wire signed [9:0] delay22_re;  // sfix10_En8
  wire signed [9:0] delay22_im;  // sfix10_En8
  wire signed [9:0] delay48_re;  // sfix10_En8
  wire signed [9:0] delay48_im;  // sfix10_En8
  wire signed [9:0] combined22_re;  // sfix10_En8
  wire signed [9:0] combined22_im;  // sfix10_En8
  wire signed [34:0] gain22_mul_temp;  // sfix35_En32
  wire signed [34:0] gain22_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain22_re;  // sfix36_En32
  wire signed [35:0] gain22_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_44;  // sfix64_En32
  wire signed [63:0] add_add_cast_45;  // sfix64_En32
  wire signed [63:0] add_re_21;  // sfix64_En32
  wire signed [63:0] add_im_21;  // sfix64_En32
  wire signed [9:0] delay23_re;  // sfix10_En8
  wire signed [9:0] delay23_im;  // sfix10_En8
  wire signed [9:0] delay47_re;  // sfix10_En8
  wire signed [9:0] delay47_im;  // sfix10_En8
  wire signed [9:0] combined23_re;  // sfix10_En8
  wire signed [9:0] combined23_im;  // sfix10_En8
  wire signed [34:0] gain23_mul_temp;  // sfix35_En32
  wire signed [34:0] gain23_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain23_re;  // sfix36_En32
  wire signed [35:0] gain23_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_46;  // sfix64_En32
  wire signed [63:0] add_add_cast_47;  // sfix64_En32
  wire signed [63:0] add_re_22;  // sfix64_En32
  wire signed [63:0] add_im_22;  // sfix64_En32
  wire signed [9:0] delay24_re;  // sfix10_En8
  wire signed [9:0] delay24_im;  // sfix10_En8
  wire signed [9:0] delay46_re;  // sfix10_En8
  wire signed [9:0] delay46_im;  // sfix10_En8
  wire signed [9:0] combined24_re;  // sfix10_En8
  wire signed [9:0] combined24_im;  // sfix10_En8
  wire signed [34:0] gain24_mul_temp;  // sfix35_En32
  wire signed [34:0] gain24_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain24_re;  // sfix36_En32
  wire signed [35:0] gain24_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_48;  // sfix64_En32
  wire signed [63:0] add_add_cast_49;  // sfix64_En32
  wire signed [63:0] add_re_23;  // sfix64_En32
  wire signed [63:0] add_im_23;  // sfix64_En32
  wire signed [9:0] delay25_re;  // sfix10_En8
  wire signed [9:0] delay25_im;  // sfix10_En8
  wire signed [9:0] delay45_re;  // sfix10_En8
  wire signed [9:0] delay45_im;  // sfix10_En8
  wire signed [9:0] combined25_re;  // sfix10_En8
  wire signed [9:0] combined25_im;  // sfix10_En8
  wire signed [34:0] gain25_mul_temp;  // sfix35_En32
  wire signed [34:0] gain25_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain25_re;  // sfix36_En32
  wire signed [35:0] gain25_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_50;  // sfix64_En32
  wire signed [63:0] add_add_cast_51;  // sfix64_En32
  wire signed [63:0] add_re_24;  // sfix64_En32
  wire signed [63:0] add_im_24;  // sfix64_En32
  wire signed [9:0] delay26_re;  // sfix10_En8
  wire signed [9:0] delay26_im;  // sfix10_En8
  wire signed [9:0] delay44_re;  // sfix10_En8
  wire signed [9:0] delay44_im;  // sfix10_En8
  wire signed [9:0] combined26_re;  // sfix10_En8
  wire signed [9:0] combined26_im;  // sfix10_En8
  wire signed [34:0] gain26_mul_temp;  // sfix35_En32
  wire signed [34:0] gain26_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain26_re;  // sfix36_En32
  wire signed [35:0] gain26_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_52;  // sfix64_En32
  wire signed [63:0] add_add_cast_53;  // sfix64_En32
  wire signed [63:0] add_re_25;  // sfix64_En32
  wire signed [63:0] add_im_25;  // sfix64_En32
  wire signed [9:0] delay27_re;  // sfix10_En8
  wire signed [9:0] delay27_im;  // sfix10_En8
  wire signed [9:0] delay43_re;  // sfix10_En8
  wire signed [9:0] delay43_im;  // sfix10_En8
  wire signed [9:0] combined27_re;  // sfix10_En8
  wire signed [9:0] combined27_im;  // sfix10_En8
  wire signed [34:0] gain27_mul_temp;  // sfix35_En32
  wire signed [34:0] gain27_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain27_re;  // sfix36_En32
  wire signed [35:0] gain27_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_54;  // sfix64_En32
  wire signed [63:0] add_add_cast_55;  // sfix64_En32
  wire signed [63:0] add_re_26;  // sfix64_En32
  wire signed [63:0] add_im_26;  // sfix64_En32
  wire signed [9:0] delay28_re;  // sfix10_En8
  wire signed [9:0] delay28_im;  // sfix10_En8
  wire signed [9:0] delay42_re;  // sfix10_En8
  wire signed [9:0] delay42_im;  // sfix10_En8
  wire signed [9:0] combined28_re;  // sfix10_En8
  wire signed [9:0] combined28_im;  // sfix10_En8
  wire signed [34:0] gain28_mul_temp;  // sfix35_En32
  wire signed [34:0] gain28_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain28_re;  // sfix36_En32
  wire signed [35:0] gain28_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_56;  // sfix64_En32
  wire signed [63:0] add_add_cast_57;  // sfix64_En32
  wire signed [63:0] add_re_27;  // sfix64_En32
  wire signed [63:0] add_im_27;  // sfix64_En32
  wire signed [9:0] delay29_re;  // sfix10_En8
  wire signed [9:0] delay29_im;  // sfix10_En8
  wire signed [9:0] delay41_re;  // sfix10_En8
  wire signed [9:0] delay41_im;  // sfix10_En8
  wire signed [9:0] combined29_re;  // sfix10_En8
  wire signed [9:0] combined29_im;  // sfix10_En8
  wire signed [34:0] gain29_mul_temp;  // sfix35_En32
  wire signed [34:0] gain29_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain29_re;  // sfix36_En32
  wire signed [35:0] gain29_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_58;  // sfix64_En32
  wire signed [63:0] add_add_cast_59;  // sfix64_En32
  wire signed [63:0] add_re_28;  // sfix64_En32
  wire signed [63:0] add_im_28;  // sfix64_En32
  wire signed [9:0] delay30_re;  // sfix10_En8
  wire signed [9:0] delay30_im;  // sfix10_En8
  wire signed [9:0] delay40_re;  // sfix10_En8
  wire signed [9:0] delay40_im;  // sfix10_En8
  wire signed [9:0] combined30_re;  // sfix10_En8
  wire signed [9:0] combined30_im;  // sfix10_En8
  wire signed [34:0] gain30_mul_temp;  // sfix35_En32
  wire signed [34:0] gain30_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain30_re;  // sfix36_En32
  wire signed [35:0] gain30_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_60;  // sfix64_En32
  wire signed [63:0] add_add_cast_61;  // sfix64_En32
  wire signed [63:0] add_re_29;  // sfix64_En32
  wire signed [63:0] add_im_29;  // sfix64_En32
  wire signed [9:0] delay31_re;  // sfix10_En8
  wire signed [9:0] delay31_im;  // sfix10_En8
  wire signed [9:0] delay39_re;  // sfix10_En8
  wire signed [9:0] delay39_im;  // sfix10_En8
  wire signed [9:0] combined31_re;  // sfix10_En8
  wire signed [9:0] combined31_im;  // sfix10_En8
  wire signed [34:0] gain31_mul_temp;  // sfix35_En32
  wire signed [34:0] gain31_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain31_re;  // sfix36_En32
  wire signed [35:0] gain31_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_62;  // sfix64_En32
  wire signed [63:0] add_add_cast_63;  // sfix64_En32
  wire signed [63:0] add_re_30;  // sfix64_En32
  wire signed [63:0] add_im_30;  // sfix64_En32
  wire signed [9:0] delay32_re;  // sfix10_En8
  wire signed [9:0] delay32_im;  // sfix10_En8
  wire signed [9:0] delay38_re;  // sfix10_En8
  wire signed [9:0] delay38_im;  // sfix10_En8
  wire signed [9:0] combined32_re;  // sfix10_En8
  wire signed [9:0] combined32_im;  // sfix10_En8
  wire signed [34:0] gain32_mul_temp;  // sfix35_En32
  wire signed [34:0] gain32_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain32_re;  // sfix36_En32
  wire signed [35:0] gain32_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_64;  // sfix64_En32
  wire signed [63:0] add_add_cast_65;  // sfix64_En32
  wire signed [63:0] add_re_31;  // sfix64_En32
  wire signed [63:0] add_im_31;  // sfix64_En32
  wire signed [9:0] delay33_re;  // sfix10_En8
  wire signed [9:0] delay33_im;  // sfix10_En8
  wire signed [9:0] delay37_re;  // sfix10_En8
  wire signed [9:0] delay37_im;  // sfix10_En8
  wire signed [9:0] combined33_re;  // sfix10_En8
  wire signed [9:0] combined33_im;  // sfix10_En8
  wire signed [34:0] gain33_mul_temp;  // sfix35_En32
  wire signed [34:0] gain33_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain33_re;  // sfix36_En32
  wire signed [35:0] gain33_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_66;  // sfix64_En32
  wire signed [63:0] add_add_cast_67;  // sfix64_En32
  wire signed [63:0] add_re_32;  // sfix64_En32
  wire signed [63:0] add_im_32;  // sfix64_En32
  wire signed [9:0] delay34_re;  // sfix10_En8
  wire signed [9:0] delay34_im;  // sfix10_En8
  wire signed [9:0] delay36_re;  // sfix10_En8
  wire signed [9:0] delay36_im;  // sfix10_En8
  wire signed [9:0] combined34_re;  // sfix10_En8
  wire signed [9:0] combined34_im;  // sfix10_En8
  wire signed [34:0] gain34_mul_temp;  // sfix35_En32
  wire signed [34:0] gain34_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain34_re;  // sfix36_En32
  wire signed [35:0] gain34_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_68;  // sfix64_En32
  wire signed [63:0] add_add_cast_69;  // sfix64_En32
  wire signed [63:0] add_re_33;  // sfix64_En32
  wire signed [63:0] add_im_33;  // sfix64_En32
  wire signed [9:0] delay35_re;  // sfix10_En8
  wire signed [9:0] delay35_im;  // sfix10_En8
  wire signed [34:0] gain35_mul_temp;  // sfix35_En32
  wire signed [34:0] gain35_mul_temp_1;  // sfix35_En32
  wire signed [35:0] gain35_re;  // sfix36_En32
  wire signed [35:0] gain35_im;  // sfix36_En32
  wire signed [63:0] add_add_cast_70;  // sfix64_En32
  wire signed [63:0] add_add_cast_71;  // sfix64_En32
  reg signed [31:0] tapped_delay_t_0_0;  // int32
  reg signed [31:0] tapped_delay_t_1;  // int32
  reg signed [31:0] tapped_delay_t_0_1;  // int32
  reg signed [31:0] tapped_delay_t_1_0;  // int32


  always @(posedge clk or posedge reset)
    begin : tapped_delay_process
      if (reset == 1'b1) begin
        for(tapped_delay_t_1_0 = 32'sd0; tapped_delay_t_1_0 <= 32'sd69; tapped_delay_t_1_0 = tapped_delay_t_1_0 + 32'sd1) begin
          tapped_delay_reg_re[tapped_delay_t_1_0] <= 10'sb0000000000;
          tapped_delay_reg_im[tapped_delay_t_1_0] <= 10'sb0000000000;
        end
      end
      else begin
        if (enb) begin
          for(tapped_delay_t_0_1 = 32'sd0; tapped_delay_t_0_1 <= 32'sd69; tapped_delay_t_0_1 = tapped_delay_t_0_1 + 32'sd1) begin
            tapped_delay_reg_re[tapped_delay_t_0_1] <= tapped_delay_reg_next_re[tapped_delay_t_0_1];
            tapped_delay_reg_im[tapped_delay_t_0_1] <= tapped_delay_reg_next_im[tapped_delay_t_0_1];
          end
        end
      end
    end

  always @* begin

    for(tapped_delay_t_0_0 = 32'sd0; tapped_delay_t_0_0 <= 32'sd69; tapped_delay_t_0_0 = tapped_delay_t_0_0 + 32'sd1) begin
      delay_pipeline_re[tapped_delay_t_0_0] = tapped_delay_reg_re[tapped_delay_t_0_0];
      delay_pipeline_im[tapped_delay_t_0_0] = tapped_delay_reg_im[tapped_delay_t_0_0];
    end

    tapped_delay_reg_next_re[0] = Discrete_FIR_Filter1_in_re;
    tapped_delay_reg_next_im[0] = Discrete_FIR_Filter1_in_im;

    for(tapped_delay_t_1 = 32'sd0; tapped_delay_t_1 <= 32'sd68; tapped_delay_t_1 = tapped_delay_t_1 + 32'sd1) begin
      tapped_delay_reg_next_re[tapped_delay_t_1 + 32'sd1] = tapped_delay_reg_re[tapped_delay_t_1];
      tapped_delay_reg_next_im[tapped_delay_t_1 + 32'sd1] = tapped_delay_reg_im[tapped_delay_t_1];
    end

  end

  assign delay70_re = delay_pipeline_re[69];

  assign delay70_im = delay_pipeline_im[69];

  assign combined0_re = Discrete_FIR_Filter1_in_re + delay70_re;
  assign combined0_im = Discrete_FIR_Filter1_in_im + delay70_im;

  assign gain0_mul_temp = 25'sb1111111111111001111001101 * combined0_re;
  assign gain0_re = {gain0_mul_temp[34], gain0_mul_temp};
  assign gain0_mul_temp_1 = 25'sb1111111111111001111001101 * combined0_im;
  assign gain0_im = {gain0_mul_temp_1[34], gain0_mul_temp_1};

  assign delay1_re = delay_pipeline_re[0];

  assign delay1_im = delay_pipeline_im[0];

  assign delay69_re = delay_pipeline_re[68];

  assign delay69_im = delay_pipeline_im[68];

  assign combined1_re = delay1_re + delay69_re;
  assign combined1_im = delay1_im + delay69_im;

  assign gain1_mul_temp = 25'sb1111111111110100001011111 * combined1_re;
  assign gain1_re = {gain1_mul_temp[34], gain1_mul_temp};
  assign gain1_mul_temp_1 = 25'sb1111111111110100001011111 * combined1_im;
  assign gain1_im = {gain1_mul_temp_1[34], gain1_mul_temp_1};

  assign add_add_cast = {{28{gain0_re[35]}}, gain0_re};
  assign add_add_cast_1 = {{28{gain1_re[35]}}, gain1_re};
  assign add_re = add_add_cast + add_add_cast_1;
  assign add_add_cast_2 = {{28{gain0_im[35]}}, gain0_im};
  assign add_add_cast_3 = {{28{gain1_im[35]}}, gain1_im};
  assign add_im = add_add_cast_2 + add_add_cast_3;

  assign delay2_re = delay_pipeline_re[1];

  assign delay2_im = delay_pipeline_im[1];

  assign delay68_re = delay_pipeline_re[67];

  assign delay68_im = delay_pipeline_im[67];

  assign combined2_re = delay2_re + delay68_re;
  assign combined2_im = delay2_im + delay68_im;

  assign gain2_mul_temp = 25'sb1111111111110101000011000 * combined2_re;
  assign gain2_re = {gain2_mul_temp[34], gain2_mul_temp};
  assign gain2_mul_temp_1 = 25'sb1111111111110101000011000 * combined2_im;
  assign gain2_im = {gain2_mul_temp_1[34], gain2_mul_temp_1};

  assign add_add_cast_4 = {{28{gain2_re[35]}}, gain2_re};
  assign add_re_1 = add_re + add_add_cast_4;
  assign add_add_cast_5 = {{28{gain2_im[35]}}, gain2_im};
  assign add_im_1 = add_im + add_add_cast_5;

  assign delay3_re = delay_pipeline_re[2];

  assign delay3_im = delay_pipeline_im[2];

  assign delay67_re = delay_pipeline_re[66];

  assign delay67_im = delay_pipeline_im[66];

  assign combined3_re = delay3_re + delay67_re;
  assign combined3_im = delay3_im + delay67_im;

  assign gain3_mul_temp = 25'sb0000000000000101010001001 * combined3_re;
  assign gain3_re = {gain3_mul_temp[34], gain3_mul_temp};
  assign gain3_mul_temp_1 = 25'sb0000000000000101010001001 * combined3_im;
  assign gain3_im = {gain3_mul_temp_1[34], gain3_mul_temp_1};

  assign add_add_cast_6 = {{28{gain3_re[35]}}, gain3_re};
  assign add_re_2 = add_re_1 + add_add_cast_6;
  assign add_add_cast_7 = {{28{gain3_im[35]}}, gain3_im};
  assign add_im_2 = add_im_1 + add_add_cast_7;

  assign delay4_re = delay_pipeline_re[3];

  assign delay4_im = delay_pipeline_im[3];

  assign delay66_re = delay_pipeline_re[65];

  assign delay66_im = delay_pipeline_im[65];

  assign combined4_re = delay4_re + delay66_re;
  assign combined4_im = delay4_im + delay66_im;

  assign gain4_mul_temp = 25'sb0000000000100011101000011 * combined4_re;
  assign gain4_re = {gain4_mul_temp[34], gain4_mul_temp};
  assign gain4_mul_temp_1 = 25'sb0000000000100011101000011 * combined4_im;
  assign gain4_im = {gain4_mul_temp_1[34], gain4_mul_temp_1};

  assign add_add_cast_8 = {{28{gain4_re[35]}}, gain4_re};
  assign add_re_3 = add_re_2 + add_add_cast_8;
  assign add_add_cast_9 = {{28{gain4_im[35]}}, gain4_im};
  assign add_im_3 = add_im_2 + add_add_cast_9;

  assign delay5_re = delay_pipeline_re[4];

  assign delay5_im = delay_pipeline_im[4];

  assign delay65_re = delay_pipeline_re[64];

  assign delay65_im = delay_pipeline_im[64];

  assign combined5_re = delay5_re + delay65_re;
  assign combined5_im = delay5_im + delay65_im;

  assign gain5_mul_temp = 25'sb0000000000111110111011001 * combined5_re;
  assign gain5_re = {gain5_mul_temp[34], gain5_mul_temp};
  assign gain5_mul_temp_1 = 25'sb0000000000111110111011001 * combined5_im;
  assign gain5_im = {gain5_mul_temp_1[34], gain5_mul_temp_1};

  assign add_add_cast_10 = {{28{gain5_re[35]}}, gain5_re};
  assign add_re_4 = add_re_3 + add_add_cast_10;
  assign add_add_cast_11 = {{28{gain5_im[35]}}, gain5_im};
  assign add_im_4 = add_im_3 + add_add_cast_11;

  assign delay6_re = delay_pipeline_re[5];

  assign delay6_im = delay_pipeline_im[5];

  assign delay64_re = delay_pipeline_re[63];

  assign delay64_im = delay_pipeline_im[63];

  assign combined6_re = delay6_re + delay64_re;
  assign combined6_im = delay6_im + delay64_im;

  assign gain6_mul_temp = 25'sb0000000000111101000111001 * combined6_re;
  assign gain6_re = {gain6_mul_temp[34], gain6_mul_temp};
  assign gain6_mul_temp_1 = 25'sb0000000000111101000111001 * combined6_im;
  assign gain6_im = {gain6_mul_temp_1[34], gain6_mul_temp_1};

  assign add_add_cast_12 = {{28{gain6_re[35]}}, gain6_re};
  assign add_re_5 = add_re_4 + add_add_cast_12;
  assign add_add_cast_13 = {{28{gain6_im[35]}}, gain6_im};
  assign add_im_5 = add_im_4 + add_add_cast_13;

  assign delay7_re = delay_pipeline_re[6];

  assign delay7_im = delay_pipeline_im[6];

  assign delay63_re = delay_pipeline_re[62];

  assign delay63_im = delay_pipeline_im[62];

  assign combined7_re = delay7_re + delay63_re;
  assign combined7_im = delay7_im + delay63_im;

  assign gain7_mul_temp = 25'sb0000000000010000011110001 * combined7_re;
  assign gain7_re = {gain7_mul_temp[34], gain7_mul_temp};
  assign gain7_mul_temp_1 = 25'sb0000000000010000011110001 * combined7_im;
  assign gain7_im = {gain7_mul_temp_1[34], gain7_mul_temp_1};

  assign add_add_cast_14 = {{28{gain7_re[35]}}, gain7_re};
  assign add_re_6 = add_re_5 + add_add_cast_14;
  assign add_add_cast_15 = {{28{gain7_im[35]}}, gain7_im};
  assign add_im_6 = add_im_5 + add_add_cast_15;

  assign delay8_re = delay_pipeline_re[7];

  assign delay8_im = delay_pipeline_im[7];

  assign delay62_re = delay_pipeline_re[61];

  assign delay62_im = delay_pipeline_im[61];

  assign combined8_re = delay8_re + delay62_re;
  assign combined8_im = delay8_im + delay62_im;

  assign gain8_mul_temp = 25'sb1111111111001011111001001 * combined8_re;
  assign gain8_re = {gain8_mul_temp[34], gain8_mul_temp};
  assign gain8_mul_temp_1 = 25'sb1111111111001011111001001 * combined8_im;
  assign gain8_im = {gain8_mul_temp_1[34], gain8_mul_temp_1};

  assign add_add_cast_16 = {{28{gain8_re[35]}}, gain8_re};
  assign add_re_7 = add_re_6 + add_add_cast_16;
  assign add_add_cast_17 = {{28{gain8_im[35]}}, gain8_im};
  assign add_im_7 = add_im_6 + add_add_cast_17;

  assign delay9_re = delay_pipeline_re[8];

  assign delay9_im = delay_pipeline_im[8];

  assign delay61_re = delay_pipeline_re[60];

  assign delay61_im = delay_pipeline_im[60];

  assign combined9_re = delay9_re + delay61_re;
  assign combined9_im = delay9_im + delay61_im;

  assign gain9_mul_temp = 25'sb1111111110100000110101110 * combined9_re;
  assign gain9_re = {gain9_mul_temp[34], gain9_mul_temp};
  assign gain9_mul_temp_1 = 25'sb1111111110100000110101110 * combined9_im;
  assign gain9_im = {gain9_mul_temp_1[34], gain9_mul_temp_1};

  assign add_add_cast_18 = {{28{gain9_re[35]}}, gain9_re};
  assign add_re_8 = add_re_7 + add_add_cast_18;
  assign add_add_cast_19 = {{28{gain9_im[35]}}, gain9_im};
  assign add_im_8 = add_im_7 + add_add_cast_19;

  assign delay10_re = delay_pipeline_re[9];

  assign delay10_im = delay_pipeline_im[9];

  assign delay60_re = delay_pipeline_re[59];

  assign delay60_im = delay_pipeline_im[59];

  assign combined10_re = delay10_re + delay60_re;
  assign combined10_im = delay10_im + delay60_im;

  assign gain10_mul_temp = 25'sb1111111110111110010010101 * combined10_re;
  assign gain10_re = {gain10_mul_temp[34], gain10_mul_temp};
  assign gain10_mul_temp_1 = 25'sb1111111110111110010010101 * combined10_im;
  assign gain10_im = {gain10_mul_temp_1[34], gain10_mul_temp_1};

  assign add_add_cast_20 = {{28{gain10_re[35]}}, gain10_re};
  assign add_re_9 = add_re_8 + add_add_cast_20;
  assign add_add_cast_21 = {{28{gain10_im[35]}}, gain10_im};
  assign add_im_9 = add_im_8 + add_add_cast_21;

  assign delay11_re = delay_pipeline_re[10];

  assign delay11_im = delay_pipeline_im[10];

  assign delay59_re = delay_pipeline_re[58];

  assign delay59_im = delay_pipeline_im[58];

  assign combined11_re = delay11_re + delay59_re;
  assign combined11_im = delay11_im + delay59_im;

  assign gain11_mul_temp = 25'sb0000000000100011101000000 * combined11_re;
  assign gain11_re = {gain11_mul_temp[34], gain11_mul_temp};
  assign gain11_mul_temp_1 = 25'sb0000000000100011101000000 * combined11_im;
  assign gain11_im = {gain11_mul_temp_1[34], gain11_mul_temp_1};

  assign add_add_cast_22 = {{28{gain11_re[35]}}, gain11_re};
  assign add_re_10 = add_re_9 + add_add_cast_22;
  assign add_add_cast_23 = {{28{gain11_im[35]}}, gain11_im};
  assign add_im_10 = add_im_9 + add_add_cast_23;

  assign delay12_re = delay_pipeline_re[11];

  assign delay12_im = delay_pipeline_im[11];

  assign delay58_re = delay_pipeline_re[57];

  assign delay58_im = delay_pipeline_im[57];

  assign combined12_re = delay12_re + delay58_re;
  assign combined12_im = delay12_im + delay58_im;

  assign gain12_mul_temp = 25'sb0000000010001110100000101 * combined12_re;
  assign gain12_re = {gain12_mul_temp[34], gain12_mul_temp};
  assign gain12_mul_temp_1 = 25'sb0000000010001110100000101 * combined12_im;
  assign gain12_im = {gain12_mul_temp_1[34], gain12_mul_temp_1};

  assign add_add_cast_24 = {{28{gain12_re[35]}}, gain12_re};
  assign add_re_11 = add_re_10 + add_add_cast_24;
  assign add_add_cast_25 = {{28{gain12_im[35]}}, gain12_im};
  assign add_im_11 = add_im_10 + add_add_cast_25;

  assign delay13_re = delay_pipeline_re[12];

  assign delay13_im = delay_pipeline_im[12];

  assign delay57_re = delay_pipeline_re[56];

  assign delay57_im = delay_pipeline_im[56];

  assign combined13_re = delay13_re + delay57_re;
  assign combined13_im = delay13_im + delay57_im;

  assign gain13_mul_temp = 25'sb0000000010011111111001001 * combined13_re;
  assign gain13_re = {gain13_mul_temp[34], gain13_mul_temp};
  assign gain13_mul_temp_1 = 25'sb0000000010011111111001001 * combined13_im;
  assign gain13_im = {gain13_mul_temp_1[34], gain13_mul_temp_1};

  assign add_add_cast_26 = {{28{gain13_re[35]}}, gain13_re};
  assign add_re_12 = add_re_11 + add_add_cast_26;
  assign add_add_cast_27 = {{28{gain13_im[35]}}, gain13_im};
  assign add_im_12 = add_im_11 + add_add_cast_27;

  assign delay14_re = delay_pipeline_re[13];

  assign delay14_im = delay_pipeline_im[13];

  assign delay56_re = delay_pipeline_re[55];

  assign delay56_im = delay_pipeline_im[55];

  assign combined14_re = delay14_re + delay56_re;
  assign combined14_im = delay14_im + delay56_im;

  assign gain14_mul_temp = 25'sb0000000000101001011011101 * combined14_re;
  assign gain14_re = {gain14_mul_temp[34], gain14_mul_temp};
  assign gain14_mul_temp_1 = 25'sb0000000000101001011011101 * combined14_im;
  assign gain14_im = {gain14_mul_temp_1[34], gain14_mul_temp_1};

  assign add_add_cast_28 = {{28{gain14_re[35]}}, gain14_re};
  assign add_re_13 = add_re_12 + add_add_cast_28;
  assign add_add_cast_29 = {{28{gain14_im[35]}}, gain14_im};
  assign add_im_13 = add_im_12 + add_add_cast_29;

  assign delay15_re = delay_pipeline_re[14];

  assign delay15_im = delay_pipeline_im[14];

  assign delay55_re = delay_pipeline_re[54];

  assign delay55_im = delay_pipeline_im[54];

  assign combined15_re = delay15_re + delay55_re;
  assign combined15_im = delay15_im + delay55_im;

  assign gain15_mul_temp = 25'sb1111111101101000101011010 * combined15_re;
  assign gain15_re = {gain15_mul_temp[34], gain15_mul_temp};
  assign gain15_mul_temp_1 = 25'sb1111111101101000101011010 * combined15_im;
  assign gain15_im = {gain15_mul_temp_1[34], gain15_mul_temp_1};

  assign add_add_cast_30 = {{28{gain15_re[35]}}, gain15_re};
  assign add_re_14 = add_re_13 + add_add_cast_30;
  assign add_add_cast_31 = {{28{gain15_im[35]}}, gain15_im};
  assign add_im_14 = add_im_13 + add_add_cast_31;

  assign delay16_re = delay_pipeline_re[15];

  assign delay16_im = delay_pipeline_im[15];

  assign delay54_re = delay_pipeline_re[53];

  assign delay54_im = delay_pipeline_im[53];

  assign combined16_re = delay16_re + delay54_re;
  assign combined16_im = delay16_im + delay54_im;

  assign gain16_mul_temp = 25'sb1111111011110010011101000 * combined16_re;
  assign gain16_re = {gain16_mul_temp[34], gain16_mul_temp};
  assign gain16_mul_temp_1 = 25'sb1111111011110010011101000 * combined16_im;
  assign gain16_im = {gain16_mul_temp_1[34], gain16_mul_temp_1};

  assign add_add_cast_32 = {{28{gain16_re[35]}}, gain16_re};
  assign add_re_15 = add_re_14 + add_add_cast_32;
  assign add_add_cast_33 = {{28{gain16_im[35]}}, gain16_im};
  assign add_im_15 = add_im_14 + add_add_cast_33;

  assign delay17_re = delay_pipeline_re[16];

  assign delay17_im = delay_pipeline_im[16];

  assign delay53_re = delay_pipeline_re[52];

  assign delay53_im = delay_pipeline_im[52];

  assign combined17_re = delay17_re + delay53_re;
  assign combined17_im = delay17_im + delay53_im;

  assign gain17_mul_temp = 25'sb1111111101000111011100111 * combined17_re;
  assign gain17_re = {gain17_mul_temp[34], gain17_mul_temp};
  assign gain17_mul_temp_1 = 25'sb1111111101000111011100111 * combined17_im;
  assign gain17_im = {gain17_mul_temp_1[34], gain17_mul_temp_1};

  assign add_add_cast_34 = {{28{gain17_re[35]}}, gain17_re};
  assign add_re_16 = add_re_15 + add_add_cast_34;
  assign add_add_cast_35 = {{28{gain17_im[35]}}, gain17_im};
  assign add_im_16 = add_im_15 + add_add_cast_35;

  assign delay18_re = delay_pipeline_re[17];

  assign delay18_im = delay_pipeline_im[17];

  assign delay52_re = delay_pipeline_re[51];

  assign delay52_im = delay_pipeline_im[51];

  assign combined18_re = delay18_re + delay52_re;
  assign combined18_im = delay18_im + delay52_im;

  assign gain18_mul_temp = 25'sb0000000001011001011100010 * combined18_re;
  assign gain18_re = {gain18_mul_temp[34], gain18_mul_temp};
  assign gain18_mul_temp_1 = 25'sb0000000001011001011100010 * combined18_im;
  assign gain18_im = {gain18_mul_temp_1[34], gain18_mul_temp_1};

  assign add_add_cast_36 = {{28{gain18_re[35]}}, gain18_re};
  assign add_re_17 = add_re_16 + add_add_cast_36;
  assign add_add_cast_37 = {{28{gain18_im[35]}}, gain18_im};
  assign add_im_17 = add_im_16 + add_add_cast_37;

  assign delay19_re = delay_pipeline_re[18];

  assign delay19_im = delay_pipeline_im[18];

  assign delay51_re = delay_pipeline_re[50];

  assign delay51_im = delay_pipeline_im[50];

  assign combined19_re = delay19_re + delay51_re;
  assign combined19_im = delay19_im + delay51_im;

  assign gain19_mul_temp = 25'sb0000000101101100101101000 * combined19_re;
  assign gain19_re = {gain19_mul_temp[34], gain19_mul_temp};
  assign gain19_mul_temp_1 = 25'sb0000000101101100101101000 * combined19_im;
  assign gain19_im = {gain19_mul_temp_1[34], gain19_mul_temp_1};

  assign add_add_cast_38 = {{28{gain19_re[35]}}, gain19_re};
  assign add_re_18 = add_re_17 + add_add_cast_38;
  assign add_add_cast_39 = {{28{gain19_im[35]}}, gain19_im};
  assign add_im_18 = add_im_17 + add_add_cast_39;

  assign delay20_re = delay_pipeline_re[19];

  assign delay20_im = delay_pipeline_im[19];

  assign delay50_re = delay_pipeline_re[49];

  assign delay50_im = delay_pipeline_im[49];

  assign combined20_re = delay20_re + delay50_re;
  assign combined20_im = delay20_im + delay50_im;

  assign gain20_mul_temp = 25'sb0000000110001100110010101 * combined20_re;
  assign gain20_re = {gain20_mul_temp[34], gain20_mul_temp};
  assign gain20_mul_temp_1 = 25'sb0000000110001100110010101 * combined20_im;
  assign gain20_im = {gain20_mul_temp_1[34], gain20_mul_temp_1};

  assign add_add_cast_40 = {{28{gain20_re[35]}}, gain20_re};
  assign add_re_19 = add_re_18 + add_add_cast_40;
  assign add_add_cast_41 = {{28{gain20_im[35]}}, gain20_im};
  assign add_im_19 = add_im_18 + add_add_cast_41;

  assign delay21_re = delay_pipeline_re[20];

  assign delay21_im = delay_pipeline_im[20];

  assign delay49_re = delay_pipeline_re[48];

  assign delay49_im = delay_pipeline_im[48];

  assign combined21_re = delay21_re + delay49_re;
  assign combined21_im = delay21_im + delay49_im;

  assign gain21_mul_temp = 25'sb0000000001010110010001011 * combined21_re;
  assign gain21_re = {gain21_mul_temp[34], gain21_mul_temp};
  assign gain21_mul_temp_1 = 25'sb0000000001010110010001011 * combined21_im;
  assign gain21_im = {gain21_mul_temp_1[34], gain21_mul_temp_1};

  assign add_add_cast_42 = {{28{gain21_re[35]}}, gain21_re};
  assign add_re_20 = add_re_19 + add_add_cast_42;
  assign add_add_cast_43 = {{28{gain21_im[35]}}, gain21_im};
  assign add_im_20 = add_im_19 + add_add_cast_43;

  assign delay22_re = delay_pipeline_re[21];

  assign delay22_im = delay_pipeline_im[21];

  assign delay48_re = delay_pipeline_re[47];

  assign delay48_im = delay_pipeline_im[47];

  assign combined22_re = delay22_re + delay48_re;
  assign combined22_im = delay22_im + delay48_im;

  assign gain22_mul_temp = 25'sb1111111001111001001100010 * combined22_re;
  assign gain22_re = {gain22_mul_temp[34], gain22_mul_temp};
  assign gain22_mul_temp_1 = 25'sb1111111001111001001100010 * combined22_im;
  assign gain22_im = {gain22_mul_temp_1[34], gain22_mul_temp_1};

  assign add_add_cast_44 = {{28{gain22_re[35]}}, gain22_re};
  assign add_re_21 = add_re_20 + add_add_cast_44;
  assign add_add_cast_45 = {{28{gain22_im[35]}}, gain22_im};
  assign add_im_21 = add_im_20 + add_add_cast_45;

  assign delay23_re = delay_pipeline_re[22];

  assign delay23_im = delay_pipeline_im[22];

  assign delay47_re = delay_pipeline_re[46];

  assign delay47_im = delay_pipeline_im[46];

  assign combined23_re = delay23_re + delay47_re;
  assign combined23_im = delay23_im + delay47_im;

  assign gain23_mul_temp = 25'sb1111110101101100100010111 * combined23_re;
  assign gain23_re = {gain23_mul_temp[34], gain23_mul_temp};
  assign gain23_mul_temp_1 = 25'sb1111110101101100100010111 * combined23_im;
  assign gain23_im = {gain23_mul_temp_1[34], gain23_mul_temp_1};

  assign add_add_cast_46 = {{28{gain23_re[35]}}, gain23_re};
  assign add_re_22 = add_re_21 + add_add_cast_46;
  assign add_add_cast_47 = {{28{gain23_im[35]}}, gain23_im};
  assign add_im_22 = add_im_21 + add_add_cast_47;

  assign delay24_re = delay_pipeline_re[23];

  assign delay24_im = delay_pipeline_im[23];

  assign delay46_re = delay_pipeline_re[45];

  assign delay46_im = delay_pipeline_im[45];

  assign combined24_re = delay24_re + delay46_re;
  assign combined24_im = delay24_im + delay46_im;

  assign gain24_mul_temp = 25'sb1111111001011100111111101 * combined24_re;
  assign gain24_re = {gain24_mul_temp[34], gain24_mul_temp};
  assign gain24_mul_temp_1 = 25'sb1111111001011100111111101 * combined24_im;
  assign gain24_im = {gain24_mul_temp_1[34], gain24_mul_temp_1};

  assign add_add_cast_48 = {{28{gain24_re[35]}}, gain24_re};
  assign add_re_23 = add_re_22 + add_add_cast_48;
  assign add_add_cast_49 = {{28{gain24_im[35]}}, gain24_im};
  assign add_im_23 = add_im_22 + add_add_cast_49;

  assign delay25_re = delay_pipeline_re[24];

  assign delay25_im = delay_pipeline_im[24];

  assign delay45_re = delay_pipeline_re[44];

  assign delay45_im = delay_pipeline_im[44];

  assign combined25_re = delay25_re + delay45_re;
  assign combined25_im = delay25_im + delay45_im;

  assign gain25_mul_temp = 25'sb0000000100001111010101100 * combined25_re;
  assign gain25_re = {gain25_mul_temp[34], gain25_mul_temp};
  assign gain25_mul_temp_1 = 25'sb0000000100001111010101100 * combined25_im;
  assign gain25_im = {gain25_mul_temp_1[34], gain25_mul_temp_1};

  assign add_add_cast_50 = {{28{gain25_re[35]}}, gain25_re};
  assign add_re_24 = add_re_23 + add_add_cast_50;
  assign add_add_cast_51 = {{28{gain25_im[35]}}, gain25_im};
  assign add_im_24 = add_im_23 + add_add_cast_51;

  assign delay26_re = delay_pipeline_re[25];

  assign delay26_im = delay_pipeline_im[25];

  assign delay44_re = delay_pipeline_re[43];

  assign delay44_im = delay_pipeline_im[43];

  assign combined26_re = delay26_re + delay44_re;
  assign combined26_im = delay26_im + delay44_im;

  assign gain26_mul_temp = 25'sb0000001110101001100000110 * combined26_re;
  assign gain26_re = {gain26_mul_temp[34], gain26_mul_temp};
  assign gain26_mul_temp_1 = 25'sb0000001110101001100000110 * combined26_im;
  assign gain26_im = {gain26_mul_temp_1[34], gain26_mul_temp_1};

  assign add_add_cast_52 = {{28{gain26_re[35]}}, gain26_re};
  assign add_re_25 = add_re_24 + add_add_cast_52;
  assign add_add_cast_53 = {{28{gain26_im[35]}}, gain26_im};
  assign add_im_25 = add_im_24 + add_add_cast_53;

  assign delay27_re = delay_pipeline_re[26];

  assign delay27_im = delay_pipeline_im[26];

  assign delay43_re = delay_pipeline_re[42];

  assign delay43_im = delay_pipeline_im[42];

  assign combined27_re = delay27_re + delay43_re;
  assign combined27_im = delay27_im + delay43_im;

  assign gain27_mul_temp = 25'sb0000001111001111000110000 * combined27_re;
  assign gain27_re = {gain27_mul_temp[34], gain27_mul_temp};
  assign gain27_mul_temp_1 = 25'sb0000001111001111000110000 * combined27_im;
  assign gain27_im = {gain27_mul_temp_1[34], gain27_mul_temp_1};

  assign add_add_cast_54 = {{28{gain27_re[35]}}, gain27_re};
  assign add_re_26 = add_re_25 + add_add_cast_54;
  assign add_add_cast_55 = {{28{gain27_im[35]}}, gain27_im};
  assign add_im_26 = add_im_25 + add_add_cast_55;

  assign delay28_re = delay_pipeline_re[27];

  assign delay28_im = delay_pipeline_im[27];

  assign delay42_re = delay_pipeline_re[41];

  assign delay42_im = delay_pipeline_im[41];

  assign combined28_re = delay28_re + delay42_re;
  assign combined28_im = delay28_im + delay42_im;

  assign gain28_mul_temp = 25'sb0000000001111110101111101 * combined28_re;
  assign gain28_re = {gain28_mul_temp[34], gain28_mul_temp};
  assign gain28_mul_temp_1 = 25'sb0000000001111110101111101 * combined28_im;
  assign gain28_im = {gain28_mul_temp_1[34], gain28_mul_temp_1};

  assign add_add_cast_56 = {{28{gain28_re[35]}}, gain28_re};
  assign add_re_27 = add_re_26 + add_add_cast_56;
  assign add_add_cast_57 = {{28{gain28_im[35]}}, gain28_im};
  assign add_im_27 = add_im_26 + add_add_cast_57;

  assign delay29_re = delay_pipeline_re[28];

  assign delay29_im = delay_pipeline_im[28];

  assign delay41_re = delay_pipeline_re[40];

  assign delay41_im = delay_pipeline_im[40];

  assign combined29_re = delay29_re + delay41_re;
  assign combined29_im = delay29_im + delay41_im;

  assign gain29_mul_temp = 25'sb1111101101011111000000010 * combined29_re;
  assign gain29_re = {gain29_mul_temp[34], gain29_mul_temp};
  assign gain29_mul_temp_1 = 25'sb1111101101011111000000010 * combined29_im;
  assign gain29_im = {gain29_mul_temp_1[34], gain29_mul_temp_1};

  assign add_add_cast_58 = {{28{gain29_re[35]}}, gain29_re};
  assign add_re_28 = add_re_27 + add_add_cast_58;
  assign add_add_cast_59 = {{28{gain29_im[35]}}, gain29_im};
  assign add_im_28 = add_im_27 + add_add_cast_59;

  assign delay30_re = delay_pipeline_re[29];

  assign delay30_im = delay_pipeline_im[29];

  assign delay40_re = delay_pipeline_re[39];

  assign delay40_im = delay_pipeline_im[39];

  assign combined30_re = delay30_re + delay40_re;
  assign combined30_im = delay30_im + delay40_im;

  assign gain30_mul_temp = 25'sb1111100001010001010110010 * combined30_re;
  assign gain30_re = {gain30_mul_temp[34], gain30_mul_temp};
  assign gain30_mul_temp_1 = 25'sb1111100001010001010110010 * combined30_im;
  assign gain30_im = {gain30_mul_temp_1[34], gain30_mul_temp_1};

  assign add_add_cast_60 = {{28{gain30_re[35]}}, gain30_re};
  assign add_re_29 = add_re_28 + add_add_cast_60;
  assign add_add_cast_61 = {{28{gain30_im[35]}}, gain30_im};
  assign add_im_29 = add_im_28 + add_add_cast_61;

  assign delay31_re = delay_pipeline_re[30];

  assign delay31_im = delay_pipeline_im[30];

  assign delay39_re = delay_pipeline_re[38];

  assign delay39_im = delay_pipeline_im[38];

  assign combined31_re = delay31_re + delay39_re;
  assign combined31_im = delay31_im + delay39_im;

  assign gain31_mul_temp = 25'sb1111101100111011011111011 * combined31_re;
  assign gain31_re = {gain31_mul_temp[34], gain31_mul_temp};
  assign gain31_mul_temp_1 = 25'sb1111101100111011011111011 * combined31_im;
  assign gain31_im = {gain31_mul_temp_1[34], gain31_mul_temp_1};

  assign add_add_cast_62 = {{28{gain31_re[35]}}, gain31_re};
  assign add_re_30 = add_re_29 + add_add_cast_62;
  assign add_add_cast_63 = {{28{gain31_im[35]}}, gain31_im};
  assign add_im_30 = add_im_29 + add_add_cast_63;

  assign delay32_re = delay_pipeline_re[31];

  assign delay32_im = delay_pipeline_im[31];

  assign delay38_re = delay_pipeline_re[37];

  assign delay38_im = delay_pipeline_im[37];

  assign combined32_re = delay32_re + delay38_re;
  assign combined32_im = delay32_im + delay38_im;

  assign gain32_mul_temp = 25'sb0000010101001100001000101 * combined32_re;
  assign gain32_re = {gain32_mul_temp[34], gain32_mul_temp};
  assign gain32_mul_temp_1 = 25'sb0000010101001100001000101 * combined32_im;
  assign gain32_im = {gain32_mul_temp_1[34], gain32_mul_temp_1};

  assign add_add_cast_64 = {{28{gain32_re[35]}}, gain32_re};
  assign add_re_31 = add_re_30 + add_add_cast_64;
  assign add_add_cast_65 = {{28{gain32_im[35]}}, gain32_im};
  assign add_im_31 = add_im_30 + add_add_cast_65;

  assign delay33_re = delay_pipeline_re[32];

  assign delay33_im = delay_pipeline_im[32];

  assign delay37_re = delay_pipeline_re[36];

  assign delay37_im = delay_pipeline_im[36];

  assign combined33_re = delay33_re + delay37_re;
  assign combined33_im = delay33_im + delay37_im;

  assign gain33_mul_temp = 25'sb0001001110010101010110100 * combined33_re;
  assign gain33_re = {gain33_mul_temp[34], gain33_mul_temp};
  assign gain33_mul_temp_1 = 25'sb0001001110010101010110100 * combined33_im;
  assign gain33_im = {gain33_mul_temp_1[34], gain33_mul_temp_1};

  assign add_add_cast_66 = {{28{gain33_re[35]}}, gain33_re};
  assign add_re_32 = add_re_31 + add_add_cast_66;
  assign add_add_cast_67 = {{28{gain33_im[35]}}, gain33_im};
  assign add_im_32 = add_im_31 + add_add_cast_67;

  assign delay34_re = delay_pipeline_re[33];

  assign delay34_im = delay_pipeline_im[33];

  assign delay36_re = delay_pipeline_re[35];

  assign delay36_im = delay_pipeline_im[35];

  assign combined34_re = delay34_re + delay36_re;
  assign combined34_im = delay34_im + delay36_im;

  assign gain34_mul_temp = 25'sb0010000000100011111000110 * combined34_re;
  assign gain34_re = {gain34_mul_temp[34], gain34_mul_temp};
  assign gain34_mul_temp_1 = 25'sb0010000000100011111000110 * combined34_im;
  assign gain34_im = {gain34_mul_temp_1[34], gain34_mul_temp_1};

  assign add_add_cast_68 = {{28{gain34_re[35]}}, gain34_re};
  assign add_re_33 = add_re_32 + add_add_cast_68;
  assign add_add_cast_69 = {{28{gain34_im[35]}}, gain34_im};
  assign add_im_33 = add_im_32 + add_add_cast_69;

  assign delay35_re = delay_pipeline_re[34];

  assign delay35_im = delay_pipeline_im[34];

  assign gain35_mul_temp = 25'sb0010010100100001010111011 * delay35_re;
  assign gain35_re = {gain35_mul_temp[34], gain35_mul_temp};
  assign gain35_mul_temp_1 = 25'sb0010010100100001010111011 * delay35_im;
  assign gain35_im = {gain35_mul_temp_1[34], gain35_mul_temp_1};

  assign add_add_cast_70 = {{28{gain35_re[35]}}, gain35_re};
  assign Discrete_FIR_Filter1_out_re = add_re_33 + add_add_cast_70;
  assign add_add_cast_71 = {{28{gain35_im[35]}}, gain35_im};
  assign Discrete_FIR_Filter1_out_im = add_im_33 + add_add_cast_71;

endmodule  // Discrete_FIR_Filter1

