// -------------------------------------------------------------
// 
// File Name: hdlsrc\dsp_proj_v3_2024_n\dsp_proj_v3_2024_n_tc.v
// Created: 2026-04-12 08:40:34
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dsp_proj_v3_2024_n_tc
// Source Path: dsp_proj_v3_2024_n_tc
// Hierarchy Level: 1
// 
// Master clock enable input: clk_enable
// 
// enb         : identical to clk_enable
// enb_1_5_0   : 5x slower than clk with last phase
// enb_1_5_1   : 5x slower than clk with phase 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dsp_proj_v3_2024_n_tc
          (clk,
           reset,
           clk_enable,
           enb,
           enb_1_5_0,
           enb_1_5_1);


  input   clk;
  input   reset;
  input   clk_enable;
  output  enb;
  output  enb_1_5_0;
  output  enb_1_5_1;


  reg [2:0] count5;  // ufix3
  wire comp_0_tmp;
  wire phase_0_tmp;
  reg  phase_0;
  wire enb_1_5_0_1;
  wire comp_1_tmp;
  wire phase_1_tmp;
  reg  phase_1;
  wire enb_1_5_1_1;


  assign enb = clk_enable;

  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 4
  always @(posedge clk or posedge reset)
    begin : counter_5_process
      if (reset == 1'b1) begin
        count5 <= 3'b001;
      end
      else begin
        if (clk_enable) begin
          if (count5 >= 3'b100) begin
            count5 <= 3'b000;
          end
          else begin
            count5 <= count5 + 3'b001;
          end
        end
      end
    end

  assign comp_0_tmp = count5 == 3'b100;

  assign phase_0_tmp = comp_0_tmp & clk_enable;

  always @(posedge clk or posedge reset)
    begin : phase_delay_process
      if (reset == 1'b1) begin
        phase_0 <= 1'b0;
      end
      else begin
        if (clk_enable) begin
          phase_0 <= phase_0_tmp;
        end
      end
    end

  assign enb_1_5_0_1 = phase_0 & clk_enable;

  assign enb_1_5_0 = enb_1_5_0_1;

  assign comp_1_tmp = count5 == 3'b000;

  assign phase_1_tmp = comp_1_tmp & clk_enable;

  always @(posedge clk or posedge reset)
    begin : phase_delay_1_process
      if (reset == 1'b1) begin
        phase_1 <= 1'b1;
      end
      else begin
        if (clk_enable) begin
          phase_1 <= phase_1_tmp;
        end
      end
    end

  assign enb_1_5_1_1 = phase_1 & clk_enable;

  assign enb_1_5_1 = enb_1_5_1_1;

endmodule  // dsp_proj_v3_2024_n_tc

