// -------------------------------------------------------------
// 
// File Name: hdlsrc\dsp_proj_v3_2024_n\dsp_proj_v3_2024_n.v
// Created: 2026-04-12 08:40:35
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1.66667e-08
// Target subsystem base rate: 1.66667e-08
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        8.33333e-08
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1_re                       ce_out        8.33333e-08
// Out1_im                       ce_out        8.33333e-08
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dsp_proj_v3_2024_n
// Source Path: dsp_proj_v3_2024_n
// Hierarchy Level: 0
// Model version: 3.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dsp_proj_v3_2024_n
          (clk,
           reset,
           clk_enable,
           ce_out,
           Out1_re,
           Out1_im);


  input   clk;
  input   reset;
  input   clk_enable;
  output  ce_out;
  output  signed [13:0] Out1_re;  // sfix14_En11
  output  signed [13:0] Out1_im;  // sfix14_En11


  wire enb;
  wire enb_1_5_1;
  wire enb_1_5_0;
  wire Constant_out1;
  wire [11:0] count_step;  // ufix12
  wire [11:0] count_from;  // ufix12
  wire [11:0] count_reset;  // ufix12
  reg [11:0] Sys_Base_CLK2_out1;  // ufix12
  wire [11:0] count;  // ufix12
  wire need_to_wrap;
  wire [11:0] count_value;  // ufix12
  wire [11:0] count_1;  // ufix12
  wire EN_CLK_6_out1;
  wire [11:0] count_2;  // ufix12
  wire switch_compare_1;
  wire signed [7:0] Constant3_out1_re;  // sfix8_En6
  wire signed [7:0] Constant3_out1_im;  // sfix8_En6
  wire [11:0] count_step_1;  // ufix12
  wire [11:0] count_from_1;  // ufix12
  wire [11:0] count_reset_1;  // ufix12
  reg [11:0] Sys_Base_CLK_out1;  // ufix12
  wire [11:0] count_3;  // ufix12
  wire need_to_wrap_1;
  wire [11:0] count_value_1;  // ufix12
  wire [11:0] count_4;  // ufix12
  wire alpha100_cyles_per_load_and_processing_out1;
  wire [11:0] count_5;  // ufix12
  wire Process;
  wire Trigger_Reset_when_Going_to_processing_mode_Y;
  wire [11:0] count_step_2;  // ufix12
  wire [11:0] count_from_2;  // ufix12
  wire [11:0] count_reset_2;  // ufix12
  reg [11:0] RAM1_addr_cntr_out1;  // ufix12
  wire [11:0] count_6;  // ufix12
  wire need_to_wrap_2;
  wire [11:0] count_value_2;  // ufix12
  wire [11:0] count_7;  // ufix12
  wire [11:0] count_8;  // ufix12
  wire Constant2_out1;
  wire signed [7:0] RAM1_out1_re;  // sfix8_En6
  wire signed [7:0] RAM1_out1_im;  // sfix8_En6
  wire signed [7:0] Constant1_out1_re;  // sfix8_En6
  wire signed [7:0] Constant1_out1_im;  // sfix8_En6
  wire signed [7:0] Switch2_out1_re;  // sfix8_En6
  wire signed [7:0] Switch2_out1_im;  // sfix8_En6
  wire signed [63:0] Discrete_FIR_Filter_out1_re;  // sfix64_En30
  wire signed [63:0] Discrete_FIR_Filter_out1_im;  // sfix64_En30
  reg signed [63:0] Downsample2_bypass_reg_re;  // sfix64_En30
  reg signed [63:0] Downsample2_bypass_reg_im;  // sfix64_En30
  wire signed [63:0] Downsample2_out1_re;  // sfix64_En30
  wire signed [63:0] Downsample2_out1_im;  // sfix64_En30
  wire signed [11:0] Data_Type_Conversion_out1_re;  // sfix12_En11
  wire signed [11:0] Data_Type_Conversion_out1_im;  // sfix12_En11
  wire [11:0] count_step_3;  // ufix12
  wire [11:0] count_from_3;  // ufix12
  wire [11:0] count_reset_3;  // ufix12
  reg [11:0] Sys_Base_CLK3_out1;  // ufix12
  wire [11:0] count_9;  // ufix12
  wire need_to_wrap_3;
  wire [11:0] count_value_3;  // ufix12
  wire [11:0] count_10;  // ufix12
  wire EN_CLK_4_out1;
  wire [11:0] count_11;  // ufix12
  wire switch_compare_1_1;
  wire signed [9:0] Constant4_out1_re;  // sfix10_En8
  wire signed [9:0] Constant4_out1_im;  // sfix10_En8
  wire [11:0] count_step_4;  // ufix12
  wire [11:0] count_from_4;  // ufix12
  wire [11:0] count_reset_4;  // ufix12
  reg [11:0] RAM2_addr_cntr_out1;  // ufix12
  wire [11:0] count_12;  // ufix12
  wire need_to_wrap_4;
  wire [11:0] count_value_4;  // ufix12
  wire [11:0] count_13;  // ufix12
  wire [11:0] count_14;  // ufix12
  wire signed [9:0] RAM2_out1_re;  // sfix10_En8
  wire signed [9:0] RAM2_out1_im;  // sfix10_En8
  wire signed [9:0] Constant7_out1_re;  // sfix10_En8
  wire signed [9:0] Constant7_out1_im;  // sfix10_En8
  wire signed [9:0] Switch1_out1_re;  // sfix10_En8
  wire signed [9:0] Switch1_out1_im;  // sfix10_En8
  wire signed [63:0] Discrete_FIR_Filter1_out1_re;  // sfix64_En32
  wire signed [63:0] Discrete_FIR_Filter1_out1_im;  // sfix64_En32
  reg signed [63:0] Downsample1_bypass_reg_re;  // sfix64_En32
  reg signed [63:0] Downsample1_bypass_reg_im;  // sfix64_En32
  wire signed [63:0] Downsample1_out1_re;  // sfix64_En32
  wire signed [63:0] Downsample1_out1_im;  // sfix64_En32
  wire signed [11:0] Data_Type_Conversion2_out1_re;  // sfix12_En11
  wire signed [11:0] Data_Type_Conversion2_out1_im;  // sfix12_En11
  wire signed [31:0] Add_stage2_add_cast;  // sfix32_En11
  wire signed [31:0] Add_stage2_add_cast_1;  // sfix32_En11
  wire signed [31:0] Add_stage2_add_temp;  // sfix32_En11
  wire signed [31:0] Add_stage2_add_cast_2;  // sfix32_En11
  wire signed [31:0] Add_stage2_add_cast_3;  // sfix32_En11
  wire signed [31:0] Add_stage2_add_temp_1;  // sfix32_En11
  wire signed [12:0] Add_op_stage1_re;  // sfix13_En11
  wire signed [12:0] Add_op_stage1_im;  // sfix13_En11
  wire [11:0] count_step_5;  // ufix12
  wire [11:0] count_from_5;  // ufix12
  wire [11:0] count_reset_5;  // ufix12
  reg [11:0] Sys_Base_CLK1_out1;  // ufix12
  wire [11:0] count_15;  // ufix12
  wire need_to_wrap_5;
  wire [11:0] count_value_5;  // ufix12
  wire [11:0] count_16;  // ufix12
  wire EN_CLK_3_out1;
  wire [11:0] count_17;  // ufix12
  wire switch_compare_1_2;
  wire signed [11:0] Constant5_out1_re;  // sfix12_En10
  wire signed [11:0] Constant5_out1_im;  // sfix12_En10
  wire [11:0] count_step_6;  // ufix12
  wire [11:0] count_from_6;  // ufix12
  wire [11:0] count_reset_6;  // ufix12
  reg [11:0] RAM3_addr_cntr_out1;  // ufix12
  wire [11:0] count_18;  // ufix12
  wire need_to_wrap_6;
  wire [11:0] count_value_6;  // ufix12
  wire [11:0] count_19;  // ufix12
  wire [11:0] count_20;  // ufix12
  wire signed [11:0] RAM3_out1_re;  // sfix12_En10
  wire signed [11:0] RAM3_out1_im;  // sfix12_En10
  wire signed [11:0] Constant8_out1_re;  // sfix12_En10
  wire signed [11:0] Constant8_out1_im;  // sfix12_En10
  wire signed [11:0] Switch_out1_re;  // sfix12_En10
  wire signed [11:0] Switch_out1_im;  // sfix12_En10
  wire signed [63:0] Discrete_FIR_Filter2_out1_re;  // sfix64_En34
  wire signed [63:0] Discrete_FIR_Filter2_out1_im;  // sfix64_En34
  reg signed [63:0] Downsample_bypass_reg_re;  // sfix64_En34
  reg signed [63:0] Downsample_bypass_reg_im;  // sfix64_En34
  wire signed [63:0] Downsample_out1_re;  // sfix64_En34
  wire signed [63:0] Downsample_out1_im;  // sfix64_En34
  wire signed [11:0] Data_Type_Conversion1_out1_re;  // sfix12_En11
  wire signed [11:0] Data_Type_Conversion1_out1_im;  // sfix12_En11
  wire signed [31:0] Add_stage3_add_cast;  // sfix32_En11
  wire signed [31:0] Add_stage3_add_cast_1;  // sfix32_En11
  wire signed [31:0] Add_stage3_add_temp;  // sfix32_En11
  wire signed [31:0] Add_stage3_add_cast_2;  // sfix32_En11
  wire signed [31:0] Add_stage3_add_cast_3;  // sfix32_En11
  wire signed [31:0] Add_stage3_add_temp_1;  // sfix32_En11
  wire signed [15:0] Add_out1_re;  // sfix16_En11
  wire signed [15:0] Add_out1_im;  // sfix16_En11
  wire signed [13:0] Output_data_type_out1_re;  // sfix14_En11
  wire signed [13:0] Output_data_type_out1_im;  // sfix14_En11
  wire Constant6_out1;
  wire signed [13:0] Single_Port_RAM_System3_out1_re;  // sfix14_En11
  wire signed [13:0] Single_Port_RAM_System3_out1_im;  // sfix14_En11


  assign Constant_out1 = 1'b1;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 5
  assign count_step = 12'b000000000001;

  assign count_from = 12'b000000000000;

  assign count_reset = 12'b000000000000;

  dsp_proj_v3_2024_n_tc u_dsp_proj_v3_2024_n_tc (.clk(clk),
                                                 .reset(reset),
                                                 .clk_enable(clk_enable),
                                                 .enb(enb),
                                                 .enb_1_5_0(enb_1_5_0),
                                                 .enb_1_5_1(enb_1_5_1)
                                                 );

  assign count = Sys_Base_CLK2_out1 + count_step;

  assign need_to_wrap = Sys_Base_CLK2_out1 == 12'b000000000101;

  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);

  assign count_1 = (Constant_out1 == 1'b0 ? Sys_Base_CLK2_out1 :
              count_value);

  assign count_2 = (EN_CLK_6_out1 == 1'b0 ? count_1 :
              count_reset);

  always @(posedge clk or posedge reset)
    begin : Sys_Base_CLK2_process
      if (reset == 1'b1) begin
        Sys_Base_CLK2_out1 <= 12'b000000000000;
      end
      else begin
        if (enb) begin
          Sys_Base_CLK2_out1 <= count_2;
        end
      end
    end

  assign EN_CLK_6_out1 = Sys_Base_CLK2_out1 == 12'b000000000101;

  assign switch_compare_1 = EN_CLK_6_out1 > 1'b0;

  assign Constant3_out1_re = 8'sb00000000;
  assign Constant3_out1_im = 8'sb00000000;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 1000
  assign count_step_1 = 12'b000000000001;

  assign count_from_1 = 12'b000000000000;

  assign count_reset_1 = 12'b000000000000;

  assign count_3 = Sys_Base_CLK_out1 + count_step_1;

  assign need_to_wrap_1 = Sys_Base_CLK_out1 == 12'b001111101000;

  assign count_value_1 = (need_to_wrap_1 == 1'b0 ? count_3 :
              count_from_1);

  assign count_4 = (Constant_out1 == 1'b0 ? Sys_Base_CLK_out1 :
              count_value_1);

  assign count_5 = (alpha100_cyles_per_load_and_processing_out1 == 1'b0 ? count_4 :
              count_reset_1);

  always @(posedge clk or posedge reset)
    begin : Sys_Base_CLK_process
      if (reset == 1'b1) begin
        Sys_Base_CLK_out1 <= 12'b000000000000;
      end
      else begin
        if (enb) begin
          Sys_Base_CLK_out1 <= count_5;
        end
      end
    end

  assign alpha100_cyles_per_load_and_processing_out1 = Sys_Base_CLK_out1 == 12'b001111101000;

  Chart u_Chart (.clk(clk),
                 .reset(reset),
                 .enb(enb),
                 .EN(alpha100_cyles_per_load_and_processing_out1),
                 .Process(Process)
                 );

  Trigger_Reset_when_Going_to_processing_mode u_Trigger_Reset_when_Going_to_processing_mode (.clk(clk),
                                                                                             .reset(reset),
                                                                                             .enb(enb),
                                                                                             .U(Process),
                                                                                             .Y(Trigger_Reset_when_Going_to_processing_mode_Y)
                                                                                             );

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 3000
  assign count_step_2 = 12'b000000000001;

  assign count_from_2 = 12'b000000000000;

  assign count_reset_2 = 12'b000000000000;

  assign count_6 = RAM1_addr_cntr_out1 + count_step_2;

  assign need_to_wrap_2 = RAM1_addr_cntr_out1 == 12'b101110111000;

  assign count_value_2 = (need_to_wrap_2 == 1'b0 ? count_6 :
              count_from_2);

  assign count_7 = (EN_CLK_6_out1 == 1'b0 ? RAM1_addr_cntr_out1 :
              count_value_2);

  assign count_8 = (Trigger_Reset_when_Going_to_processing_mode_Y == 1'b0 ? count_7 :
              count_reset_2);

  always @(posedge clk or posedge reset)
    begin : RAM1_addr_cntr_process
      if (reset == 1'b1) begin
        RAM1_addr_cntr_out1 <= 12'b000000000000;
      end
      else begin
        if (enb) begin
          RAM1_addr_cntr_out1 <= count_8;
        end
      end
    end

  assign Constant2_out1 = 1'b0;

  SinglePortRAM_generic #(.AddrWidth(12),
                          .DataWidth(8)
                          )
                        u_RAM1 (.clk(clk),
                                .enb(enb),
                                .din_re(Constant3_out1_re),
                                .din_im(Constant3_out1_im),
                                .addr(RAM1_addr_cntr_out1),
                                .we(Constant2_out1),
                                .dout_re(RAM1_out1_re),
                                .dout_im(RAM1_out1_im)
                                );

  assign Constant1_out1_re = 8'sb00000000;
  assign Constant1_out1_im = 8'sb00000000;

  assign Switch2_out1_re = (switch_compare_1 == 1'b0 ? RAM1_out1_re :
              Constant1_out1_re);
  assign Switch2_out1_im = (switch_compare_1 == 1'b0 ? RAM1_out1_im :
              Constant1_out1_im);

  Discrete_FIR_Filter u_Discrete_FIR_Filter (.clk(clk),
                                             .reset(reset),
                                             .enb(enb),
                                             .Discrete_FIR_Filter_in_re(Switch2_out1_re),  // sfix8_En6
                                             .Discrete_FIR_Filter_in_im(Switch2_out1_im),  // sfix8_En6
                                             .Discrete_FIR_Filter_out_re(Discrete_FIR_Filter_out1_re),  // sfix64_En30
                                             .Discrete_FIR_Filter_out_im(Discrete_FIR_Filter_out1_im)  // sfix64_En30
                                             );

  // Downsample2: Downsample by 5, Sample offset 0 
  // Downsample bypass register
  always @(posedge clk or posedge reset)
    begin : Downsample2_bypass_process
      if (reset == 1'b1) begin
        Downsample2_bypass_reg_re <= 64'sh0000000000000000;
        Downsample2_bypass_reg_im <= 64'sh0000000000000000;
      end
      else begin
        if (enb_1_5_1) begin
          Downsample2_bypass_reg_im <= Discrete_FIR_Filter_out1_im;
          Downsample2_bypass_reg_re <= Discrete_FIR_Filter_out1_re;
        end
      end
    end

  assign Downsample2_out1_re = (enb_1_5_1 == 1'b1 ? Discrete_FIR_Filter_out1_re :
              Downsample2_bypass_reg_re);
  assign Downsample2_out1_im = (enb_1_5_1 == 1'b1 ? Discrete_FIR_Filter_out1_im :
              Downsample2_bypass_reg_im);

  assign Data_Type_Conversion_out1_re = ((Downsample2_out1_re[63] == 1'b0) && (Downsample2_out1_re[62:30] != 33'h000000000) ? 12'sb011111111111 :
              ((Downsample2_out1_re[63] == 1'b1) && (Downsample2_out1_re[62:30] != 33'h1FFFFFFFF) ? 12'sb100000000000 :
              $signed(Downsample2_out1_re[30:19])));
  assign Data_Type_Conversion_out1_im = ((Downsample2_out1_im[63] == 1'b0) && (Downsample2_out1_im[62:30] != 33'h000000000) ? 12'sb011111111111 :
              ((Downsample2_out1_im[63] == 1'b1) && (Downsample2_out1_im[62:30] != 33'h1FFFFFFFF) ? 12'sb100000000000 :
              $signed(Downsample2_out1_im[30:19])));

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 3
  assign count_step_3 = 12'b000000000001;

  assign count_from_3 = 12'b000000000000;

  assign count_reset_3 = 12'b000000000000;

  assign count_9 = Sys_Base_CLK3_out1 + count_step_3;

  assign need_to_wrap_3 = Sys_Base_CLK3_out1 == 12'b000000000011;

  assign count_value_3 = (need_to_wrap_3 == 1'b0 ? count_9 :
              count_from_3);

  assign count_10 = (Constant_out1 == 1'b0 ? Sys_Base_CLK3_out1 :
              count_value_3);

  assign count_11 = (EN_CLK_4_out1 == 1'b0 ? count_10 :
              count_reset_3);

  always @(posedge clk or posedge reset)
    begin : Sys_Base_CLK3_process
      if (reset == 1'b1) begin
        Sys_Base_CLK3_out1 <= 12'b000000000000;
      end
      else begin
        if (enb) begin
          Sys_Base_CLK3_out1 <= count_11;
        end
      end
    end

  assign EN_CLK_4_out1 = Sys_Base_CLK3_out1 == 12'b000000000011;

  assign switch_compare_1_1 = EN_CLK_4_out1 > 1'b0;

  assign Constant4_out1_re = 10'sb0000000000;
  assign Constant4_out1_im = 10'sb0000000000;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 3000
  assign count_step_4 = 12'b000000000001;

  assign count_from_4 = 12'b000000000000;

  assign count_reset_4 = 12'b000000000000;

  assign count_12 = RAM2_addr_cntr_out1 + count_step_4;

  assign need_to_wrap_4 = RAM2_addr_cntr_out1 == 12'b101110111000;

  assign count_value_4 = (need_to_wrap_4 == 1'b0 ? count_12 :
              count_from_4);

  assign count_13 = (EN_CLK_4_out1 == 1'b0 ? RAM2_addr_cntr_out1 :
              count_value_4);

  assign count_14 = (Trigger_Reset_when_Going_to_processing_mode_Y == 1'b0 ? count_13 :
              count_reset_4);

  always @(posedge clk or posedge reset)
    begin : RAM2_addr_cntr_process
      if (reset == 1'b1) begin
        RAM2_addr_cntr_out1 <= 12'b000000000000;
      end
      else begin
        if (enb) begin
          RAM2_addr_cntr_out1 <= count_14;
        end
      end
    end

  SinglePortRAM_generic_block #(.AddrWidth(12),
                                .DataWidth(10)
                                )
                              u_RAM2 (.clk(clk),
                                      .enb(enb),
                                      .din_re(Constant4_out1_re),
                                      .din_im(Constant4_out1_im),
                                      .addr(RAM2_addr_cntr_out1),
                                      .we(Constant2_out1),
                                      .dout_re(RAM2_out1_re),
                                      .dout_im(RAM2_out1_im)
                                      );

  assign Constant7_out1_re = 10'sb0000000000;
  assign Constant7_out1_im = 10'sb0000000000;

  assign Switch1_out1_re = (switch_compare_1_1 == 1'b0 ? RAM2_out1_re :
              Constant7_out1_re);
  assign Switch1_out1_im = (switch_compare_1_1 == 1'b0 ? RAM2_out1_im :
              Constant7_out1_im);

  Discrete_FIR_Filter1 u_Discrete_FIR_Filter1 (.clk(clk),
                                               .reset(reset),
                                               .enb(enb),
                                               .Discrete_FIR_Filter1_in_re(Switch1_out1_re),  // sfix10_En8
                                               .Discrete_FIR_Filter1_in_im(Switch1_out1_im),  // sfix10_En8
                                               .Discrete_FIR_Filter1_out_re(Discrete_FIR_Filter1_out1_re),  // sfix64_En32
                                               .Discrete_FIR_Filter1_out_im(Discrete_FIR_Filter1_out1_im)  // sfix64_En32
                                               );

  // Downsample1: Downsample by 5, Sample offset 0 
  // Downsample bypass register
  always @(posedge clk or posedge reset)
    begin : Downsample1_bypass_process
      if (reset == 1'b1) begin
        Downsample1_bypass_reg_re <= 64'sh0000000000000000;
        Downsample1_bypass_reg_im <= 64'sh0000000000000000;
      end
      else begin
        if (enb_1_5_1) begin
          Downsample1_bypass_reg_im <= Discrete_FIR_Filter1_out1_im;
          Downsample1_bypass_reg_re <= Discrete_FIR_Filter1_out1_re;
        end
      end
    end

  assign Downsample1_out1_re = (enb_1_5_1 == 1'b1 ? Discrete_FIR_Filter1_out1_re :
              Downsample1_bypass_reg_re);
  assign Downsample1_out1_im = (enb_1_5_1 == 1'b1 ? Discrete_FIR_Filter1_out1_im :
              Downsample1_bypass_reg_im);

  assign Data_Type_Conversion2_out1_re = ((Downsample1_out1_re[63] == 1'b0) && (Downsample1_out1_re[62:32] != 31'b0000000000000000000000000000000) ? 12'sb011111111111 :
              ((Downsample1_out1_re[63] == 1'b1) && (Downsample1_out1_re[62:32] != 31'b1111111111111111111111111111111) ? 12'sb100000000000 :
              $signed(Downsample1_out1_re[32:21])));
  assign Data_Type_Conversion2_out1_im = ((Downsample1_out1_im[63] == 1'b0) && (Downsample1_out1_im[62:32] != 31'b0000000000000000000000000000000) ? 12'sb011111111111 :
              ((Downsample1_out1_im[63] == 1'b1) && (Downsample1_out1_im[62:32] != 31'b1111111111111111111111111111111) ? 12'sb100000000000 :
              $signed(Downsample1_out1_im[32:21])));

  assign Add_stage2_add_cast = {{20{Data_Type_Conversion_out1_re[11]}}, Data_Type_Conversion_out1_re};
  assign Add_stage2_add_cast_1 = {{20{Data_Type_Conversion2_out1_re[11]}}, Data_Type_Conversion2_out1_re};
  assign Add_stage2_add_temp = Add_stage2_add_cast + Add_stage2_add_cast_1;
  assign Add_op_stage1_re = Add_stage2_add_temp[12:0];
  assign Add_stage2_add_cast_2 = {{20{Data_Type_Conversion_out1_im[11]}}, Data_Type_Conversion_out1_im};
  assign Add_stage2_add_cast_3 = {{20{Data_Type_Conversion2_out1_im[11]}}, Data_Type_Conversion2_out1_im};
  assign Add_stage2_add_temp_1 = Add_stage2_add_cast_2 + Add_stage2_add_cast_3;
  assign Add_op_stage1_im = Add_stage2_add_temp_1[12:0];

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 2
  assign count_step_5 = 12'b000000000001;

  assign count_from_5 = 12'b000000000000;

  assign count_reset_5 = 12'b000000000000;

  assign count_15 = Sys_Base_CLK1_out1 + count_step_5;

  assign need_to_wrap_5 = Sys_Base_CLK1_out1 == 12'b000000000010;

  assign count_value_5 = (need_to_wrap_5 == 1'b0 ? count_15 :
              count_from_5);

  assign count_16 = (Constant_out1 == 1'b0 ? Sys_Base_CLK1_out1 :
              count_value_5);

  assign count_17 = (EN_CLK_3_out1 == 1'b0 ? count_16 :
              count_reset_5);

  always @(posedge clk or posedge reset)
    begin : Sys_Base_CLK1_process
      if (reset == 1'b1) begin
        Sys_Base_CLK1_out1 <= 12'b000000000000;
      end
      else begin
        if (enb) begin
          Sys_Base_CLK1_out1 <= count_17;
        end
      end
    end

  assign EN_CLK_3_out1 = Sys_Base_CLK1_out1 == 12'b000000000010;

  assign switch_compare_1_2 = EN_CLK_3_out1 > 1'b0;

  assign Constant5_out1_re = 12'sb000000000000;
  assign Constant5_out1_im = 12'sb000000000000;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 3000
  assign count_step_6 = 12'b000000000001;

  assign count_from_6 = 12'b000000000000;

  assign count_reset_6 = 12'b000000000000;

  assign count_18 = RAM3_addr_cntr_out1 + count_step_6;

  assign need_to_wrap_6 = RAM3_addr_cntr_out1 == 12'b101110111000;

  assign count_value_6 = (need_to_wrap_6 == 1'b0 ? count_18 :
              count_from_6);

  assign count_19 = (EN_CLK_3_out1 == 1'b0 ? RAM3_addr_cntr_out1 :
              count_value_6);

  assign count_20 = (Trigger_Reset_when_Going_to_processing_mode_Y == 1'b0 ? count_19 :
              count_reset_6);

  always @(posedge clk or posedge reset)
    begin : RAM3_addr_cntr_process
      if (reset == 1'b1) begin
        RAM3_addr_cntr_out1 <= 12'b000000000000;
      end
      else begin
        if (enb) begin
          RAM3_addr_cntr_out1 <= count_20;
        end
      end
    end

  SinglePortRAM_generic_block1 #(.AddrWidth(12),
                                 .DataWidth(12)
                                 )
                               u_RAM3 (.clk(clk),
                                       .enb(enb),
                                       .din_re(Constant5_out1_re),
                                       .din_im(Constant5_out1_im),
                                       .addr(RAM3_addr_cntr_out1),
                                       .we(Constant2_out1),
                                       .dout_re(RAM3_out1_re),
                                       .dout_im(RAM3_out1_im)
                                       );

  assign Constant8_out1_re = 12'sb000000000000;
  assign Constant8_out1_im = 12'sb000000000000;

  assign Switch_out1_re = (switch_compare_1_2 == 1'b0 ? RAM3_out1_re :
              Constant8_out1_re);
  assign Switch_out1_im = (switch_compare_1_2 == 1'b0 ? RAM3_out1_im :
              Constant8_out1_im);

  Discrete_FIR_Filter2 u_Discrete_FIR_Filter2 (.clk(clk),
                                               .reset(reset),
                                               .enb(enb),
                                               .Discrete_FIR_Filter2_in_re(Switch_out1_re),  // sfix12_En10
                                               .Discrete_FIR_Filter2_in_im(Switch_out1_im),  // sfix12_En10
                                               .Discrete_FIR_Filter2_out_re(Discrete_FIR_Filter2_out1_re),  // sfix64_En34
                                               .Discrete_FIR_Filter2_out_im(Discrete_FIR_Filter2_out1_im)  // sfix64_En34
                                               );

  // Downsample: Downsample by 5, Sample offset 0 
  // Downsample bypass register
  always @(posedge clk or posedge reset)
    begin : Downsample_bypass_process
      if (reset == 1'b1) begin
        Downsample_bypass_reg_re <= 64'sh0000000000000000;
        Downsample_bypass_reg_im <= 64'sh0000000000000000;
      end
      else begin
        if (enb_1_5_1) begin
          Downsample_bypass_reg_im <= Discrete_FIR_Filter2_out1_im;
          Downsample_bypass_reg_re <= Discrete_FIR_Filter2_out1_re;
        end
      end
    end

  assign Downsample_out1_re = (enb_1_5_1 == 1'b1 ? Discrete_FIR_Filter2_out1_re :
              Downsample_bypass_reg_re);
  assign Downsample_out1_im = (enb_1_5_1 == 1'b1 ? Discrete_FIR_Filter2_out1_im :
              Downsample_bypass_reg_im);

  assign Data_Type_Conversion1_out1_re = ((Downsample_out1_re[63] == 1'b0) && (Downsample_out1_re[62:34] != 29'b00000000000000000000000000000) ? 12'sb011111111111 :
              ((Downsample_out1_re[63] == 1'b1) && (Downsample_out1_re[62:34] != 29'b11111111111111111111111111111) ? 12'sb100000000000 :
              $signed(Downsample_out1_re[34:23])));
  assign Data_Type_Conversion1_out1_im = ((Downsample_out1_im[63] == 1'b0) && (Downsample_out1_im[62:34] != 29'b00000000000000000000000000000) ? 12'sb011111111111 :
              ((Downsample_out1_im[63] == 1'b1) && (Downsample_out1_im[62:34] != 29'b11111111111111111111111111111) ? 12'sb100000000000 :
              $signed(Downsample_out1_im[34:23])));

  assign Add_stage3_add_cast = {{19{Add_op_stage1_re[12]}}, Add_op_stage1_re};
  assign Add_stage3_add_cast_1 = {{20{Data_Type_Conversion1_out1_re[11]}}, Data_Type_Conversion1_out1_re};
  assign Add_stage3_add_temp = Add_stage3_add_cast + Add_stage3_add_cast_1;
  assign Add_out1_re = Add_stage3_add_temp[15:0];
  assign Add_stage3_add_cast_2 = {{19{Add_op_stage1_im[12]}}, Add_op_stage1_im};
  assign Add_stage3_add_cast_3 = {{20{Data_Type_Conversion1_out1_im[11]}}, Data_Type_Conversion1_out1_im};
  assign Add_stage3_add_temp_1 = Add_stage3_add_cast_2 + Add_stage3_add_cast_3;
  assign Add_out1_im = Add_stage3_add_temp_1[15:0];

  assign Output_data_type_out1_re = Add_out1_re[13:0];
  assign Output_data_type_out1_im = Add_out1_im[13:0];

  assign Constant6_out1 = 1'b1;

  SinglePortRAM_generic_block2 #(.AddrWidth(12),
                                 .DataWidth(14)
                                 )
                               u_Single_Port_RAM_System3 (.clk(clk),
                                                          .enb_1_5_0(enb_1_5_0),
                                                          .din_re(Output_data_type_out1_re),
                                                          .din_im(Output_data_type_out1_im),
                                                          .addr(Sys_Base_CLK_out1),
                                                          .we(Constant6_out1),
                                                          .dout_re(Single_Port_RAM_System3_out1_re),
                                                          .dout_im(Single_Port_RAM_System3_out1_im)
                                                          );

  assign Out1_re = Single_Port_RAM_System3_out1_re;

  assign Out1_im = Single_Port_RAM_System3_out1_im;

  assign ce_out = enb_1_5_1;

endmodule  // dsp_proj_v3_2024_n

