// -------------------------------------------------------------
// 
// File Name: hdlsrc\dsp_proj_v3_2024_n\Positive.v
// Created: 2026-04-12 08:40:34
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Positive
// Source Path: dsp_proj_v3_2024_n/Trigger Reset when  Going to processing mode/Positive
// Hierarchy Level: 2
// Model version: 3.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Positive
          (u,
           y);


  input   u;
  output  y;


  wire Constant_out1;
  wire Compare_out1;


  assign Constant_out1 = 1'b0;

  assign Compare_out1 = u > Constant_out1;

  assign y = Compare_out1;

endmodule  // Positive

