// -------------------------------------------------------------
// 
// File Name: hdlsrc\dsp_proj_v3_2024_n\SinglePortRAM_generic_block2.v
// Created: 2026-04-12 08:40:35
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SinglePortRAM_generic_block2
// Source Path: dsp_proj_v3_2024_n/SinglePortRAM_generic
// Hierarchy Level: 1
// Model version: 3.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SinglePortRAM_generic_block2
          (clk,
           enb_1_5_0,
           din_re,
           din_im,
           addr,
           we,
           dout_re,
           dout_im);

  parameter integer AddrWidth = 1;
  parameter integer DataWidth = 1;

  input   clk;
  input   enb_1_5_0;
  input   signed [DataWidth - 1:0] din_re;  // parameterized width
  input   signed [DataWidth - 1:0] din_im;  // parameterized width
  input   [AddrWidth - 1:0] addr;  // parameterized width
  input   we;  // ufix1
  output  signed [DataWidth - 1:0] dout_re;  // parameterized width
  output  signed [DataWidth - 1:0] dout_im;  // parameterized width


  reg  [DataWidth*2 - 1:0] ram [2**AddrWidth - 1:0];
  reg  [DataWidth*2 - 1:0] data_int;
  integer i;

  initial begin
    for (i=0; i<=2**AddrWidth - 1; i=i+1) begin
      ram[i] = 0;
    end
    data_int = 0;
  end


  always @(posedge clk)
    begin : SinglePortRAM_generic_process
      if (enb_1_5_0 == 1'b1) begin
        if (we == 1'b1) begin
          ram[addr] <= {din_re, din_im};
          data_int <= {din_re, din_im};
        end
        else begin
          data_int <= ram[addr];
        end
      end
    end

  assign dout_re = data_int[DataWidth*2-1:DataWidth];
  assign dout_im = data_int[DataWidth-1:0];

endmodule  // SinglePortRAM_generic_block2

