// -------------------------------------------------------------
// 
// File Name: hdlsrc\dsp_proj_v3_2024_n\Trigger_Reset_when_Going_to_processing_mode.v
// Created: 2026-04-12 08:40:34
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Trigger_Reset_when_Going_to_processing_mode
// Source Path: dsp_proj_v3_2024_n/Trigger Reset when  Going to processing mode
// Hierarchy Level: 1
// Model version: 3.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Trigger_Reset_when_Going_to_processing_mode
          (clk,
           reset,
           enb,
           U,
           Y);


  input   clk;
  input   reset;
  input   enb;
  input   U;
  output  Y;


  wire U_k;
  reg  U_k_1;
  wire FixPt_Relational_Operator_out1;

  // U(k)
  // Edge


  Positive u_Positive (.u(U),
                       .y(U_k)
                       );

  // 
  // Store in Global RAM
  always @(posedge clk or posedge reset)
    begin : Delay_Input1_process
      if (reset == 1'b1) begin
        U_k_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          U_k_1 <= U_k;
        end
      end
    end

  assign FixPt_Relational_Operator_out1 = U_k > U_k_1;

  assign Y = FixPt_Relational_Operator_out1;

endmodule  // Trigger_Reset_when_Going_to_processing_mode

